"""Generated explicit OBLib header ownership; do not edit by hand."""

OBLIB_HEADER_TARGETS = {
    "common_sql_mode": {
        "hdrs": [
        "common/sql_mode/ob_sql_mode.h",
    ],
        "deps": [],
    },
    "oblib_collections_advanced": {
        "hdrs": [
        "lib/container/ob_bitmap.h",
        "lib/container/ob_fast_array.h",
        "lib/container/ob_fixed_array.h",
        "lib/container/ob_id_map.h",
        "lib/container/ob_int_flags.h",
        "lib/container/ob_loser_tree.h",
        "lib/container/ob_vector.h",
        "lib/container/ob_vector.ipp",
        "lib/hash/ob_array_hash_map.h",
        "lib/hash/ob_build_in_hashmap.h",
        "lib/hash/ob_cuckoo_hashmap.h",
        "lib/hash/ob_hashmap.h",
        "lib/hash/ob_hashset.h",
        "lib/hash/ob_hashtable.h",
        "lib/hash/ob_hashutils.h",
        "lib/hash/ob_pointer_hashmap.h",
        "lib/hash/ob_ptr_array_map.h",
        "lib/hash/ob_serialization.h",
    ],
        "deps": [
        ":oblib_collections_base",
        ":oblib_collections_primitives",
        ":oblib_collections_runtime",
        ":oblib_concurrency_runtime_base",
        ":oblib_concurrency_support",
        ":oblib_core_advanced",
        ":oblib_core_utilities",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
        ":oblib_memory_base",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_collections_base": {
        "hdrs": [
        "lib/hash_func/ob_hash_func.h",
    ],
        "deps": [
        ":oblib_collections_primitives",
        ":oblib_foundation",
    ],
    },
    "oblib_collections_model": {
        "hdrs": [
        "lib/container/ob_ext_ring_buffer.h",
        "lib/container/ob_ext_ring_buffer_impl.h",
        "lib/hash/ob_linear_hash_map.h",
        "lib/hash/ob_link_hashmap.h",
        "lib/hash/ob_link_hashmap_deps.h",
    ],
        "deps": [
        ":oblib_concurrency_runtime_base",
        ":oblib_core_advanced",
        ":oblib_core_utilities",
        ":oblib_foundation_base",
        ":oblib_foundation_integration",
        ":oblib_foundation_services",
        ":oblib_memory_advanced",
        ":oblib_memory_base",
        ":oblib_memory_model",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_collections_primitives": {
        "hdrs": [
        "lib/hash/fnv_hash.h",
        "lib/hash/mprotect.h",
        "lib/hash_func/murmur_hash.h",
        "lib/hash_func/wyhash.h",
        "lib/hash_func/xxhash.h",
    ],
        "deps": [],
    },
    "oblib_collections_runtime": {
        "hdrs": [
        "lib/container/ob_array_helper.h",
        "lib/container/ob_iarray.h",
        "lib/container/ob_tuple.h",
        "lib/string/ob_sql_string.h",
        "lib/string/ob_string_buffer.h",
    ],
        "deps": [
        ":oblib_concurrency_support",
        ":oblib_core_utilities",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_collections_runtime_base": {
        "hdrs": [
        "lib/container/ob_concurrent_bitset.h",
        "lib/hash/ob_darray.h",
        "lib/hash/ob_fixed_hash2.h",
        "lib/hash/ob_hash.h",
    ],
        "deps": [
        ":oblib_concurrency_runtime_base",
        ":oblib_foundation_base",
        ":oblib_memory_base",
    ],
    },
    "oblib_collections_utilities": {
        "hdrs": [
        "lib/string/ob_string_holder.h",
    ],
        "deps": [
        ":oblib_foundation_support",
        ":oblib_memory_base",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_common": {
        "hdrs": [
        "common/ob_range.h",
        "common/ob_store_range.h",
        "common/ob_string_buf.h",
        "common/object/ob_obj_funcs.h",
        "common/row/ob_row.h",
        "common/row/ob_row_iterator.h",
        "common/row/ob_row_store.h",
        "common/row/ob_row_util.h",
        "common/rowkey/ob_store_rowkey.h",
        "common/storage/ob_freeze_define.h",
    ],
        "deps": [
        ":oblib_collections_advanced",
        ":oblib_core_advanced",
        ":oblib_data_formats_domain",
        ":oblib_data_formats_model",
        ":oblib_db_values_integration",
        ":oblib_db_values_model",
        ":oblib_db_values_runtime",
        ":oblib_db_values_services",
        ":oblib_encoding_primitives",
        ":oblib_encoding_runtime",
        ":oblib_foundation_base",
        ":oblib_foundation_services",
        ":oblib_foundation_support",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_compression": {
        "hdrs": [
        "lib/compress/ob_compressor_pool.h",
    ],
        "deps": [
        ":oblib_compression_support",
        ":oblib_foundation_integration",
    ],
    },
    "oblib_compression_integration": {
        "hdrs": [
        "lib/oblog/ob_log_compressor.h",
    ],
        "deps": [
        ":oblib_compression_support",
        ":oblib_concurrency_support",
        ":oblib_foundation_integration",
        ":oblib_foundation_services",
    ],
    },
    "oblib_compression_primitives": {
        "hdrs": [
        "lib/compress/zstd_1_3_8/ob_zstd_wrapper.h",
    ],
        "deps": [],
    },
    "oblib_compression_support": {
        "hdrs": [
        "lib/compress/none/ob_none_compressor.h",
        "lib/compress/ob_compress_util.h",
        "lib/compress/ob_compressor.h",
        "lib/compress/zlib/ob_zlib_compressor.h",
        "lib/compress/zstd_1_3_8/ob_zstd_compressor_1_3_8.h",
    ],
        "deps": [
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
        ":oblib_memory_base",
        "@seekdb_3rd_headers//:zlib_headers",
    ],
    },
    "oblib_concurrency_advanced": {
        "hdrs": [
        "lib/guard/ob_light_shared_gaurd.h",
        "lib/list/ob_list.h",
        "lib/lock/ob_drw_lock.h",
        "lib/thread/ob_balance_filter.h",
        "lib/thread/ob_queue_thread.h",
    ],
        "deps": [
        ":oblib_collections_advanced",
        ":oblib_concurrency_primitives",
        ":oblib_concurrency_support",
        ":oblib_core_advanced",
        ":oblib_core_utilities",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_runtime",
        ":oblib_io_runtime",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_concurrency_model": {
        "hdrs": [
        "lib/thread/ob_async_task_queue.h",
        "lib/thread/ob_dedup_queue.h",
    ],
        "deps": [
        ":oblib_collections_advanced",
        ":oblib_concurrency_runtime_base",
        ":oblib_concurrency_support",
        ":oblib_core_advanced",
        ":oblib_foundation_base",
        ":oblib_foundation_runtime",
        ":oblib_foundation_services",
        ":oblib_memory_model",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_concurrency_primitives": {
        "hdrs": [
        "lib/atomic/ob_atomic_reference.h",
        "lib/coro/co_var.h",
        "lib/guard/ob_scope_guard.h",
        "lib/lock/ob_lock.h",
        "lib/lock/ob_rwlock.h",
        "lib/thread/ob_priority_scheduler.h",
        "lib/thread/ob_thread_name.h",
    ],
        "deps": [],
    },
    "oblib_concurrency_runtime_base": {
        "hdrs": [
        "lib/lock/ob_mutex.h",
        "lib/lock/ob_recursive_mutex.h",
        "lib/lock/ob_spin_lock.h",
        "lib/lock/ob_spin_rwlock.h",
        "lib/queue/ob_priority_queue.h",
        "lib/thread/protected_stack_allocator.h",
    ],
        "deps": [
        ":oblib_concurrency_support",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
        ":oblib_memory_base",
    ],
    },
    "oblib_concurrency_support": {
        "hdrs": [
        "lib/list/ob_dlist.h",
        "lib/lock/cond.h",
        "lib/lock/ob_futex.h",
        "lib/lock/ob_latch.h",
        "lib/lock/ob_lock_guard.h",
        "lib/lock/ob_monitor.h",
        "lib/lock/ob_scond.h",
        "lib/lock/ob_thread_cond.h",
        "lib/queue/ob_fixed_queue.h",
        "lib/queue/ob_lighty_queue.h",
    ],
        "deps": [
        ":oblib_concurrency_primitives",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
        ":oblib_memory_base",
    ],
    },
    "oblib_concurrency_utilities": {
        "hdrs": [
        "lib/thread_local/ob_tsi_factory.h",
    ],
        "deps": [
        ":oblib_diagnostics_utilities",
    ],
    },
    "oblib_core_advanced": {
        "hdrs": [
        "lib/utility/ob_smart_call.h",
        "lib/utility/ob_sort.h",
        "lib/utility/ob_tracepoint.h",
        "lib/utility/utility.h",
    ],
        "deps": [
        "//src/oblib/easy:easy",
        ":oblib_collections_runtime",
        ":oblib_concurrency_primitives",
        ":oblib_concurrency_runtime_base",
        ":oblib_concurrency_support",
        ":oblib_core_utilities",
        ":oblib_diagnostics_runtime",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_runtime",
        ":oblib_memory_base",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_core_utilities": {
        "hdrs": [
        "lib/utility/ob_print_utils.h",
    ],
        "deps": [
        ":oblib_collections_primitives",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
        ":oblib_memory_base",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_data_formats_domain": {
        "hdrs": [
        "common/json_type/ob_json_parse.h",
        "common/json_type/ob_json_schema.h",
        "common/udt/ob_array_binary.h",
        "common/udt/ob_array_fixed_size.h",
        "common/udt/ob_array_fixed_size.ipp",
        "common/udt/ob_array_nested.h",
        "common/udt/ob_array_type.h",
        "common/udt/ob_array_utils.h",
        "common/udt/ob_collection_type.h",
        "common/udt/ob_map_type.h",
        "common/udt/ob_udt_type.h",
        "common/udt/ob_vector_type.h",
        "common/xml/ob_binary_aggregate.h",
        "common/xml/ob_xml_util.h",
        "common/xml/ob_xpath.h",
    ],
        "deps": [
        ":oblib_collections_advanced",
        ":oblib_collections_runtime",
        ":oblib_data_formats_integration",
        ":oblib_data_formats_model",
        ":oblib_db_values_model",
        ":oblib_db_values_primitives",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_integration",
        ":oblib_foundation_services",
        ":oblib_foundation_support",
        ":oblib_memory_utilities",
        ":oblib_mysql_client_runtime",
        "@seekdb_3rd_headers//:rapidjson_headers",
    ],
    },
    "oblib_data_formats_integration": {
        "hdrs": [
        "common/json_type/ob_json_path.h",
        "common/xml/ob_libxml2_sax_handler.h",
        "common/xml/ob_mul_mode_reader.h",
        "common/xml/ob_multi_mode_bin.h",
        "common/xml/ob_multi_mode_interface.h",
        "common/xml/ob_tree_base.h",
        "common/xml/ob_xml_parser.h",
        "common/xml/ob_xml_tree.h",
    ],
        "deps": [
        ":oblib_collections_advanced",
        ":oblib_collections_runtime",
        ":oblib_data_formats_services",
        ":oblib_db_values_runtime",
        ":oblib_db_values_services",
        ":oblib_foundation_base",
        ":oblib_foundation_integration",
        ":oblib_foundation_services",
        ":oblib_foundation_support",
        ":oblib_memory_utilities",
        "@seekdb_3rd_headers//:libxml2_headers",
    ],
    },
    "oblib_data_formats_model": {
        "hdrs": [
        "common/json_type/ob_json_base.h",
        "common/json_type/ob_json_bin.h",
        "common/json_type/ob_json_diff.h",
        "common/json_type/ob_json_tree.h",
    ],
        "deps": [
        ":oblib_collections_advanced",
        ":oblib_data_formats_integration",
        ":oblib_data_formats_services",
        ":oblib_db_values_model",
        ":oblib_db_values_runtime",
        ":oblib_db_values_services",
        ":oblib_encoding_base",
        ":oblib_foundation_base",
        ":oblib_foundation_integration",
        ":oblib_foundation_services",
        ":oblib_foundation_support",
        ":oblib_mysql_client_runtime",
        "@seekdb_3rd_headers//:rapidjson_headers",
    ],
    },
    "oblib_data_formats_services": {
        "hdrs": [
        "common/json_type/ob_json_common.h",
    ],
        "deps": [
        ":oblib_collections_runtime",
        ":oblib_db_values_services",
    ],
    },
    "oblib_db_log_advanced": {
        "hdrs": [
        "common/log/ob_log_cursor.h",
        "common/log/ob_log_data_writer.h",
        "common/log/ob_log_entry.h",
        "common/log/ob_log_generator.h",
    ],
        "deps": [
        ":oblib_concurrency_runtime_base",
        ":oblib_db_log_primitives",
        ":oblib_db_values_advanced",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
        ":oblib_io_runtime",
    ],
    },
    "oblib_db_log_primitives": {
        "hdrs": [
        "common/log/ob_log_constants.h",
    ],
        "deps": [],
    },
    "oblib_db_meta_domain": {
        "hdrs": [
        "common/expression/ob_expr_string_buf.h",
    ],
        "deps": [
        ":oblib_common",
    ],
    },
    "oblib_db_meta_runtime": {
        "hdrs": [
        "common/meta_programming/ob_meta_compare.h",
        "common/meta_programming/ob_meta_copy.h",
        "common/meta_programming/ob_meta_serialization.h",
        "common/meta_programming/ob_meta_swap.h",
        "common/meta_programming/ob_mover.h",
        "common/meta_programming/ob_type_traits.h",
    ],
        "deps": [
        ":oblib_core_utilities",
        ":oblib_db_meta_support",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_memory_base",
    ],
    },
    "oblib_db_meta_support": {
        "hdrs": [
        "common/meta_programming/ob_meta_define.h",
    ],
        "deps": [
        ":oblib_memory_base",
    ],
    },
    "oblib_db_values_advanced": {
        "hdrs": [
        "common/ob_record_header.h",
        "common/storage/ob_sequence.h",
    ],
        "deps": [
        ":oblib_core_advanced",
        ":oblib_encoding_runtime",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_runtime",
        ":oblib_foundation_support",
    ],
    },
    "oblib_db_values_base": {
        "hdrs": [
        "common/ob_role_mgr.h",
    ],
        "deps": [
        ":oblib_foundation_base",
    ],
    },
    "oblib_db_values_integration": {
        "hdrs": [
        "common/ob_simple_iterator.h",
        "common/row/ob_row_desc.h",
    ],
        "deps": [
        ":oblib_foundation_base",
        ":oblib_foundation_integration",
        ":oblib_foundation_services",
    ],
    },
    "oblib_db_values_model": {
        "hdrs": [
        "common/datum/ob_datum.h",
        "common/enumset/ob_enum_set_meta.h",
        "common/ob_field.h",
        "common/ob_string_buf.ipp",
        "common/object/ob_obj_compare.h",
        "common/object/ob_object.h",
        "common/rowkey/ob_rowkey.h",
        "common/rowkey/ob_rowkey_info.h",
        "common/sql_mode/ob_sql_mode_utils.h",
        "common/timezone/ob_timezone_info.h",
    ],
        "deps": [
        ":common_sql_mode",
        ":oblib_collections_advanced",
        ":oblib_collections_base",
        ":oblib_collections_model",
        ":oblib_collections_runtime",
        ":oblib_core_advanced",
        ":oblib_core_utilities",
        ":oblib_db_values_primitives",
        ":oblib_db_values_runtime",
        ":oblib_db_values_services",
        ":oblib_encoding_base",
        ":oblib_encoding_runtime",
        ":oblib_foundation_base",
        ":oblib_foundation_integration",
        ":oblib_foundation_services",
        ":oblib_foundation_support",
        ":oblib_memory_base",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_db_values_primitives": {
        "hdrs": [
        "common/ob_action_flag.h",
        "common/ob_role.h",
        "common/wide_integer/ob_wide_integer_cmp_funcs.h",
        "common/wide_integer/ob_wide_integer_helper.h",
        "common/wide_integer/ob_wide_integer_impl.h",
        "common/wide_integer/ob_wide_integer_str_funcs.h",
    ],
        "deps": [],
    },
    "oblib_db_values_runtime": {
        "hdrs": [
        "common/ob_accuracy.h",
        "common/ob_common_types.h",
        "common/ob_data_version_mgr.h",
        "common/ob_store_format.h",
        "common/ob_timeout_ctx.h",
        "common/ob_version_def.h",
        "common/ob_zerofill_info.h",
        "common/object/ob_obj_type.h",
        "common/timezone/ob_time_convert.h",
        "common/timezone/ob_time_def.h",
    ],
        "deps": [
        ":common_sql_mode",
        ":oblib_core_utilities",
        ":oblib_encoding_runtime",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_db_values_services": {
        "hdrs": [
        "common/cell/ob_cell_writer.h",
        "common/lob/ob_lob_base.h",
        "common/number/ob_number_v2.h",
        "common/ob_tablet_id.h",
        "common/wide_integer/ob_wide_integer.h",
    ],
        "deps": [
        ":oblib_collections_advanced",
        ":oblib_collections_runtime",
        ":oblib_core_advanced",
        ":oblib_core_utilities",
        ":oblib_db_values_primitives",
        ":oblib_db_values_runtime",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_services",
        ":oblib_foundation_support",
    ],
    },
    "oblib_db_values_support": {
        "hdrs": [
        "common/ob_hex_utils_base.h",
    ],
        "deps": [
        ":oblib_foundation_support",
        ":oblib_memory_base",
    ],
    },
    "oblib_diagnostics_advanced": {
        "hdrs": [
        "lib/trace/ob_trace.h",
    ],
        "deps": [
        ":oblib_concurrency_support",
        ":oblib_core_advanced",
        ":oblib_foundation_base",
    ],
    },
    "oblib_diagnostics_primitives": {
        "hdrs": [
        "lib/oblog/ob_easy_log.h",
        "lib/oblog/ob_log_level.h",
        "lib/oblog/ob_log_time_fmt.h",
        "lib/wait_event/ob_inner_sql_wait_type.h",
    ],
        "deps": [],
    },
    "oblib_diagnostics_runtime": {
        "hdrs": [
        "lib/oblog/ob_trace_log.h",
        "lib/profile/ob_trace_id.h",
        "lib/stat/ob_diagnose_info.h",
        "lib/stat/ob_diagnostic_info_guard.h",
        "lib/trace/ob_trace_event.h",
    ],
        "deps": [
        ":oblib_concurrency_runtime_base",
        ":oblib_concurrency_utilities",
        ":oblib_core_utilities",
        ":oblib_diagnostics_primitives",
        ":oblib_diagnostics_support",
        ":oblib_encoding_runtime",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_runtime",
        ":oblib_foundation_support",
        ":oblib_io_runtime",
    ],
    },
    "oblib_diagnostics_services": {
        "hdrs": [
        "lib/oblog/ob_warning_buffer.h",
    ],
        "deps": [
        ":oblib_core_utilities",
        ":oblib_foundation_base",
        ":oblib_foundation_services",
        ":oblib_foundation_support",
    ],
    },
    "oblib_diagnostics_support": {
        "hdrs": [
        "lib/profile/ob_trace_id_adaptor.h",
        "lib/signal/ob_signal_struct.h",
        "lib/signal/ob_signal_utils.h",
        "lib/stat/ob_stat_template.h",
        "lib/statistic_event/ob_stat_event.h",
        "lib/trace/ob_seq_event_recorder.h",
    ],
        "deps": [
        "//src/oblib/easy:easy",
        ":oblib_concurrency_primitives",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
    ],
    },
    "oblib_diagnostics_utilities": {
        "hdrs": [
        "lib/stat/ob_di_tls.h",
    ],
        "deps": [
        ":oblib_foundation_base",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_encoding_advanced": {
        "hdrs": [
        "lib/json/ob_json.h",
        "lib/json/ob_json_print_utils.h",
    ],
        "deps": [
        ":oblib_concurrency_advanced",
        ":oblib_concurrency_support",
        ":oblib_core_utilities",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
        ":oblib_memory_utilities",
        "@seekdb_3rd_headers//:rapidjson_headers",
    ],
    },
    "oblib_encoding_base": {
        "hdrs": [
        "lib/charset/mb_wc.h",
        "lib/charset/ob_ctype.h",
        "lib/charset/ob_dtoa.h",
        "lib/charset/ob_mysql_global.h",
    ],
        "deps": [
        ":oblib_collections_primitives",
        ":oblib_encoding_primitives",
    ],
    },
    "oblib_encoding_primitives": {
        "hdrs": [
        "lib/charset/ob_config.h",
        "lib/charset/ob_template_helper.h",
        "lib/checksum/ob_parity_check.h",
        "lib/encode/ob_base64_encode.h",
    ],
        "deps": [],
    },
    "oblib_encoding_runtime": {
        "hdrs": [
        "lib/charset/ob_charset.h",
        "lib/charset/ob_charset_string_helper.h",
        "lib/checksum/ob_crc64.h",
        "lib/json/ob_yson.h",
    ],
        "deps": [
        ":oblib_concurrency_primitives",
        ":oblib_core_utilities",
        ":oblib_encoding_base",
        ":oblib_encoding_primitives",
        ":oblib_encoding_support",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
    ],
    },
    "oblib_encoding_support": {
        "hdrs": [
        "lib/encrypt/ob_encrypted_helper.h",
        "lib/json/ob_yson_encode.h",
    ],
        "deps": [
        ":oblib_diagnostics_support",
        ":oblib_foundation",
        ":oblib_foundation_support",
    ],
    },
    "oblib_foundation": {
        "hdrs": [
        "lib/geometry/ob_geo_wkb_define.h",
        "lib/net/ob_sql_tls_info.h",
        "lib/ob_date_unit_type.h",
        "lib/ob_errno.h",
        "lib/ob_name_def.h",
        "lib/ob_name_id_def.h",
        "lib/time/Time.h",
        "lib/utility/ob_backtrace.h",
        "lib/utility/ob_defer.h",
        "lib/utility/ob_macro_utils.h",
        "lib/utility/ob_platform_utils.h",
        "lib/utility/ob_rate_limiter.h",
        "lib/utility/ob_template_utils.h",
        "lib/utility/ob_tracepoint_def.h",
        "lib/utility/ob_utility.h",
    ],
        "deps": [],
    },
    "oblib_foundation_base": {
        "hdrs": [
        "lib/atomic/atomic128.h",
        "lib/atomic/ob_atomic.h",
        "lib/list/ob_atomic_list.h",
        "lib/list/ob_dlink_node.h",
        "lib/list/ob_intrusive_list.h",
        "lib/lock/mutex.h",
        "lib/lock/ob_small_spin_lock.h",
        "lib/metrics/ob_counter.h",
        "lib/ob_abort.h",
        "lib/ob_check_macros.h",
        "lib/ob_define.h",
        "lib/ob_lib_config.h",
        "lib/ob_running_mode.h",
        "lib/oblog/ob_async_log_struct.h",
        "lib/oblog/ob_base_log_writer.h",
        "lib/oblog/ob_log.h",
        "lib/oblog/ob_log_dba_event.h",
        "lib/oblog/ob_log_module.h",
        "lib/oblog/ob_log_print_kv.h",
        "lib/oblog/ob_log_user_msg.h",
        "lib/oblog/ob_ringbuf_log_writer.h",
        "lib/oblog/ob_syslog_rate_limiter.h",
        "lib/queue/ob_link.h",
        "lib/queue/ob_link_queue.h",
        "lib/random/ob_mysql_random.h",
        "lib/random/ob_random.h",
        "lib/rc/ob_rc.h",
        "lib/runtime.h",
        "lib/stat/ob_latch_define.h",
        "lib/statistic_event/ob_stat_class.h",
        "lib/thread/ob_adaptive_worker_pool.h",
        "lib/thread/ob_link_task.h",
        "lib/thread/ob_thread_lease.h",
        "lib/thread_local/ob_tsi_utils.h",
        "lib/time/ob_tsc_timestamp.h",
        "lib/trace/ob_trace_def.h",
        "lib/utility/alloc_assist.h",
        "lib/utility/ob_bits_utils.h",
        "lib/utility/ob_common_utility.h",
        "lib/utility/ob_fast_convert.h",
        "lib/utility/ob_hang_fatal_error.h",
        "lib/utility/ob_mod_define.h",
        "lib/utility/ob_print_kv.h",
        "lib/wait_event/ob_wait_class.h",
        "lib/wait_event/ob_wait_event.h",
    ],
        "deps": [
        ":oblib_collections_base",
        ":oblib_collections_primitives",
        ":oblib_concurrency_primitives",
        ":oblib_diagnostics_primitives",
        ":oblib_foundation",
    ],
    },
    "oblib_foundation_integration": {
        "hdrs": [
        "lib/allocator/ob_qsync.h",
        "lib/allocator/ob_slice_alloc.h",
        "lib/allocator/ob_small_allocator.h",
        "lib/allocator/ob_vslice_alloc.h",
        "lib/container/ob_array_iterator.h",
        "lib/container/ob_array_serialization.h",
        "lib/container/ob_bit_set.h",
        "lib/container/ob_fixed_array_iterator.h",
        "lib/container/ob_rbtree.h",
        "lib/core_local/ob_core_local_storage.h",
        "lib/cpu/ob_cpu_topology.h",
        "lib/hash/ob_array_index_hash_set.h",
        "lib/hash/ob_dchash.h",
        "lib/hash/ob_iteratable_hashmap.h",
        "lib/hash/ob_iteratable_hashset.h",
        "lib/hash/ob_placement_hashmap.h",
        "lib/hash/ob_placement_hashset.h",
        "lib/hash/ob_placement_hashutils.h",
        "lib/lock/ob_qsync_lock.h",
        "lib/lock/ob_tc_ref.h",
        "lib/lock/ob_tc_rwlock.h",
        "lib/objectpool/ob_concurrency_objpool.h",
        "lib/task/ob_timer.h",
        "lib/task/ob_timer_monitor.h",
        "lib/task/ob_timer_service.h",
        "lib/thread/ob_simple_thread_pool.h",
        "lib/thread/ob_simple_thread_pool.ipp",
        "lib/time/ob_cur_time.h",
        "lib/utility/ob_target_specific.h",
    ],
        "deps": [
        ":oblib_collections_advanced",
        ":oblib_collections_base",
        ":oblib_collections_primitives",
        ":oblib_collections_runtime_base",
        ":oblib_concurrency_advanced",
        ":oblib_concurrency_primitives",
        ":oblib_concurrency_runtime_base",
        ":oblib_concurrency_support",
        ":oblib_core_advanced",
        ":oblib_core_utilities",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_runtime",
        ":oblib_foundation_services",
        ":oblib_foundation_support",
        ":oblib_memory_advanced",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_foundation_runtime": {
        "hdrs": [
        "lib/function/ob_function.h",
        "lib/future/ob_future.h",
        "lib/guard/ob_shared_guard.h",
        "lib/guard/ob_unique_guard.h",
        "lib/guard/ob_weak_guard.h",
        "lib/literals/ob_literals.h",
        "lib/thread/ob_test_util.h",
        "lib/thread/thread.h",
        "lib/thread/thread_pool.h",
        "lib/thread/threads.h",
        "lib/time/ob_clock_generator.h",
        "lib/utility/ob_smart_var.h",
    ],
        "deps": [
        "//src/oblib/easy:easy",
        ":oblib_concurrency_runtime_base",
        ":oblib_concurrency_support",
        ":oblib_core_utilities",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
        ":oblib_io_runtime",
        ":oblib_memory_base",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_foundation_services": {
        "hdrs": [
        "lib/container/ob_2d_array.h",
        "lib/container/ob_array.h",
        "lib/container/ob_array_array.h",
        "lib/container/ob_heap.h",
        "lib/container/ob_raw_se_array.h",
        "lib/container/ob_se_array.h",
        "lib/container/ob_se_array_iterator.h",
        "lib/list/ob_obj_store.h",
        "lib/lock/ob_bucket_lock.h",
        "lib/rc/context.h",
        "lib/string/ob_strings.h",
        "lib/thread/ob_dynamic_thread_pool.h",
        "lib/thread/ob_reentrant_thread.h",
        "lib/utility/ob_edit_distance.h",
        "lib/utility/ob_hyperloglog.h",
        "lib/worker.h",
    ],
        "deps": [
        ":oblib_collections_advanced",
        ":oblib_collections_runtime",
        ":oblib_concurrency_support",
        ":oblib_concurrency_utilities",
        ":oblib_core_advanced",
        ":oblib_core_utilities",
        ":oblib_encoding_support",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_runtime",
        ":oblib_foundation_support",
        ":oblib_memory_base",
        ":oblib_memory_primitives",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_foundation_support": {
        "hdrs": [
        "lib/container/ob_array_wrap.h",
        "lib/locale/ob_locale_type.h",
        "lib/string/ob_fixed_length_string.h",
        "lib/string/ob_string.h",
        "lib/time/ob_time_utility.h",
        "lib/utility/data_buffer.h",
        "lib/utility/ob_serialization_helper.h",
        "lib/utility/ob_unify_serialize.h",
        "lib/utility/serialization.h",
    ],
        "deps": [
        ":oblib_concurrency_primitives",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_memory_base",
    ],
    },
    "oblib_io_advanced": {
        "hdrs": [
        "lib/file/ob_file.h",
    ],
        "deps": [
        ":oblib_core_advanced",
        ":oblib_foundation_base",
        ":oblib_io_base",
        ":oblib_memory_utilities",
        "@seekdb_3rd_headers//:libaio_headers",
    ],
    },
    "oblib_io_base": {
        "hdrs": [
        "lib/file/ob_fileinfo_manager.h",
    ],
        "deps": [
        ":oblib_foundation_base",
    ],
    },
    "oblib_io_primitives": {
        "hdrs": [
        "lib/file/file_directory_utils.h",
        "lib/file/ob_string_util.h",
    ],
        "deps": [],
    },
    "oblib_io_runtime": {
        "hdrs": [
        "lib/net/ob_addr.h",
        "lib/net/ob_net_util.h",
    ],
        "deps": [
        "//src/oblib/easy:easy",
        ":oblib_core_utilities",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
    ],
    },
    "oblib_memory_advanced": {
        "hdrs": [
        "lib/allocator/ob_block_alloc_mgr.h",
        "lib/allocator/ob_fixed_size_block_allocator.h",
        "lib/allocator/ob_retire_station.h",
        "lib/objectpool/ob_resource_pool.h",
        "lib/objectpool/ob_tc_factory.h",
    ],
        "deps": [
        ":oblib_collections_advanced",
        ":oblib_concurrency_advanced",
        ":oblib_concurrency_runtime_base",
        ":oblib_concurrency_support",
        ":oblib_core_advanced",
        ":oblib_foundation_base",
        ":oblib_foundation_runtime",
        ":oblib_foundation_support",
        ":oblib_memory_base",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_memory_base": {
        "hdrs": [
        "lib/alloc/abit_set.h",
        "lib/alloc/alloc_failed_reason.h",
        "lib/alloc/alloc_struct.h",
        "lib/alloc/ob_ctx_define.h",
        "lib/alloc/ob_iallocator.h",
        "lib/alloc/ob_malloc_callback.h",
        "lib/allocator/ob_allocator.h",
        "lib/allocator/ob_external_ref.h",
        "lib/allocator/ob_hazard_ref.h",
        "lib/allocator/ob_heavy_ref.h",
        "lib/lds/ob_lds_assist.h",
        "lib/objectpool/ob_pool.ipp",
        "lib/resource/ob_cache_washer.h",
    ],
        "deps": [
        ":oblib_concurrency_primitives",
        ":oblib_foundation",
        ":oblib_foundation_base",
    ],
    },
    "oblib_memory_model": {
        "hdrs": [
        "lib/allocator/ob_concurrent_fifo_allocator.h",
        "lib/allocator/ob_lf_fifo_allocator.h",
    ],
        "deps": [
        ":oblib_foundation_integration",
        ":oblib_memory_base",
    ],
    },
    "oblib_memory_primitives": {
        "hdrs": [
        "lib/alloc/alloc_func.h",
        "lib/alloc/malloc_hook.h",
        "lib/allocator/ob_tc_malloc.h",
        "lib/lds/ob_lds_define.h",
    ],
        "deps": [],
    },
    "oblib_memory_runtime_base": {
        "hdrs": [
        "lib/alloc/block_set.h",
        "lib/alloc/object_mgr.h",
        "lib/alloc/object_set.h",
        "lib/resource/achunk_mgr.h",
        "lib/resource/ob_resource_mgr.h",
    ],
        "deps": [
        ":oblib_concurrency_runtime_base",
        ":oblib_concurrency_support",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
        ":oblib_memory_base",
        ":oblib_memory_support",
    ],
    },
    "oblib_memory_services": {
        "hdrs": [
        "lib/alloc/memory_dump.h",
        "lib/alloc/ob_malloc_sample_struct.h",
        "lib/objectpool/ob_cached_allocator.h",
    ],
        "deps": [
        ":oblib_collections_advanced",
        ":oblib_concurrency_runtime_base",
        ":oblib_concurrency_support",
        ":oblib_foundation_runtime",
        ":oblib_foundation_services",
        ":oblib_memory_base",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_memory_support": {
        "hdrs": [
        "lib/alloc/alloc_interface.h",
    ],
        "deps": [
        ":oblib_foundation_base",
    ],
    },
    "oblib_memory_utilities": {
        "hdrs": [
        "lib/alloc/ob_ctx_allocator.h",
        "lib/alloc/ob_malloc_allocator.h",
        "lib/allocator/ob_allocator_v2.h",
        "lib/allocator/ob_fifo_allocator.h",
        "lib/allocator/ob_jemalloc.h",
        "lib/allocator/ob_malloc.h",
        "lib/allocator/ob_memory_sanity.h",
        "lib/allocator/ob_page_manager.h",
        "lib/allocator/ob_safe_arena.h",
        "lib/allocator/page_arena.h",
        "lib/objectpool/ob_global_factory.h",
        "lib/objectpool/ob_pool.h",
        "lib/objectpool/ob_pooled_allocator.h",
    ],
        "deps": [
        ":oblib_concurrency_primitives",
        ":oblib_concurrency_runtime_base",
        ":oblib_concurrency_support",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
        ":oblib_memory_base",
        ":oblib_memory_primitives",
        ":oblib_memory_runtime_base",
        ":oblib_memory_support",
    ],
    },
    "oblib_mysql_client_domain": {
        "hdrs": [
        "common/mysqlclient/ob_mysql_proxy.h",
    ],
        "deps": [
        ":oblib_db_values_runtime",
        ":oblib_mysql_client_model",
        ":oblib_mysql_client_runtime",
    ],
    },
    "oblib_mysql_client_model": {
        "hdrs": [
        "common/mysqlclient/ob_isql_connection.h",
        "common/mysqlclient/ob_mysql_result.h",
    ],
        "deps": [
        ":oblib_collections_advanced",
        ":oblib_collections_runtime",
        ":oblib_db_values_model",
        ":oblib_db_values_runtime",
        ":oblib_db_values_services",
        ":oblib_foundation_base",
        ":oblib_foundation_runtime",
        ":oblib_foundation_support",
        ":oblib_mysql_client_runtime",
    ],
    },
    "oblib_mysql_client_primitives": {
        "hdrs": [
        "common/mysqlclient/ob_isql_result_handler.h",
    ],
        "deps": [],
    },
    "oblib_mysql_client_runtime": {
        "hdrs": [
        "common/mysqlclient/ob_isql_client.h",
        "common/mysqlclient/ob_mysql_global.h",
        "common/mysqlclient/ob_single_connection_proxy.h",
    ],
        "deps": [
        "//src/oblib/easy:easy",
        ":oblib_core_utilities",
        ":oblib_encoding_base",
        ":oblib_foundation_runtime",
        ":oblib_memory_utilities",
    ],
    },
    "oblib_mysql_client_services": {
        "hdrs": [
        "common/mysqlclient/ob_mysql_transaction.h",
    ],
        "deps": [
        ":oblib_collections_advanced",
        ":oblib_collections_runtime",
        ":oblib_foundation_base",
        ":oblib_mysql_client_runtime",
    ],
    },
    "oblib_mysql_protocol_advanced": {
        "hdrs": [
        "rpc/obmysql/ob_sql_nio_server.h",
        "rpc/obmysql/ob_sql_sock_handler.h",
    ],
        "deps": [
        "//rust:sql_nio_headers",
        ":oblib_mysql_protocol_primitives",
        ":oblib_mysql_protocol_runtime",
    ],
    },
    "oblib_mysql_protocol_domain": {
        "hdrs": [
        "rpc/obmysql/packet/ompk_field.h",
        "rpc/obmysql/packet/ompk_row.h",
    ],
        "deps": [
        ":oblib_mysql_protocol_model",
        ":oblib_mysql_protocol_runtime",
    ],
    },
    "oblib_mysql_protocol_model": {
        "hdrs": [
        "rpc/obmysql/ob_mysql_field.h",
        "rpc/obmysql/ob_mysql_row.h",
        "rpc/obmysql/ob_mysql_util.h",
    ],
        "deps": [
        ":oblib_core_utilities",
        ":oblib_db_values_model",
        ":oblib_db_values_runtime",
        ":oblib_db_values_services",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
        ":oblib_mysql_client_runtime",
        ":oblib_mysql_protocol_runtime",
    ],
    },
    "oblib_mysql_protocol_primitives": {
        "hdrs": [
        "rpc/obmysql/ob_i_cs_mem_pool.h",
        "rpc/obmysql/ob_i_sm_conn_callback.h",
    ],
        "deps": [],
    },
    "oblib_mysql_protocol_runtime": {
        "hdrs": [
        "rpc/obmysql/ob_mysql_packet.h",
        "rpc/obmysql/ob_sql_sock_session.h",
        "rpc/obmysql/obsm_struct.h",
        "rpc/obmysql/packet/ompk_eof.h",
        "rpc/obmysql/packet/ompk_error.h",
        "rpc/obmysql/packet/ompk_local_infile.h",
        "rpc/obmysql/packet/ompk_prepare.h",
        "rpc/obmysql/packet/ompk_resheader.h",
        "rpc/obmysql/packet/ompk_string.h",
    ],
        "deps": [
        "//src/oblib/easy:easy",
        ":oblib_concurrency_support",
        ":oblib_core_utilities",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_runtime",
        ":oblib_foundation_support",
        ":oblib_io_primitives",
        ":oblib_memory_utilities",
        ":oblib_mysql_protocol_primitives",
        ":oblib_rpc",
        ":oblib_rpc_transport_utilities",
    ],
    },
    "oblib_mysql_protocol_services": {
        "hdrs": [
        "rpc/obmysql/ob_login_info.h",
        "rpc/obmysql/packet/ompk_auth_switch.h",
        "rpc/obmysql/packet/ompk_ok.h",
    ],
        "deps": [
        ":oblib_foundation_services",
        ":oblib_foundation_support",
        ":oblib_mysql_protocol_runtime",
    ],
    },
    "oblib_restore_advanced": {
        "hdrs": [
        "lib/restore/ob_io_device.h",
    ],
        "deps": [
        ":oblib_collections_advanced",
        ":oblib_collections_runtime",
        ":oblib_core_utilities",
        ":oblib_foundation_base",
        ":oblib_restore_runtime",
    ],
    },
    "oblib_restore_runtime": {
        "hdrs": [
        "lib/restore/ob_device_common.h",
    ],
        "deps": [
        ":oblib_core_utilities",
        ":oblib_foundation_base",
    ],
    },
    "oblib_rpc": {
        "hdrs": [
        "rpc/frame/ob_req_deliver.h",
        "rpc/frame/ob_req_processor.h",
        "rpc/frame/ob_req_queue_thread.h",
        "rpc/frame/ob_sql_processor.h",
        "rpc/ob_lock_wait_node.h",
        "rpc/ob_packet.h",
        "rpc/ob_request.h",
        "rpc/ob_sql_request_operator.h",
    ],
        "deps": [
        ":oblib_collections_runtime_base",
        ":oblib_concurrency_runtime_base",
        ":oblib_concurrency_support",
        ":oblib_core_utilities",
        ":oblib_diagnostics_runtime",
        ":oblib_foundation",
        ":oblib_foundation_base",
        ":oblib_foundation_support",
        ":oblib_io_primitives",
        ":oblib_io_runtime",
        ":oblib_rpc_transport_base",
        ":oblib_rpc_transport_primitives",
        ":oblib_rpc_transport_support",
        ":oblib_rpc_transport_utilities",
    ],
    },
    "oblib_rpc_transport_base": {
        "hdrs": [
        "rpc/frame/ob_req_qhandler.h",
    ],
        "deps": [
        ":oblib_rpc_transport_primitives",
    ],
    },
    "oblib_rpc_transport_primitives": {
        "hdrs": [
        "rpc/frame/obi_req_qhandler.h",
    ],
        "deps": [],
    },
    "oblib_rpc_transport_services": {
        "hdrs": [
        "rpc/frame/ob_result_code.h",
    ],
        "deps": [
        ":oblib_core_utilities",
        ":oblib_diagnostics_services",
        ":oblib_foundation_base",
        ":oblib_foundation_services",
        ":oblib_foundation_support",
    ],
    },
    "oblib_rpc_transport_support": {
        "hdrs": [
        "rpc/ob_reusable_mem.h",
    ],
        "deps": [
        ":oblib_foundation_base",
    ],
    },
    "oblib_rpc_transport_utilities": {
        "hdrs": [
        "rpc/frame/ob_req_translator.h",
        "rpc/ob_sql_mem_pool.h",
    ],
        "deps": [
        ":oblib_memory_utilities",
    ],
    },
    "oblib_vector": {
        "hdrs": [
        "lib/vector/ob_vector_util.h",
    ],
        "deps": [
        ":oblib_memory_utilities",
        ":oblib_vector_primitives",
        "@seekdb_3rd_headers//:vsag_headers",
    ],
    },
    "oblib_vector_primitives": {
        "hdrs": [
        "lib/vector/ob_vsag_adaptor.h",
    ],
        "deps": [],
    },
}

OBLIB_HEADER_TARGET_FOR_HEADER = {
    "common/cell/ob_cell_writer.h": ":oblib_db_values_services",
    "common/datum/ob_datum.h": ":oblib_db_values_model",
    "common/enumset/ob_enum_set_meta.h": ":oblib_db_values_model",
    "common/expression/ob_expr_string_buf.h": ":oblib_db_meta_domain",
    "common/json_type/ob_json_base.h": ":oblib_data_formats_model",
    "common/json_type/ob_json_bin.h": ":oblib_data_formats_model",
    "common/json_type/ob_json_common.h": ":oblib_data_formats_services",
    "common/json_type/ob_json_diff.h": ":oblib_data_formats_model",
    "common/json_type/ob_json_parse.h": ":oblib_data_formats_domain",
    "common/json_type/ob_json_path.h": ":oblib_data_formats_integration",
    "common/json_type/ob_json_schema.h": ":oblib_data_formats_domain",
    "common/json_type/ob_json_tree.h": ":oblib_data_formats_model",
    "common/lob/ob_lob_base.h": ":oblib_db_values_services",
    "common/log/ob_log_constants.h": ":oblib_db_log_primitives",
    "common/log/ob_log_cursor.h": ":oblib_db_log_advanced",
    "common/log/ob_log_data_writer.h": ":oblib_db_log_advanced",
    "common/log/ob_log_entry.h": ":oblib_db_log_advanced",
    "common/log/ob_log_generator.h": ":oblib_db_log_advanced",
    "common/meta_programming/ob_meta_compare.h": ":oblib_db_meta_runtime",
    "common/meta_programming/ob_meta_copy.h": ":oblib_db_meta_runtime",
    "common/meta_programming/ob_meta_define.h": ":oblib_db_meta_support",
    "common/meta_programming/ob_meta_serialization.h": ":oblib_db_meta_runtime",
    "common/meta_programming/ob_meta_swap.h": ":oblib_db_meta_runtime",
    "common/meta_programming/ob_mover.h": ":oblib_db_meta_runtime",
    "common/meta_programming/ob_type_traits.h": ":oblib_db_meta_runtime",
    "common/mysqlclient/ob_isql_client.h": ":oblib_mysql_client_runtime",
    "common/mysqlclient/ob_isql_connection.h": ":oblib_mysql_client_model",
    "common/mysqlclient/ob_isql_result_handler.h": ":oblib_mysql_client_primitives",
    "common/mysqlclient/ob_mysql_global.h": ":oblib_mysql_client_runtime",
    "common/mysqlclient/ob_mysql_proxy.h": ":oblib_mysql_client_domain",
    "common/mysqlclient/ob_mysql_result.h": ":oblib_mysql_client_model",
    "common/mysqlclient/ob_mysql_transaction.h": ":oblib_mysql_client_services",
    "common/mysqlclient/ob_single_connection_proxy.h": ":oblib_mysql_client_runtime",
    "common/number/ob_number_v2.h": ":oblib_db_values_services",
    "common/ob_accuracy.h": ":oblib_db_values_runtime",
    "common/ob_action_flag.h": ":oblib_db_values_primitives",
    "common/ob_common_types.h": ":oblib_db_values_runtime",
    "common/ob_data_version_mgr.h": ":oblib_db_values_runtime",
    "common/ob_field.h": ":oblib_db_values_model",
    "common/ob_hex_utils_base.h": ":oblib_db_values_support",
    "common/ob_range.h": ":oblib_common",
    "common/ob_record_header.h": ":oblib_db_values_advanced",
    "common/ob_role.h": ":oblib_db_values_primitives",
    "common/ob_role_mgr.h": ":oblib_db_values_base",
    "common/ob_simple_iterator.h": ":oblib_db_values_integration",
    "common/ob_store_format.h": ":oblib_db_values_runtime",
    "common/ob_store_range.h": ":oblib_common",
    "common/ob_string_buf.h": ":oblib_common",
    "common/ob_string_buf.ipp": ":oblib_db_values_model",
    "common/ob_tablet_id.h": ":oblib_db_values_services",
    "common/ob_timeout_ctx.h": ":oblib_db_values_runtime",
    "common/ob_version_def.h": ":oblib_db_values_runtime",
    "common/ob_zerofill_info.h": ":oblib_db_values_runtime",
    "common/object/ob_obj_compare.h": ":oblib_db_values_model",
    "common/object/ob_obj_funcs.h": ":oblib_common",
    "common/object/ob_obj_type.h": ":oblib_db_values_runtime",
    "common/object/ob_object.h": ":oblib_db_values_model",
    "common/row/ob_row.h": ":oblib_common",
    "common/row/ob_row_desc.h": ":oblib_db_values_integration",
    "common/row/ob_row_iterator.h": ":oblib_common",
    "common/row/ob_row_store.h": ":oblib_common",
    "common/row/ob_row_util.h": ":oblib_common",
    "common/rowkey/ob_rowkey.h": ":oblib_db_values_model",
    "common/rowkey/ob_rowkey_info.h": ":oblib_db_values_model",
    "common/rowkey/ob_store_rowkey.h": ":oblib_common",
    "common/sql_mode/ob_sql_mode.h": ":common_sql_mode",
    "common/sql_mode/ob_sql_mode_utils.h": ":oblib_db_values_model",
    "common/storage/ob_freeze_define.h": ":oblib_common",
    "common/storage/ob_sequence.h": ":oblib_db_values_advanced",
    "common/timezone/ob_time_convert.h": ":oblib_db_values_runtime",
    "common/timezone/ob_time_def.h": ":oblib_db_values_runtime",
    "common/timezone/ob_timezone_info.h": ":oblib_db_values_model",
    "common/udt/ob_array_binary.h": ":oblib_data_formats_domain",
    "common/udt/ob_array_fixed_size.h": ":oblib_data_formats_domain",
    "common/udt/ob_array_fixed_size.ipp": ":oblib_data_formats_domain",
    "common/udt/ob_array_nested.h": ":oblib_data_formats_domain",
    "common/udt/ob_array_type.h": ":oblib_data_formats_domain",
    "common/udt/ob_array_utils.h": ":oblib_data_formats_domain",
    "common/udt/ob_collection_type.h": ":oblib_data_formats_domain",
    "common/udt/ob_map_type.h": ":oblib_data_formats_domain",
    "common/udt/ob_udt_type.h": ":oblib_data_formats_domain",
    "common/udt/ob_vector_type.h": ":oblib_data_formats_domain",
    "common/wide_integer/ob_wide_integer.h": ":oblib_db_values_services",
    "common/wide_integer/ob_wide_integer_cmp_funcs.h": ":oblib_db_values_primitives",
    "common/wide_integer/ob_wide_integer_helper.h": ":oblib_db_values_primitives",
    "common/wide_integer/ob_wide_integer_impl.h": ":oblib_db_values_primitives",
    "common/wide_integer/ob_wide_integer_str_funcs.h": ":oblib_db_values_primitives",
    "common/xml/ob_binary_aggregate.h": ":oblib_data_formats_domain",
    "common/xml/ob_libxml2_sax_handler.h": ":oblib_data_formats_integration",
    "common/xml/ob_mul_mode_reader.h": ":oblib_data_formats_integration",
    "common/xml/ob_multi_mode_bin.h": ":oblib_data_formats_integration",
    "common/xml/ob_multi_mode_interface.h": ":oblib_data_formats_integration",
    "common/xml/ob_tree_base.h": ":oblib_data_formats_integration",
    "common/xml/ob_xml_parser.h": ":oblib_data_formats_integration",
    "common/xml/ob_xml_tree.h": ":oblib_data_formats_integration",
    "common/xml/ob_xml_util.h": ":oblib_data_formats_domain",
    "common/xml/ob_xpath.h": ":oblib_data_formats_domain",
    "lib/alloc/abit_set.h": ":oblib_memory_base",
    "lib/alloc/alloc_failed_reason.h": ":oblib_memory_base",
    "lib/alloc/alloc_func.h": ":oblib_memory_primitives",
    "lib/alloc/alloc_interface.h": ":oblib_memory_support",
    "lib/alloc/alloc_struct.h": ":oblib_memory_base",
    "lib/alloc/block_set.h": ":oblib_memory_runtime_base",
    "lib/alloc/malloc_hook.h": ":oblib_memory_primitives",
    "lib/alloc/memory_dump.h": ":oblib_memory_services",
    "lib/alloc/ob_ctx_allocator.h": ":oblib_memory_utilities",
    "lib/alloc/ob_ctx_define.h": ":oblib_memory_base",
    "lib/alloc/ob_iallocator.h": ":oblib_memory_base",
    "lib/alloc/ob_malloc_allocator.h": ":oblib_memory_utilities",
    "lib/alloc/ob_malloc_callback.h": ":oblib_memory_base",
    "lib/alloc/ob_malloc_sample_struct.h": ":oblib_memory_services",
    "lib/alloc/object_mgr.h": ":oblib_memory_runtime_base",
    "lib/alloc/object_set.h": ":oblib_memory_runtime_base",
    "lib/allocator/ob_allocator.h": ":oblib_memory_base",
    "lib/allocator/ob_allocator_v2.h": ":oblib_memory_utilities",
    "lib/allocator/ob_block_alloc_mgr.h": ":oblib_memory_advanced",
    "lib/allocator/ob_concurrent_fifo_allocator.h": ":oblib_memory_model",
    "lib/allocator/ob_external_ref.h": ":oblib_memory_base",
    "lib/allocator/ob_fifo_allocator.h": ":oblib_memory_utilities",
    "lib/allocator/ob_fixed_size_block_allocator.h": ":oblib_memory_advanced",
    "lib/allocator/ob_hazard_ref.h": ":oblib_memory_base",
    "lib/allocator/ob_heavy_ref.h": ":oblib_memory_base",
    "lib/allocator/ob_jemalloc.h": ":oblib_memory_utilities",
    "lib/allocator/ob_lf_fifo_allocator.h": ":oblib_memory_model",
    "lib/allocator/ob_malloc.h": ":oblib_memory_utilities",
    "lib/allocator/ob_memory_sanity.h": ":oblib_memory_utilities",
    "lib/allocator/ob_page_manager.h": ":oblib_memory_utilities",
    "lib/allocator/ob_qsync.h": ":oblib_foundation_integration",
    "lib/allocator/ob_retire_station.h": ":oblib_memory_advanced",
    "lib/allocator/ob_safe_arena.h": ":oblib_memory_utilities",
    "lib/allocator/ob_slice_alloc.h": ":oblib_foundation_integration",
    "lib/allocator/ob_small_allocator.h": ":oblib_foundation_integration",
    "lib/allocator/ob_tc_malloc.h": ":oblib_memory_primitives",
    "lib/allocator/ob_vslice_alloc.h": ":oblib_foundation_integration",
    "lib/allocator/page_arena.h": ":oblib_memory_utilities",
    "lib/atomic/atomic128.h": ":oblib_foundation_base",
    "lib/atomic/ob_atomic.h": ":oblib_foundation_base",
    "lib/atomic/ob_atomic_reference.h": ":oblib_concurrency_primitives",
    "lib/charset/mb_wc.h": ":oblib_encoding_base",
    "lib/charset/ob_charset.h": ":oblib_encoding_runtime",
    "lib/charset/ob_charset_string_helper.h": ":oblib_encoding_runtime",
    "lib/charset/ob_config.h": ":oblib_encoding_primitives",
    "lib/charset/ob_ctype.h": ":oblib_encoding_base",
    "lib/charset/ob_dtoa.h": ":oblib_encoding_base",
    "lib/charset/ob_mysql_global.h": ":oblib_encoding_base",
    "lib/charset/ob_template_helper.h": ":oblib_encoding_primitives",
    "lib/checksum/ob_crc64.h": ":oblib_encoding_runtime",
    "lib/checksum/ob_parity_check.h": ":oblib_encoding_primitives",
    "lib/compress/none/ob_none_compressor.h": ":oblib_compression_support",
    "lib/compress/ob_compress_util.h": ":oblib_compression_support",
    "lib/compress/ob_compressor.h": ":oblib_compression_support",
    "lib/compress/ob_compressor_pool.h": ":oblib_compression",
    "lib/compress/zlib/ob_zlib_compressor.h": ":oblib_compression_support",
    "lib/compress/zstd_1_3_8/ob_zstd_compressor_1_3_8.h": ":oblib_compression_support",
    "lib/compress/zstd_1_3_8/ob_zstd_wrapper.h": ":oblib_compression_primitives",
    "lib/container/ob_2d_array.h": ":oblib_foundation_services",
    "lib/container/ob_array.h": ":oblib_foundation_services",
    "lib/container/ob_array_array.h": ":oblib_foundation_services",
    "lib/container/ob_array_helper.h": ":oblib_collections_runtime",
    "lib/container/ob_array_iterator.h": ":oblib_foundation_integration",
    "lib/container/ob_array_serialization.h": ":oblib_foundation_integration",
    "lib/container/ob_array_wrap.h": ":oblib_foundation_support",
    "lib/container/ob_bit_set.h": ":oblib_foundation_integration",
    "lib/container/ob_bitmap.h": ":oblib_collections_advanced",
    "lib/container/ob_concurrent_bitset.h": ":oblib_collections_runtime_base",
    "lib/container/ob_ext_ring_buffer.h": ":oblib_collections_model",
    "lib/container/ob_ext_ring_buffer_impl.h": ":oblib_collections_model",
    "lib/container/ob_fast_array.h": ":oblib_collections_advanced",
    "lib/container/ob_fixed_array.h": ":oblib_collections_advanced",
    "lib/container/ob_fixed_array_iterator.h": ":oblib_foundation_integration",
    "lib/container/ob_heap.h": ":oblib_foundation_services",
    "lib/container/ob_iarray.h": ":oblib_collections_runtime",
    "lib/container/ob_id_map.h": ":oblib_collections_advanced",
    "lib/container/ob_int_flags.h": ":oblib_collections_advanced",
    "lib/container/ob_loser_tree.h": ":oblib_collections_advanced",
    "lib/container/ob_raw_se_array.h": ":oblib_foundation_services",
    "lib/container/ob_rbtree.h": ":oblib_foundation_integration",
    "lib/container/ob_se_array.h": ":oblib_foundation_services",
    "lib/container/ob_se_array_iterator.h": ":oblib_foundation_services",
    "lib/container/ob_tuple.h": ":oblib_collections_runtime",
    "lib/container/ob_vector.h": ":oblib_collections_advanced",
    "lib/container/ob_vector.ipp": ":oblib_collections_advanced",
    "lib/core_local/ob_core_local_storage.h": ":oblib_foundation_integration",
    "lib/coro/co_var.h": ":oblib_concurrency_primitives",
    "lib/cpu/ob_cpu_topology.h": ":oblib_foundation_integration",
    "lib/encode/ob_base64_encode.h": ":oblib_encoding_primitives",
    "lib/encrypt/ob_encrypted_helper.h": ":oblib_encoding_support",
    "lib/file/file_directory_utils.h": ":oblib_io_primitives",
    "lib/file/ob_file.h": ":oblib_io_advanced",
    "lib/file/ob_fileinfo_manager.h": ":oblib_io_base",
    "lib/file/ob_string_util.h": ":oblib_io_primitives",
    "lib/function/ob_function.h": ":oblib_foundation_runtime",
    "lib/future/ob_future.h": ":oblib_foundation_runtime",
    "lib/geometry/ob_geo_wkb_define.h": ":oblib_foundation",
    "lib/guard/ob_light_shared_gaurd.h": ":oblib_concurrency_advanced",
    "lib/guard/ob_scope_guard.h": ":oblib_concurrency_primitives",
    "lib/guard/ob_shared_guard.h": ":oblib_foundation_runtime",
    "lib/guard/ob_unique_guard.h": ":oblib_foundation_runtime",
    "lib/guard/ob_weak_guard.h": ":oblib_foundation_runtime",
    "lib/hash/fnv_hash.h": ":oblib_collections_primitives",
    "lib/hash/mprotect.h": ":oblib_collections_primitives",
    "lib/hash/ob_array_hash_map.h": ":oblib_collections_advanced",
    "lib/hash/ob_array_index_hash_set.h": ":oblib_foundation_integration",
    "lib/hash/ob_build_in_hashmap.h": ":oblib_collections_advanced",
    "lib/hash/ob_cuckoo_hashmap.h": ":oblib_collections_advanced",
    "lib/hash/ob_darray.h": ":oblib_collections_runtime_base",
    "lib/hash/ob_dchash.h": ":oblib_foundation_integration",
    "lib/hash/ob_fixed_hash2.h": ":oblib_collections_runtime_base",
    "lib/hash/ob_hash.h": ":oblib_collections_runtime_base",
    "lib/hash/ob_hashmap.h": ":oblib_collections_advanced",
    "lib/hash/ob_hashset.h": ":oblib_collections_advanced",
    "lib/hash/ob_hashtable.h": ":oblib_collections_advanced",
    "lib/hash/ob_hashutils.h": ":oblib_collections_advanced",
    "lib/hash/ob_iteratable_hashmap.h": ":oblib_foundation_integration",
    "lib/hash/ob_iteratable_hashset.h": ":oblib_foundation_integration",
    "lib/hash/ob_linear_hash_map.h": ":oblib_collections_model",
    "lib/hash/ob_link_hashmap.h": ":oblib_collections_model",
    "lib/hash/ob_link_hashmap_deps.h": ":oblib_collections_model",
    "lib/hash/ob_placement_hashmap.h": ":oblib_foundation_integration",
    "lib/hash/ob_placement_hashset.h": ":oblib_foundation_integration",
    "lib/hash/ob_placement_hashutils.h": ":oblib_foundation_integration",
    "lib/hash/ob_pointer_hashmap.h": ":oblib_collections_advanced",
    "lib/hash/ob_ptr_array_map.h": ":oblib_collections_advanced",
    "lib/hash/ob_serialization.h": ":oblib_collections_advanced",
    "lib/hash_func/murmur_hash.h": ":oblib_collections_primitives",
    "lib/hash_func/ob_hash_func.h": ":oblib_collections_base",
    "lib/hash_func/wyhash.h": ":oblib_collections_primitives",
    "lib/hash_func/xxhash.h": ":oblib_collections_primitives",
    "lib/json/ob_json.h": ":oblib_encoding_advanced",
    "lib/json/ob_json_print_utils.h": ":oblib_encoding_advanced",
    "lib/json/ob_yson.h": ":oblib_encoding_runtime",
    "lib/json/ob_yson_encode.h": ":oblib_encoding_support",
    "lib/lds/ob_lds_assist.h": ":oblib_memory_base",
    "lib/lds/ob_lds_define.h": ":oblib_memory_primitives",
    "lib/list/ob_atomic_list.h": ":oblib_foundation_base",
    "lib/list/ob_dlink_node.h": ":oblib_foundation_base",
    "lib/list/ob_dlist.h": ":oblib_concurrency_support",
    "lib/list/ob_intrusive_list.h": ":oblib_foundation_base",
    "lib/list/ob_list.h": ":oblib_concurrency_advanced",
    "lib/list/ob_obj_store.h": ":oblib_foundation_services",
    "lib/literals/ob_literals.h": ":oblib_foundation_runtime",
    "lib/locale/ob_locale_type.h": ":oblib_foundation_support",
    "lib/lock/cond.h": ":oblib_concurrency_support",
    "lib/lock/mutex.h": ":oblib_foundation_base",
    "lib/lock/ob_bucket_lock.h": ":oblib_foundation_services",
    "lib/lock/ob_drw_lock.h": ":oblib_concurrency_advanced",
    "lib/lock/ob_futex.h": ":oblib_concurrency_support",
    "lib/lock/ob_latch.h": ":oblib_concurrency_support",
    "lib/lock/ob_lock.h": ":oblib_concurrency_primitives",
    "lib/lock/ob_lock_guard.h": ":oblib_concurrency_support",
    "lib/lock/ob_monitor.h": ":oblib_concurrency_support",
    "lib/lock/ob_mutex.h": ":oblib_concurrency_runtime_base",
    "lib/lock/ob_qsync_lock.h": ":oblib_foundation_integration",
    "lib/lock/ob_recursive_mutex.h": ":oblib_concurrency_runtime_base",
    "lib/lock/ob_rwlock.h": ":oblib_concurrency_primitives",
    "lib/lock/ob_scond.h": ":oblib_concurrency_support",
    "lib/lock/ob_small_spin_lock.h": ":oblib_foundation_base",
    "lib/lock/ob_spin_lock.h": ":oblib_concurrency_runtime_base",
    "lib/lock/ob_spin_rwlock.h": ":oblib_concurrency_runtime_base",
    "lib/lock/ob_tc_ref.h": ":oblib_foundation_integration",
    "lib/lock/ob_tc_rwlock.h": ":oblib_foundation_integration",
    "lib/lock/ob_thread_cond.h": ":oblib_concurrency_support",
    "lib/metrics/ob_counter.h": ":oblib_foundation_base",
    "lib/net/ob_addr.h": ":oblib_io_runtime",
    "lib/net/ob_net_util.h": ":oblib_io_runtime",
    "lib/net/ob_sql_tls_info.h": ":oblib_foundation",
    "lib/ob_abort.h": ":oblib_foundation_base",
    "lib/ob_check_macros.h": ":oblib_foundation_base",
    "lib/ob_date_unit_type.h": ":oblib_foundation",
    "lib/ob_define.h": ":oblib_foundation_base",
    "lib/ob_errno.h": ":oblib_foundation",
    "lib/ob_lib_config.h": ":oblib_foundation_base",
    "lib/ob_name_def.h": ":oblib_foundation",
    "lib/ob_name_id_def.h": ":oblib_foundation",
    "lib/ob_running_mode.h": ":oblib_foundation_base",
    "lib/objectpool/ob_cached_allocator.h": ":oblib_memory_services",
    "lib/objectpool/ob_concurrency_objpool.h": ":oblib_foundation_integration",
    "lib/objectpool/ob_global_factory.h": ":oblib_memory_utilities",
    "lib/objectpool/ob_pool.h": ":oblib_memory_utilities",
    "lib/objectpool/ob_pool.ipp": ":oblib_memory_base",
    "lib/objectpool/ob_pooled_allocator.h": ":oblib_memory_utilities",
    "lib/objectpool/ob_resource_pool.h": ":oblib_memory_advanced",
    "lib/objectpool/ob_tc_factory.h": ":oblib_memory_advanced",
    "lib/oblog/ob_async_log_struct.h": ":oblib_foundation_base",
    "lib/oblog/ob_base_log_writer.h": ":oblib_foundation_base",
    "lib/oblog/ob_easy_log.h": ":oblib_diagnostics_primitives",
    "lib/oblog/ob_log.h": ":oblib_foundation_base",
    "lib/oblog/ob_log_compressor.h": ":oblib_compression_integration",
    "lib/oblog/ob_log_dba_event.h": ":oblib_foundation_base",
    "lib/oblog/ob_log_level.h": ":oblib_diagnostics_primitives",
    "lib/oblog/ob_log_module.h": ":oblib_foundation_base",
    "lib/oblog/ob_log_print_kv.h": ":oblib_foundation_base",
    "lib/oblog/ob_log_time_fmt.h": ":oblib_diagnostics_primitives",
    "lib/oblog/ob_log_user_msg.h": ":oblib_foundation_base",
    "lib/oblog/ob_ringbuf_log_writer.h": ":oblib_foundation_base",
    "lib/oblog/ob_syslog_rate_limiter.h": ":oblib_foundation_base",
    "lib/oblog/ob_trace_log.h": ":oblib_diagnostics_runtime",
    "lib/oblog/ob_warning_buffer.h": ":oblib_diagnostics_services",
    "lib/profile/ob_trace_id.h": ":oblib_diagnostics_runtime",
    "lib/profile/ob_trace_id_adaptor.h": ":oblib_diagnostics_support",
    "lib/queue/ob_fixed_queue.h": ":oblib_concurrency_support",
    "lib/queue/ob_lighty_queue.h": ":oblib_concurrency_support",
    "lib/queue/ob_link.h": ":oblib_foundation_base",
    "lib/queue/ob_link_queue.h": ":oblib_foundation_base",
    "lib/queue/ob_priority_queue.h": ":oblib_concurrency_runtime_base",
    "lib/random/ob_mysql_random.h": ":oblib_foundation_base",
    "lib/random/ob_random.h": ":oblib_foundation_base",
    "lib/rc/context.h": ":oblib_foundation_services",
    "lib/rc/ob_rc.h": ":oblib_foundation_base",
    "lib/resource/achunk_mgr.h": ":oblib_memory_runtime_base",
    "lib/resource/ob_cache_washer.h": ":oblib_memory_base",
    "lib/resource/ob_resource_mgr.h": ":oblib_memory_runtime_base",
    "lib/restore/ob_device_common.h": ":oblib_restore_runtime",
    "lib/restore/ob_io_device.h": ":oblib_restore_advanced",
    "lib/runtime.h": ":oblib_foundation_base",
    "lib/signal/ob_signal_struct.h": ":oblib_diagnostics_support",
    "lib/signal/ob_signal_utils.h": ":oblib_diagnostics_support",
    "lib/stat/ob_di_tls.h": ":oblib_diagnostics_utilities",
    "lib/stat/ob_diagnose_info.h": ":oblib_diagnostics_runtime",
    "lib/stat/ob_diagnostic_info_guard.h": ":oblib_diagnostics_runtime",
    "lib/stat/ob_latch_define.h": ":oblib_foundation_base",
    "lib/stat/ob_stat_template.h": ":oblib_diagnostics_support",
    "lib/statistic_event/ob_stat_class.h": ":oblib_foundation_base",
    "lib/statistic_event/ob_stat_event.h": ":oblib_diagnostics_support",
    "lib/string/ob_fixed_length_string.h": ":oblib_foundation_support",
    "lib/string/ob_sql_string.h": ":oblib_collections_runtime",
    "lib/string/ob_string.h": ":oblib_foundation_support",
    "lib/string/ob_string_buffer.h": ":oblib_collections_runtime",
    "lib/string/ob_string_holder.h": ":oblib_collections_utilities",
    "lib/string/ob_strings.h": ":oblib_foundation_services",
    "lib/task/ob_timer.h": ":oblib_foundation_integration",
    "lib/task/ob_timer_monitor.h": ":oblib_foundation_integration",
    "lib/task/ob_timer_service.h": ":oblib_foundation_integration",
    "lib/thread/ob_adaptive_worker_pool.h": ":oblib_foundation_base",
    "lib/thread/ob_async_task_queue.h": ":oblib_concurrency_model",
    "lib/thread/ob_balance_filter.h": ":oblib_concurrency_advanced",
    "lib/thread/ob_dedup_queue.h": ":oblib_concurrency_model",
    "lib/thread/ob_dynamic_thread_pool.h": ":oblib_foundation_services",
    "lib/thread/ob_link_task.h": ":oblib_foundation_base",
    "lib/thread/ob_priority_scheduler.h": ":oblib_concurrency_primitives",
    "lib/thread/ob_queue_thread.h": ":oblib_concurrency_advanced",
    "lib/thread/ob_reentrant_thread.h": ":oblib_foundation_services",
    "lib/thread/ob_simple_thread_pool.h": ":oblib_foundation_integration",
    "lib/thread/ob_simple_thread_pool.ipp": ":oblib_foundation_integration",
    "lib/thread/ob_test_util.h": ":oblib_foundation_runtime",
    "lib/thread/ob_thread_lease.h": ":oblib_foundation_base",
    "lib/thread/ob_thread_name.h": ":oblib_concurrency_primitives",
    "lib/thread/protected_stack_allocator.h": ":oblib_concurrency_runtime_base",
    "lib/thread/thread.h": ":oblib_foundation_runtime",
    "lib/thread/thread_pool.h": ":oblib_foundation_runtime",
    "lib/thread/threads.h": ":oblib_foundation_runtime",
    "lib/thread_local/ob_tsi_factory.h": ":oblib_concurrency_utilities",
    "lib/thread_local/ob_tsi_utils.h": ":oblib_foundation_base",
    "lib/time/Time.h": ":oblib_foundation",
    "lib/time/ob_clock_generator.h": ":oblib_foundation_runtime",
    "lib/time/ob_cur_time.h": ":oblib_foundation_integration",
    "lib/time/ob_time_utility.h": ":oblib_foundation_support",
    "lib/time/ob_tsc_timestamp.h": ":oblib_foundation_base",
    "lib/trace/ob_seq_event_recorder.h": ":oblib_diagnostics_support",
    "lib/trace/ob_trace.h": ":oblib_diagnostics_advanced",
    "lib/trace/ob_trace_def.h": ":oblib_foundation_base",
    "lib/trace/ob_trace_event.h": ":oblib_diagnostics_runtime",
    "lib/utility/alloc_assist.h": ":oblib_foundation_base",
    "lib/utility/data_buffer.h": ":oblib_foundation_support",
    "lib/utility/ob_backtrace.h": ":oblib_foundation",
    "lib/utility/ob_bits_utils.h": ":oblib_foundation_base",
    "lib/utility/ob_common_utility.h": ":oblib_foundation_base",
    "lib/utility/ob_defer.h": ":oblib_foundation",
    "lib/utility/ob_edit_distance.h": ":oblib_foundation_services",
    "lib/utility/ob_fast_convert.h": ":oblib_foundation_base",
    "lib/utility/ob_hang_fatal_error.h": ":oblib_foundation_base",
    "lib/utility/ob_hyperloglog.h": ":oblib_foundation_services",
    "lib/utility/ob_macro_utils.h": ":oblib_foundation",
    "lib/utility/ob_mod_define.h": ":oblib_foundation_base",
    "lib/utility/ob_platform_utils.h": ":oblib_foundation",
    "lib/utility/ob_print_kv.h": ":oblib_foundation_base",
    "lib/utility/ob_print_utils.h": ":oblib_core_utilities",
    "lib/utility/ob_rate_limiter.h": ":oblib_foundation",
    "lib/utility/ob_serialization_helper.h": ":oblib_foundation_support",
    "lib/utility/ob_smart_call.h": ":oblib_core_advanced",
    "lib/utility/ob_smart_var.h": ":oblib_foundation_runtime",
    "lib/utility/ob_sort.h": ":oblib_core_advanced",
    "lib/utility/ob_target_specific.h": ":oblib_foundation_integration",
    "lib/utility/ob_template_utils.h": ":oblib_foundation",
    "lib/utility/ob_tracepoint.h": ":oblib_core_advanced",
    "lib/utility/ob_tracepoint_def.h": ":oblib_foundation",
    "lib/utility/ob_unify_serialize.h": ":oblib_foundation_support",
    "lib/utility/ob_utility.h": ":oblib_foundation",
    "lib/utility/serialization.h": ":oblib_foundation_support",
    "lib/utility/utility.h": ":oblib_core_advanced",
    "lib/vector/ob_vector_util.h": ":oblib_vector",
    "lib/vector/ob_vsag_adaptor.h": ":oblib_vector_primitives",
    "lib/wait_event/ob_inner_sql_wait_type.h": ":oblib_diagnostics_primitives",
    "lib/wait_event/ob_wait_class.h": ":oblib_foundation_base",
    "lib/wait_event/ob_wait_event.h": ":oblib_foundation_base",
    "lib/worker.h": ":oblib_foundation_services",
    "rpc/frame/ob_req_deliver.h": ":oblib_rpc",
    "rpc/frame/ob_req_processor.h": ":oblib_rpc",
    "rpc/frame/ob_req_qhandler.h": ":oblib_rpc_transport_base",
    "rpc/frame/ob_req_queue_thread.h": ":oblib_rpc",
    "rpc/frame/ob_req_translator.h": ":oblib_rpc_transport_utilities",
    "rpc/frame/ob_result_code.h": ":oblib_rpc_transport_services",
    "rpc/frame/ob_sql_processor.h": ":oblib_rpc",
    "rpc/frame/obi_req_qhandler.h": ":oblib_rpc_transport_primitives",
    "rpc/ob_lock_wait_node.h": ":oblib_rpc",
    "rpc/ob_packet.h": ":oblib_rpc",
    "rpc/ob_request.h": ":oblib_rpc",
    "rpc/ob_reusable_mem.h": ":oblib_rpc_transport_support",
    "rpc/ob_sql_mem_pool.h": ":oblib_rpc_transport_utilities",
    "rpc/ob_sql_request_operator.h": ":oblib_rpc",
    "rpc/obmysql/ob_i_cs_mem_pool.h": ":oblib_mysql_protocol_primitives",
    "rpc/obmysql/ob_i_sm_conn_callback.h": ":oblib_mysql_protocol_primitives",
    "rpc/obmysql/ob_login_info.h": ":oblib_mysql_protocol_services",
    "rpc/obmysql/ob_mysql_field.h": ":oblib_mysql_protocol_model",
    "rpc/obmysql/ob_mysql_packet.h": ":oblib_mysql_protocol_runtime",
    "rpc/obmysql/ob_mysql_row.h": ":oblib_mysql_protocol_model",
    "rpc/obmysql/ob_mysql_util.h": ":oblib_mysql_protocol_model",
    "rpc/obmysql/ob_sql_nio_server.h": ":oblib_mysql_protocol_advanced",
    "rpc/obmysql/ob_sql_sock_handler.h": ":oblib_mysql_protocol_advanced",
    "rpc/obmysql/ob_sql_sock_session.h": ":oblib_mysql_protocol_runtime",
    "rpc/obmysql/obsm_struct.h": ":oblib_mysql_protocol_runtime",
    "rpc/obmysql/packet/ompk_auth_switch.h": ":oblib_mysql_protocol_services",
    "rpc/obmysql/packet/ompk_eof.h": ":oblib_mysql_protocol_runtime",
    "rpc/obmysql/packet/ompk_error.h": ":oblib_mysql_protocol_runtime",
    "rpc/obmysql/packet/ompk_field.h": ":oblib_mysql_protocol_domain",
    "rpc/obmysql/packet/ompk_local_infile.h": ":oblib_mysql_protocol_runtime",
    "rpc/obmysql/packet/ompk_ok.h": ":oblib_mysql_protocol_services",
    "rpc/obmysql/packet/ompk_prepare.h": ":oblib_mysql_protocol_runtime",
    "rpc/obmysql/packet/ompk_resheader.h": ":oblib_mysql_protocol_runtime",
    "rpc/obmysql/packet/ompk_row.h": ":oblib_mysql_protocol_domain",
    "rpc/obmysql/packet/ompk_string.h": ":oblib_mysql_protocol_runtime",
}

OBLIB_PRIVATE_HEADERS = [
    "common/cell/ob_cell_reader.h",
    "common/log/ob_log_dir_scanner.h",
    "common/log/ob_log_reader.h",
    "common/log/ob_single_log_reader.h",
    "common/ob_file_common_header.h",
    "common/row/ob_row_checksum.h",
    "common/timezone/ob_time_format.h",
    "common/timezone/ob_timezone_util.h",
    "common/timezone/private.h",
    "common/timezone/tzfile.h",
    "common/xml/ob_path_parser.h",
    "lib/alloc/ob_context_allocator.h",
    "lib/allocator/ob_delay_free_allocator.h",
    "lib/allocator/ob_simple_fifo_alloc.h",
    "lib/charset/ob_byteorder.h",
    "lib/charset/ob_ctype_bin_tab.h",
    "lib/charset/ob_ctype_utf8_tab.h",
    "lib/charset/ob_uctype.h",
    "lib/checksum/ob_crc16.h",
    "lib/codec/ob_bp_helpers.h",
    "lib/codec/ob_bp_util.h",
    "lib/codec/ob_codecs.h",
    "lib/codec/ob_composite_codec.h",
    "lib/codec/ob_delta_zigzag_pfor.h",
    "lib/codec/ob_delta_zigzag_rle.h",
    "lib/codec/ob_double_delta_zigzag_pfor.h",
    "lib/codec/ob_double_delta_zigzag_rle.h",
    "lib/codec/ob_fast_bp_func.h",
    "lib/codec/ob_fast_delta.h",
    "lib/codec/ob_generated_scalar_bp_func.h",
    "lib/codec/ob_generated_unalign_simd_bp_func.h",
    "lib/codec/ob_simd_fixed_pfor.h",
    "lib/codec/ob_sse_to_neon.h",
    "lib/codec/ob_tiered_codec.h",
    "lib/codec/ob_universal_compression.h",
    "lib/codec/ob_xor_fixed_pfor.h",
    "lib/compress/zstd_1_3_8/zstd_src/bitstream.h",
    "lib/compress/zstd_1_3_8/zstd_src/compiler.h",
    "lib/compress/zstd_1_3_8/zstd_src/cpu.h",
    "lib/compress/zstd_1_3_8/zstd_src/debug.h",
    "lib/compress/zstd_1_3_8/zstd_src/error_private.h",
    "lib/compress/zstd_1_3_8/zstd_src/fse.h",
    "lib/compress/zstd_1_3_8/zstd_src/hist.h",
    "lib/compress/zstd_1_3_8/zstd_src/huf.h",
    "lib/compress/zstd_1_3_8/zstd_src/mem.h",
    "lib/compress/zstd_1_3_8/zstd_src/pool.h",
    "lib/compress/zstd_1_3_8/zstd_src/threading.h",
    "lib/compress/zstd_1_3_8/zstd_src/xxhash.h",
    "lib/compress/zstd_1_3_8/zstd_src/zstd.h",
    "lib/compress/zstd_1_3_8/zstd_src/zstd_compress_internal.h",
    "lib/compress/zstd_1_3_8/zstd_src/zstd_ddict.h",
    "lib/compress/zstd_1_3_8/zstd_src/zstd_decompress_block.h",
    "lib/compress/zstd_1_3_8/zstd_src/zstd_decompress_internal.h",
    "lib/compress/zstd_1_3_8/zstd_src/zstd_double_fast.h",
    "lib/compress/zstd_1_3_8/zstd_src/zstd_errors.h",
    "lib/compress/zstd_1_3_8/zstd_src/zstd_fast.h",
    "lib/compress/zstd_1_3_8/zstd_src/zstd_internal.h",
    "lib/compress/zstd_1_3_8/zstd_src/zstd_lazy.h",
    "lib/compress/zstd_1_3_8/zstd_src/zstd_ldm.h",
    "lib/compress/zstd_1_3_8/zstd_src/zstd_opt.h",
    "lib/compress/zstd_1_3_8/zstd_src/zstdmt_compress.h",
    "lib/container/ob_mask_set2.h",
    "lib/container/ob_paringheap.h",
    "lib/container/ob_ring_array.h",
    "lib/container/ob_ring_buffer.h",
    "lib/encode/ob_quoted_printable_encode.h",
    "lib/encode/ob_uuencode.h",
    "lib/file/config.h",
    "lib/hash/ob_multi_mod_ref_mgr.h",
    "lib/hash/ob_refered_map.h",
    "lib/lds/ob_lds_constructor.hpp",
    "lib/list/ob_link.h",
    "lib/lock/ob_bucket_qsync_lock.h",
    "lib/metrics/ob_accumulator.h",
    "lib/metrics/ob_ema_v2.h",
    "lib/oblog/ob_base_log_buffer.h",
    "lib/oblog/ob_log_module.ipp",
    "lib/queue/ob_co_seq_queue.h",
    "lib/queue/ob_ms_queue.h",
    "lib/signal/ob_libunwind.h",
    "lib/stat/ob_di_list.h",
    "lib/string/ob_sensitive_string.h",
    "lib/thread/ob_map_queue.h",
    "lib/thread/ob_map_queue_thread_pool.h",
    "lib/thread_local/thread_buffer.h",
    "rpc/frame/ob_rpc_checksum.h",
    "rpc/obmysql/ob_mysql_packet_storage.h",
    ]

OBLIB_ALL_HEADER_TARGETS = [
    ":common_sql_mode",
    ":oblib_collections_advanced",
    ":oblib_collections_base",
    ":oblib_collections_model",
    ":oblib_collections_primitives",
    ":oblib_collections_runtime",
    ":oblib_collections_runtime_base",
    ":oblib_collections_utilities",
    ":oblib_common",
    ":oblib_compression",
    ":oblib_compression_integration",
    ":oblib_compression_primitives",
    ":oblib_compression_support",
    ":oblib_concurrency_advanced",
    ":oblib_concurrency_model",
    ":oblib_concurrency_primitives",
    ":oblib_concurrency_runtime_base",
    ":oblib_concurrency_support",
    ":oblib_concurrency_utilities",
    ":oblib_core_advanced",
    ":oblib_core_utilities",
    ":oblib_data_formats_domain",
    ":oblib_data_formats_integration",
    ":oblib_data_formats_model",
    ":oblib_data_formats_services",
    ":oblib_db_log_advanced",
    ":oblib_db_log_primitives",
    ":oblib_db_meta_domain",
    ":oblib_db_meta_runtime",
    ":oblib_db_meta_support",
    ":oblib_db_values_advanced",
    ":oblib_db_values_base",
    ":oblib_db_values_integration",
    ":oblib_db_values_model",
    ":oblib_db_values_primitives",
    ":oblib_db_values_runtime",
    ":oblib_db_values_services",
    ":oblib_db_values_support",
    ":oblib_diagnostics_advanced",
    ":oblib_diagnostics_primitives",
    ":oblib_diagnostics_runtime",
    ":oblib_diagnostics_services",
    ":oblib_diagnostics_support",
    ":oblib_diagnostics_utilities",
    ":oblib_encoding_advanced",
    ":oblib_encoding_base",
    ":oblib_encoding_primitives",
    ":oblib_encoding_runtime",
    ":oblib_encoding_support",
    ":oblib_foundation",
    ":oblib_foundation_base",
    ":oblib_foundation_integration",
    ":oblib_foundation_runtime",
    ":oblib_foundation_services",
    ":oblib_foundation_support",
    ":oblib_io_advanced",
    ":oblib_io_base",
    ":oblib_io_primitives",
    ":oblib_io_runtime",
    ":oblib_memory_advanced",
    ":oblib_memory_base",
    ":oblib_memory_model",
    ":oblib_memory_primitives",
    ":oblib_memory_runtime_base",
    ":oblib_memory_services",
    ":oblib_memory_support",
    ":oblib_memory_utilities",
    ":oblib_mysql_client_domain",
    ":oblib_mysql_client_model",
    ":oblib_mysql_client_primitives",
    ":oblib_mysql_client_runtime",
    ":oblib_mysql_client_services",
    ":oblib_mysql_protocol_advanced",
    ":oblib_mysql_protocol_domain",
    ":oblib_mysql_protocol_model",
    ":oblib_mysql_protocol_primitives",
    ":oblib_mysql_protocol_runtime",
    ":oblib_mysql_protocol_services",
    ":oblib_restore_advanced",
    ":oblib_restore_runtime",
    ":oblib_rpc",
    ":oblib_rpc_transport_base",
    ":oblib_rpc_transport_primitives",
    ":oblib_rpc_transport_services",
    ":oblib_rpc_transport_support",
    ":oblib_rpc_transport_utilities",
    ":oblib_vector",
    ":oblib_vector_primitives",
]

OBLIB_ALL_THIRD_PARTY_HEADER_DEPS = [
    "@seekdb_3rd_headers//:curl_headers",
    "@seekdb_3rd_headers//:libaio_headers",
    "@seekdb_3rd_headers//:libxml2_headers",
    "@seekdb_3rd_headers//:mariadb_headers",
    "@seekdb_3rd_headers//:openssl_headers",
    "@seekdb_3rd_headers//:rapidjson_headers",
    "@seekdb_3rd_headers//:vsag_headers",
    "@seekdb_3rd_headers//:zlib_headers",
]
