/*
 * Copyright (c) 2025 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef OCEANBASE_COMMON_OB_DEBUG_SYNC_POINT_H_
#define OCEANBASE_COMMON_OB_DEBUG_SYNC_POINT_H_

#include "lib/utility/ob_macro_utils.h"

namespace oceanbase
{
namespace common
{
class ObString;

#define OB_DEBUG_SYNC_POINT_DEF(ACT)                               \
    ACT(INVALID_DEBUG_SYNC_POINT, = 0)                             \
    ACT(NOW,)                                                      \
    ACT(MAJOR_FREEZE_BEFORE_SYS_COORDINATE_COMMIT,)                \
    ACT(BEFORE_INNER_SQL_COMMIT,)                                  \
    ACT(BEFORE_ASYNC_PT_UPDATE_TASK_EXECUTE,)                      \
    ACT(AFTER_ASYNC_PT_UPDATE_TASK_EXECUTE,)                       \
    ACT(DAILY_MERGE_BEFORE_RESTORE_LEADER_POS,)                    \
    ACT(SWITCH_LEADER_BEFORE_SYS_COORDINATE_COMMIT,)               \
    ACT(BEFORE_TRY_FREEZE_PARTITION_TABLE,)                        \
    ACT(BEFORE_WRITE_CHECK_POINT,)                                 \
    ACT(BEFORE_COMMIT_CHECK_POINT,)                                \
    ACT(BEFORE_PARTITION_MERGE_COMMIT,)                            \
    ACT(BEFORE_SEND_UPDATE_INDEX_STATUS,)                          \
    ACT(BEFORE_CHECK_MAJOR_FREEZE_DONE,)                           \
    ACT(UPDATE_WITH_PARTITION_FLAG_DONE,)                          \
    ACT(MAJOR_FREEZE_AFTER_SYS_COMMIT,)                            \
    ACT(MAJOR_FREEZE_AFTER_ROOTSERVER_COMMIT,)                     \
    ACT(SWITCH_LEADER_AFTER_SYS_COMMIT,)                           \
    ACT(SWITCH_LEADER_AFTER_ROOTSERVER_COMMIT,)                    \
    ACT(AFTER_WRITE_MAJOR_FREEZE_COMMIT_LOG,)                      \
    ACT(BEFORE_AUTO_COORDINATE,)                                   \
    ACT(DELAY_PARTITION_SERVICE_FREEZE_LOG_TASK,)                  \
    ACT(MINOR_MERGE_TIMER_TASK,)                                   \
    ACT(MERGE_TASK_PROCESS,)                                       \
    ACT(MAJOR_MERGE_TASK_PROCESS,)                                 \
    ACT(MAJOR_MERGE_PREPARE_TASK_PROCESS,)                         \
    ACT(MINOR_MERGE_SCHEDULE,)                                     \
    ACT(DELAY_INDEX_WRITE,)                                        \
    ACT(BEFORE_MINOR_FREEZE_GET_BASE_STORAGE_INFO,)                \
    ACT(BEFORE_IS_IN_SYNC_SET,)                                    \
    ACT(BEFORE_BUILD_LOCAL_INDEX,)               \
    ACT(BEFORE_SWEEP_MACRO_BLOCK,) \
    ACT(BEFORE_REPORT_BUILD_INDEX,) \
    ACT(DELAY_SCHEDULE_MERGE,) \
    ACT(DELAY_WRITE_CHECKPOINT,) \
    ACT(BEFORE_DO_GLOBAL_MAJOR_FREEZE,) \
    ACT(MAJOR_MERGE_PREPARE,)    \
    ACT(BEFORE_STOP_RS,) \
    ACT(BEFORE_ANSWER_RS_STATUS, )\
    ACT(BEFORE_CHECK_ALL_PARTITION_MERGED, )\
    ACT(BEFORE_UPDATE_INDEX_STATUS, )\
    ACT(BEFORE_CHECK_FREEZING,)\
    ACT(AFTER_RELEASE_STORES,)\
    ACT(AFTER_SET_FREEZING,)\
    ACT(BEFORE_REPORT_SELF,)\
    ACT(BEFORE_START_RS,) \
    ACT(BEFORE_MAIN_SSTBALE_FINISH_TASK,)\
    ACT(BEFORE_INDEX_SSTBALE_FINISH_TASK,)\
    ACT(HANG_MERGE,)\
    ACT(BEFORE_BACKGROUND_WASH,) \
    ACT(HANG_HEART_BEAT_ON_RS,)\
    ACT(AFTER_BUILD_INDEX_FINISH,)\
    ACT(BEFORE_PARTITION_REPORT_CALLBACK,)\
    ACT(BEFORE_RECYCLE_INTERM_RESULT,)\
    ACT(BEFORE_UPDATE_INDEX_BUILD_VERSION,)\
    ACT(AFTER_GLOBAL_INDEX_GET_SNAPSHOT,)\
    ACT(BEFORE_CHECK_GLOBAL_UNIQUE_INDEX,)\
    ACT(BEFORE_COPY_GLOBAL_INDEX,)\
    ACT(BEFORE_LOCAL_INDEX_WAIT_TRANS_END,)\
    ACT(BEFORE_LOCAL_INDEX_WAIT_TRANS_END_MID,)\
    ACT(BEFORE_LOCAL_INDEX_WAIT_SNAPSHOT_READY,)\
    ACT(BEFORE_LOCAL_INDEX_WAIT_SNAPSHOT_READY_MID,)\
    ACT(BEFORE_LOCAL_INDEX_CHOOSE_BUILD_INDEX_REPLICA,)\
    ACT(BEFORE_LOCAL_INDEX_CHOOSE_BUILD_INDEX_REPLICA_MID,)\
    ACT(BEFORE_LOCAL_INDEX_WAIT_CHOOSE_OR_BUILD_INDEX_END,)\
    ACT(BEFORE_LOCAL_INDEX_WAIT_CHOOSE_OR_BUILD_INDEX_END_MID,)\
    ACT(BEFORE_LOCAL_INDEX_COPY_BUILD_INDEX_DATA,)\
    ACT(BEFORE_LOCAL_INDEX_COPY_BUILD_INDEX_DATA_MID,)\
    ACT(BEFORE_LOCAL_INDEX_UNIQUE_INDEX_CHECKING,)\
    ACT(BEFORE_LOCAL_INDEX_UNIQUE_INDEX_CHECKING_MID,)\
    ACT(BEFORE_LOCAL_INDEX_WAIT_REPORT_STATUS,)\
    ACT(BEFORE_LOCAL_INDEX_WAIT_REPORT_STATUS_MID,)\
    ACT(BEFORE_LOCAL_INDEX_END,)\
    ACT(BEFORE_LOCAL_INDEX_END_MID,)\
    ACT(DEFORE_OBS_CREATE_PARTITION,)\
    ACT(DEFORE_FETCH_LOGIC_ROW_SRC,)\
    ACT(BEFORE_GET_MAJOR_MGERGE_TABLES,)\
    ACT(BEFORE_GET_MINOR_MGERGE_TABLES,)\
    ACT(BEFORE_GET_MAJOR_MERGE_TABLE_IDS,)\
    ACT(BEFORE_GET_MINOR_MERGE_TABLE_IDS,)\
    ACT(DAILY_MERGE_SCHEDULER_IDLE,)\
    ACT(BLOCK_GARBAGE_COLLECTOR,)\
    ACT(BEFORE_CREATE_INDEX_TASK,)\
    ACT(BEFORE_MERGE_CHECK_TASK,)\
    ACT(BEFORE_BUILD_LOCAL_INDEX_SCAN,)\
    ACT(BEFORE_CREATE_TABLE_TRANS_COMMIT,) \
    ACT(BEFORE_RESTORE_PARTITIONS,)\
    ACT(BEFORE_BATCH_PROCESS_TASK,)\
    ACT(BEFORE_INSERT_ROWS,)\
    ACT(AFTER_INSERT_ROWS,)\
    ACT(AFTER_INSERT_ROW,)\
    ACT(AFTER_TABLE_SCAN,)\
    ACT(BEFORE_BUILD_LOCAL_INDEX_REFRESH_TABLES,)\
    ACT(BEFORE_BUILD_LOCAL_INDEX_REFRESH_TABLES_MID,)\
    ACT(BEFORE_SLOG_UPDATE_FLUSH_CURSOR,)\
    ACT(BEFORE_SCHEDULE_ALL_PARTITIONS,)\
    ACT(MERGE_PARTITION_TASK,)\
    ACT(TRUNCATE_PARTITION_TRANS,)\
    ACT(BEFORE_FOLLOWER_CLUSTER_SYNC_SCHEMA,)\
    ACT(BEFORE_UPDATE_STANBY_FREEZE_INFO,)\
    ACT(BEFORE_PROCESS_USER_SCHEMA,)\
    ACT(BEFORE_GEN_NEXT_SCHEMA_VERSION,)\
    ACT(BLOCK_CALC_WRS,)\
    ACT(BEFORE_UPDATE_CORE_TABLE,)\
    ACT(BEFORE_REPLAY_ADD_PARTITION_TO_PG_CLOG,)\
    ACT(BEFORE_UPDATE_GLOBAL_INDEX_STATUS,)\
    ACT(BEFORE_UPDATE_LOCAL_INDEX_STATUS,)\
    ACT(FINISH_ABORT_CREATE_INDEX,)\
    ACT(BEFORE_SWITCHOVER_FROM_PENDING_TO_PRIMARY,)\
    ACT(AFTER_WRITE_USER_TABLE_CUTDATA_CLOG,)\
    ACT(AFTER_WRITE_INNER_TABLE_CUTDATA_CLOG,)\
    ACT(INNER_TABLE_IN_CUTDATA_STATUS,)\
    ACT(USER_TABLE_IN_CUTDATA_STATUS,)\
    ACT(INNER_TABLE_CUTDATA_FINISH,)\
    ACT(USER_TABLE_CUTDATA_FINISH,)\
    ACT(BEFORE_SWITCHOVER_TO_PENDING,)\
    ACT(BEFORE_ADD_SWITCHOVER_TASK,)\
    ACT(BEFORE_WRITE_PARTITION_CHECK_POINT,)\
    ACT(BEFORE_UPDATE_FREEZE_SNAPSHOT_INFO,)\
    ACT(BEFORE_CREATE_PG_PARTITION,)\
    ACT(BEFORE_MERGE_FINISH,)\
    ACT(BEFORE_FREEZE_ASYNC_TASK,)\
    ACT(CREATE_TABLE_BEFORE_PUBLISH_SCHEMA,)\
    ACT(BEFORE_DAILY_MERGE_RUN,)\
    ACT(AFTER_ADD_SWITCHOVER_TASK,)\
    ACT(HUNG_SWITCH_TASK_QUEUE,)\
    ACT(FETCH_MACRO_BLOCK,)\
    ACT(BEFORE_WRITE_START_WORKING,)\
    ACT(BEFORE_SYNC_LOG_SUCCESS,)\
    ACT(BEFORE_DIST_COMMIT,)\
    ACT(BLOCK_FREEZE_INFO_UPDATE,)\
    ACT(BEFROE_DO_ROOT_BACKUP,)\
    ACT(FAILED_TO_PROCESS_TO_PRIMARY,)\
    ACT(BEFORE_STANDBY_LOG_SYNC_FETCH,)\
    ACT(AFTER_STANDBY_PROMOTION_BOUNDARY_RESOLVED,)\
    ACT(AFTER_STANDBY_PROMOTION_INTENT_PERSISTED,)\
    ACT(AFTER_STANDBY_PRIMARY_ROLE_COMMITTED,)\
    ACT(BEFORE_FIX_RUNTIME_SCHEMA_VERSION,)\
    ACT(BACKUP_INFO_PREPARE,)\
    ACT(PARTITION_BACKUP_TASK_BEFORE_ADD_TASK_IN_MGR,)\
    ACT(HANG_BEFORE_RESOLVER_FINISH,)\
    ACT(AFTER_GET_MERGE_LOG_ID,)\
    ACT(END_PROCESS_USER_SCHEMA,)\
    ACT(AFTER_FREEZE_BEFORE_MINI_MERGE,)\
    ACT(BEFORE_SEND_HB,)\
    ACT(HUNG_HEARTBEAT_CHECK,)\
    ACT(BLOCK_WEAK_READ_TIMESTAMP,)\
    ACT(REPLAY_REDO_LOG,)\
    ACT(BACKUP_DATA_SYS_CLEAN_STATUS_DOING,)\
    ACT(BACKUP_DELETE_STATUS_INIT,)\
    ACT(BACKUP_DELETE_STATUS_COMPLETED,)\
    ACT(BACKUP_DELETE_TASK_STATUS_DOING,)\
    ACT(BACKUP_DELETE_TASK_DEAL_FAILED,)\
    ACT(BACKUP_DELETE_LS_TASK_STATUS_DOING,)\
    ACT(SYNC_PG_AND_REPLAY_ENGINE_DEADLOCK,)\
    ACT(BACKUP_DATA_VALIDATE_STATUS_SCHEDULE,)\
    ACT(BACKUP_DATA_VALIDATE_STATUS_DOING,)\
    ACT(FAST_RECOVER_BEFORE_PREPROCESS,)\
    ACT(FAST_RECOVER_AFTER_PREPROCESS,)\
    ACT(FAST_RECOVER_BEFORE_PROCESS,)\
    ACT(FAST_RECOVER_MID_PROCESS1,)\
    ACT(FAST_RECOVER_MID_PROCESS2,)\
    ACT(FAST_RECOVER_MID_PROCESS3,)\
    ACT(FAST_RECOVER_MID_PROCESS4,)\
    ACT(FAST_RECOVER_AFTER_PROCESS,)\
    ACT(FAST_RECOVER_REPLAY_CLOG,)\
    ACT(ADD_TRIGGER_BEFORE_MAP,)\
    ACT(DEL_TRIGGER_BEFORE_MAP,)\
    ACT(DOING_MARK_AND_SWEEP,)\
    ACT(BEFORE_ALTER_TABLE_PARTITION,)\
    ACT(BEFORE_FINISH_SET_PROTECTION_MODE,)\
    ACT(BEFORE_STANDBY_HEARTBEAT,)\
    ACT(BEFORE_DO_MINOR_FREEZE,)\
    ACT(BEFORE_UPDATE_RESTORE_FLAG_RESTORE_LOG,)\
    ACT(SLOW_TXN_DURING_2PC_COMMIT_PHASE_FOR_PHYSICAL_BACKUP_1055,)\
    ACT(SYNC_REPORT,)\
    ACT(BEFORE_STANDBY_FINISH_REPLY_SNAPSHOT_SCHEMA,)\
    ACT(BEFORE_ALTER_TABLE_COLUMN,)\
    ACT(BEFORE_CHECK_BACKUP_TASK_DATA_AVAILABLE,)\
    ACT(BLOCK_CLOG_PRIMARY_RECONFIRM,)\
    ACT(DROP_COLUMN_NOT_STORED_IN_MINOR,)\
    ACT(DROP_COLUMN_NOT_STORED_IN_MAJOR,)\
    ACT(BEFORE_FORCE_DROP_SCHEMA,)\
    ACT(DDL_REDEFINITION_LOCK_TABLE,)\
    ACT(DDL_REDEFINITION_WAIT_TRANS_END,)\
    ACT(DDL_REDEFINITION_HOLD_SNAPSHOT,)\
    ACT(DDL_REDEFINITION_WRITE_BARRIER_LOG,)\
    ACT(BEFORE_DDL_TABLE_MERGE_TASK,)\
    ACT(BEFORE_LOB_META_TABELT_DDL_MERGE_TASK,)\
    ACT(TABLE_REDEFINITION_REPLICA_BUILD,)\
    ACT(TABLE_REDEFINITION_COPY_TABLE_INDEXES,)\
    ACT(TABLE_REDEFINITION_COPY_TABLE_FOREIGN_KEYS,)\
    ACT(TABLE_REDEFINITION_COPY_TABLE_CONSTRAINTS,)\
    ACT(TABLE_REDEFINITION_TAKE_EFFECT,)\
    ACT(TABLE_REDEFINITION_WRITE_BARRIER_LOG,)\
    ACT(TABLE_REDEFINITION_FAIL,)\
    ACT(TABLE_REDEFINITION_SUCCESS,)\
    ACT(COLUMN_REDEFINITION_LOCAL_BUILD,)\
    ACT(COLUMN_REDEFINITION_COPY_TABLE_INDEXES,)\
    ACT(COLUMN_REDEFINITION_COPY_TABLE_CONSTRAINTS,)\
    ACT(COLUMN_REDEFINITION_COPY_TABLE_FOREIGN_KEYS,)\
    ACT(COLUMN_REDEFINITION_TAKE_EFFECT,)\
    ACT(DDL_STATS_BEFORE_SYNC,)\
    ACT(GATHER_STATS_BEFORE_ESTIMATE_BLOCK,)\
    ACT(GATHER_STATS_AFTER_BATCH_WRITE,)\
    ACT(FORK_TABLE_PREPARE,)\
    ACT(FORK_TABLE_OBTAIN_SNAPSHOT,)\
    ACT(FORK_TABLE_WAIT_FREEZE_END,)\
    ACT(FORK_TABLE_BUILD_DATA,)\
    ACT(FORK_TABLE_WAIT_DATA_COMPLEMENT,)\
    ACT(FORK_TABLE_SUCCESS,)\
    ACT(CREATE_INDEX_WAIT_TRANS_END,)\
    ACT(CREATE_INDEX_REPLICA_BUILD,)\
    ACT(CREATE_INDEX_LOCAL_BUILD,)\
    ACT(CREATE_INDEX_VERIFY_CHECKSUM,)\
    ACT(CREATE_INDEX_TAKE_EFFECT,)\
    ACT(CREATE_INDEX_FAILED,)\
    ACT(CREATE_INDEX_SUCCESS,)\
    ACT(CONSTRAINT_WAIT_TRANS_END,)\
    ACT(CONSTRAINT_VALIDATE,)\
    ACT(CONSTRAINT_SET_VALID,)\
    ACT(CONSTRAINT_FAIL,)\
    ACT(CONSTRAINT_ROLLBACK_FAILED_CHECK_CONSTRAINT_BEFORE_ALTER_TABLE,)\
    ACT(CONSTRAINT_ROLLBACK_FAILED_FK_BEFORE_ALTER_TABLE,)\
    ACT(CONSTRAINT_BEFORE_SET_FK_VALIDATED_BEFORE_ALTER_TABLE,)\
    ACT(CONSTRAINT_BEFORE_SET_CHECK_CONSTRAINT_VALIDATED_BEFORE_ALTER_TABLE,)\
    ACT(CONSTRAINT_SUCCESS,)\
    ACT(BEFORE_PERSIST_LS_TASK,)\
    ACT(BEFORE_SEND_RESTORE_PARTITIONS_RPC,)\
    ACT(BEFORE_CREATE_USER_LS,)\
    ACT(BEFORE_BACKUP_META,)\
    ACT(BEFORE_BACKUP_DATA,)\
    ACT(BEFORE_BACKUP_PREPARE_TASK,)\
    ACT(BEFORE_BACKUP_MAJOR_SSTABLE,)\
    ACT(BEFORE_BACKUP_BUILD_INDEX,)\
    ACT(BEFORE_BACKUP_COMPLEMENT_LOG,)\
    ACT(BEFORE_BACKUP_FINISH,)\
    ACT(BEFORE_ADD_BACKUP_TASK_INTO_SCHEDULER,)\
    ACT(BEFORE_RELEASE_DDL_KV,)\
    ACT(BEFORE_DDL_LOB_META_TABLET_MDS_DUMP,)\
    ACT(BEFORE_DDL_CHECKPOINT,)\
    ACT(AFTER_DDL_WRITE_MACRO_BLOCK,)\
    ACT(BEFORE_REPLAY_DDL_MACRO_BLOCK,)\
    ACT(BEFORE_REPLAY_DDL_PREPRARE,)\
    ACT(BEFORE_REPLAY_DDL_COMMIT,)\
    ACT(BEFORE_BACKUP_UESR_META,)\
    ACT(BEFORE_BACKUP_META_FINISH,)\
    ACT(AFTER_BACKUP_META_FINISH,)\
    ACT(BEFORE_BACKUP_SYS_TABLETS,)\
    ACT(BEFORE_WRITE_DDL_PREPARE_LOG,)\
    ACT(BEFORE_INDEX_SSTABLE_BUILD_TASK_SEND_SQL,)\
    ACT(BEFORE_CHECK_FK_DATA_VALID_SEND_SQL,)\
    ACT(BEFORE_CHECK_CONSTRAINT_VALID_SEND_SQL,)\
    ACT(BEFORE_EXECUTE_CTAS_CLEAR_SESSION_ID,)\
    ACT(BEFORE_RESTORE_START,)\
    ACT(BEFORE_RESTORE_SYS_TABLETS,)\
    ACT(BEFORE_RESTORE_TABLETS_META,)\
    ACT(BEFORE_RESTORE_MINOR,)\
    ACT(SWITCHING_TO_STANDBY,)\
    ACT(BEFORE_RECOVER_USER_LS,)\
    ACT(BLOCK_STANDBY_REFRESH_SCHEMA,)\
    ACT(BEFORE_LS_RESTORE_SYS_TABLETS,)\
    ACT(BEFORE_WAIT_RESTORE_SYS_TABLETS,)\
    ACT(BEFORE_WAIT_RESTORE_TABLETS_META,)\
    ACT(BEFORE_WAIT_LS_RESTORE_TO_CONSISTENT_SCN,)\
    ACT(BEFORE_WAIT_MAJOR_RESTORE,)\
    ACT(SWAP_ORIG_AND_HIDDEN_TABLE_BEFORE_PUBLISH_SCHEMA,)\
    ACT(BEFORE_RESTORE_MAJOR,)\
    ACT(BEFORE_UPDATE_RECOVERY_UNTIL_SCN,)\
    ACT(WHILE_LEADER_RESTORE_GROUP_TABLET,)\
    ACT(BEFORE_LEADER_RESTORE_GROUP_TABLET,)\
    ACT(MERGE_PARTITION_FINISH_TASK,)\
    ACT(RS_VALIDATE_CHECKSUM,)\
    ACT(RS_CHECK_MERGE_PROGRESS,)\
    ACT(AFTER_SCHEDULE_RESTORE_MINOR_DAG_NET,)\
    ACT(BEFORE_BACKUP_TASK_FINISH,)\
    ACT(BEFORE_UPDATE_LS_META_TABLE,)\
    ACT(BEFORE_COPY_DDL_SSTABLE,)\
    ACT(BEFORE_DDL_WRITE_PREPARE_LOG,)\
    ACT(AFTER_BACKUP_FETCH_MACRO_BLOCK_FAILED,)\
    ACT(BEFORE_TABLE_REDEFINITION_TASK_EFFECT,)\
    ACT(BEFORE_LOCK_SERVICE_UNLOCK,)\
    ACT(DDL_CHECK_TABLET_MERGE_STATUS,)\
    ACT(BEFORE_LOCK_LS_WHEN_CREATE_TABLE,)\
    ACT(TABLE_LOCK_AFTER_LOCK_TABLE_BEFORE_LOCK_TABLET,)\
    ACT(MODIFY_HIDDEN_TABLE_NOT_NULL_COLUMN_STATE_BEFORE_PUBLISH_SCHEMA,)\
    ACT(AFTER_LOCK_LS_AND_BEFORE_CHANGE_LS_FLAG,)\
    ACT(BEFORE_WAIT_LOG_SYNC,)\
    ACT(BEFORE_WAIT_LOG_REPLAY_SYNC,)\
    ACT(BEFORE_FOREIGN_KEY_CONSTRAINT_CHECK,)\
    ACT(BEFORE_RESTORE_SERVICE_PUSH_FETCH_DATA,)\
    ACT(BEFORE_RESTORE_HANDLE_FETCH_LOG_TASK,)\
    ACT(AFTER_LS_GC_DELETE_ALL_TABLETS,)\
    ACT(AFTER_UPDATE_INDEX_STATUS,)\
    ACT(BEFORE_WAIT_RESTORE_TO_CONSISTENT_SCN,)\
    ACT(AFTER_WAIT_RESTORE_TO_CONSISTENT_SCN,)\
    ACT(BEFORE_BACKUP_1001_META,)\
    ACT(BEFORE_BACKUP_1002_META,)\
    ACT(BEFORE_BACKUP_CONSISTENT_SCN,)\
    ACT(AFTER_CHANGE_BACKUP_TURN_ID,)\
    ACT(AFTER_UPDATE_TABLET_TO_LS,)\
    ACT(BEFORE_BACKUP_MAJOR,)\
    ACT(BEFORE_TABLET_MDS_FLUSH,)\
    ACT(BEFORE_CHECKPOINT_TASK,)\
    ACT(AFTER_EMPTY_SHELL_TABLET_CREATE,)\
    ACT(AFTER_MACRO_BLOCK_WRITER_DDL_CALLBACK_WAIT,)\
    ACT(AFTER_RESTORE_TABLET_TASK,)\
    ACT(BEFORE_TABLET_GC,)\
    ACT(AFTER_CHECKPOINT_GET_CURSOR,)\
    ACT(BEFORE_CHANGE_BACKUP_TURN,)\
    ACT(BEFORE_UNIQ_TASK_RUN,)\
    ACT(BEFORE_PARELLEL_TRUNCATE,)\
    ACT(END_DDL_IN_PX_SUBCOORD,)\
    ACT(BETWEEN_INSERT_LOCK_INFO_AND_TRY_LOCK_CONFIG_CHANGE,)\
    ACT(STOP_RECOVERY_LS_THREAD0,)\
    ACT(STOP_RECOVERY_LS_THREAD1,)\
    ACT(AFTER_PARALLEL_DDL_LOCK_OBJ_BY_NAME,)\
    ACT(STOP_PRIMARY_LS_THREAD,)\
    ACT(AFTER_CHANGE_ACCESS_MODE,)\
    ACT(STOP_LS_RECOVERY_THREAD,)\
    ACT(BEFORE_PROCESS_EVENT_TASK,)\
    ACT(LS_GC_BEFORE_SUBMIT_OFFLINE_LOG,)\
    ACT(LS_GC_BEFORE_OFFLINE,)\
    ACT(AFTER_LOCK_SNAPSHOT_MUTEX,)\
    ACT(BEFORE_FETCH_SIMPLE_TABLES,)\
    ACT(BEFORE_SEND_PARALLEL_CREATE_TABLE,)\
    ACT(BEFORE_CALC_CONSISTENT_SCN,)\
    ACT(RENAME_TABLE_BEFORE_PUBLISH_SCHEMA,)\
    ACT(BEFORE_SET_NEW_SCHEMA_VERSION,)\
    ACT(REPLAY_SWITCH_TO_FOLLOWER_BEFORE_PUSH_SUBMIT_TASK,)\
    ACT(BEFORE_MERGE_BACKUP_META_INFO,)\
    ACT(HANG_IN_CLONE_SYS_LOCK,)\
    ACT(HANG_IN_CLONE_SYS_CREATE_SNAPSHOT,)\
    ACT(HANG_IN_CLONE_SYS_WAIT_CREATE_SNAPSHOT,)\
    ACT(HANG_IN_CLONE_SYS_RELEASE_RESOURCE,)\
    ACT(HANG_IN_CLONE_SYS_SUCCESS,)\
    ACT(HANG_IN_CLONE_SYS_FAILED_STATUS,)\
    ACT(BEFORE_BACKUP_PREFETCH_TASK,)\
    ACT(BEFORE_BACKUP_DATA_TASK,)\
    ACT(BEFORE_CHECK_NEED_TABLET_GC,)\
    ACT(BEFORE_TABLET_FULL_DIRECT_LOAD_MGR_CLOSE,)\
    ACT(BEFORE_CHECK_TABLET_READY,)\
    ACT(BEFORE_LOG_REPLAY_TO_MAX_MINOR_END_SCN,)\
    ACT(HOLD_DDL_COMPLEMENT_DAG_WHEN_APPEND_ROW,)\
    ACT(HOLD_DDL_COMPLEMENT_DAG_BEFORE_REPORT_FINISH,)\
    ACT(HOLD_DDL_COMPLEMENT_DAG_AFTER_REPORT_FINISH,)\
    ACT(BEFORE_ALTER_TABLE_EXCHANGE_PARTITION,)\
    ACT(AFTER_REPORT_BACKUP_COMPL_LOG,)\
    ACT(BEFORE_WRITE_TABLE_LIST_META_INFO,)\
    ACT(BEFORE_ADD_REFRESH_SCHEMA_TASK,)\
    ACT(BEFORE_ADD_ASYNC_REFRESH_SCHEMA_TASK,)\
    ACT(AFTER_FIRST_CLONE_CHECK_FOR_STANDBY,)\
    ACT(REBUILD_VEC_INDEX_PREPARE,)\
    ACT(REBUILD_VEC_INDEX_WAIT_CREATE_NEW_INDEX,)\
    ACT(REBUILD_VEC_INDEX_WAIT_DROP_OLD_INDEX,)\
    ACT(REBUILD_VEC_INDEX_SWITCH_INDEX_NAME,)\
    ACT(BUILD_VECTOR_INDEX_PREPARE_STATUS,)\
    ACT(BUILD_VECTOR_INDEX_SUBMIT_DROP_TASK,)\
    ACT(BUILD_VECTOR_INDEX_PREPARE_ROWKEY_VID,)\
    ACT(BUILD_VECTOR_INDEX_PREPARE_AUX_INDEX,)\
    ACT(BUILD_VECTOR_INDEX_PREPARE_VID_ROWKEY,)\
    ACT(DROP_VECTOR_INDEX_PREPARE_STATUS,)\
    ACT(DROP_VECTOR_INDEX_BEFORE_DELETE_LOB_META,)\
    ACT(DROP_VECTOR_INDEX_AFTER_DELETE_LOB_META,)\
    ACT(HANDLE_VECTOR_INDEX_ASYNC_TASK,)\
    ACT(CS_ASYNC_VECTOR_INDEX_BEFORE_APPLY,)\
    ACT(CS_FETCHER_AFTER_DDL_MDS_LOG,)\
    ACT(CS_FETCHER_AFTER_DML_REDO_LOG,)\
    ACT(CREATE_AUX_INDEX_TABLE,)\
    ACT(BEFORE_SEND_ALTER_TABLE,)\
    ACT(BEFORE_CREATE_HIDDEN_TABLE_IN_LOAD,)\
    ACT(BEFORE_PARALLEL_DDL_LOCK,)\
    ACT(AFTER_PARALLEL_DDL_LOCK,)\
    ACT(BEFORE_RESTORE_CREATE_TABLETS_SSTABLE,)\
    ACT(BEFORE_CLOSE_BACKUP_INDEX_BUILDER,)\
    ACT(BEFROE_UPDATE_DATA_VERSION,)\
    ACT(BEFORE_DBMS_VECTOR_REFRESH,)\
    ACT(BEFORE_DBMS_VECTOR_REBUILD,)\
    ACT(BEFROE_UPDATE_MIG_TABLET_CONVERT_CO_PROGRESSING,)\
    ACT(AFTER_SET_CO_CONVERT_RETRY_EXHUASTED,)\
    ACT(BEFORE_PREFETCH_BACKUP_INFO_TASK,)\
    ACT(RS_CHANGE_TURN_DEBUG_SYNC,)\
    ACT(BEFORE_PARALLEL_BUILD_TABLET_INFO_TABLET,)\
    ACT(BUILD_FTS_INDEX_PREPARE_STATUS,)\
    ACT(DROP_FTS_INDEX_PREPARE_STATUS,)\
    ACT(CREATE_TFS_INDEX_ROWKEY_DOC_STATUS,)\
    ACT(BEFOR_PREPARE_CREATE_TFS_INDEX_DOC_ROWKEY,)\
    ACT(BEFOR_PREPARE_CREATE_TFS_INDEX_WORD_DOC,)\
    ACT(BEFOR_PREPARE_CREATE_TFS_INDEX_DOC_WORD,)\
    ACT(BEFOR_EXECUTE_CREATE_TABLE_WITH_FTS_INDEX,)\
    ACT(BEFORE_LOAD_DICTIONARY_IN_BACKGROUND,)\
    ACT(BEFORE_EXECUTE_ADMIN_SET_CONFIG,)\
    ACT(BEFORE_REFRESH_SCHEMA,)\
    ACT(BEFORE_DROP_INDEX,)\
    ACT(AFTER_IVF_CENTROID_TABLE,)\
    ACT(AFTER_PQ_CENTROID_TABLE,)\
    ACT(AFTER_SQ_META_TABLE,)\
    ACT(BEFORE_RENAME_INDEX,)\
    ACT(AFTER_DROP_FTS_SUBMIT_SUBTASK,)\
    ACT(BEFORE_GET_BACKUP_END_SCN,)\
    ACT(BEFORE_SWAP_ORIG_AND_HIDDEN_TABLE_STATE,)\
    ACT(BEFORE_ALTER_TABLE_IN_TRANS,)\
    ACT(REBUILD_INDEX_WAIT_CREATE_TASK_FINISH,)\
    ACT(REBUILD_INDEX_WAIT_DROP_TASK_FINISH,)\
    ACT(LOAD_INNER_TABLE_SCHEMA,)\
    ACT(CANCEL_VEC_TASK_ADD_SNAP_INDEX,)\
    ACT(BEFORE_RESTORE_PRE,)\
    ACT(AFTER_UPDATE_TABLET_RESTORE_STATUS,)\
    ACT(BEFORE_INC_MAJOR_DDL_MERGE_UPDATE_TABLE_STORE,)\
    ACT(AFTER_INC_MAJOR_MERGE_GET_SSTABLE,)\
    ACT(CREATE_INDEX_ON_EMPTY_TABLE,)\
    ACT(DAS_GRAPH_EXPAND_AFTER_EDGE_ROW,)\
    ACT(DAS_GRAPH_EXPAND_AFTER_ERROR_CLEANUP,)\
    ACT(MAX_DEBUG_SYNC_POINT,)

DECLARE_ENUM(ObDebugSyncPoint, debug_sync_point, OB_DEBUG_SYNC_POINT_DEF);

} // end namespace common
} // end namespace oceanbase

#endif // OCEANBASE_COMMON_OB_DEBUG_SYNC_POINT_H_
