"""Generated source inventory for SQL."""

SQL_UNITY_GROUPS = [
    struct(
        name = "ob_sql_code_generator_0",
        language = "c++",
        srcs = [
            "src/sql/code_generator/ob_code_generator.cpp",
            "src/sql/code_generator/ob_column_index_provider.cpp",
            "src/sql/code_generator/ob_dml_cg_service.cpp",
            "src/sql/code_generator/ob_expr_generator_impl.cpp",
            "src/sql/code_generator/ob_static_engine_cg.cpp",
            "src/sql/code_generator/ob_static_engine_expr_cg.cpp",
            "src/sql/code_generator/ob_tsc_cg_service.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_common_0",
        language = "c++",
        srcs = [
            "src/sql/ob_end_trans_callback.cpp",
            "src/sql/ob_end_trans_cb_packet_param.cpp",
            "src/sql/ob_phy_table_location.cpp",
            "src/sql/ob_query_retry_ctrl.cpp",
            "src/sql/ob_result_set.cpp",
            "src/sql/ob_scanner.cpp",
            "src/sql/ob_spi.cpp",
            "src/sql/ob_sql.cpp",
            "src/sql/ob_sql_context.cpp",
            "src/sql/ob_sql_define.cpp",
            "src/sql/ob_sql_task.cpp",
            "src/sql/ob_sql_temp_table.cpp",
            "src/sql/ob_sql_trans_control.cpp",
            "src/sql/ob_sql_utils.cpp",
            "src/sql/ob_optimizer_trace_impl.cpp",
            "src/sql/pl/ob_routine_param_type.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_common_mixed_0",
        language = "c++",
        srcs = [
            "src/sql/privilege_check/ob_privilege_check.cpp",
            "src/sql/privilege_check/ob_ai_model_priv_util.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_das_0",
        language = "c++",
        srcs = [
            "src/sql/das/ob_domain_id.cpp",
            "src/sql/das/ob_das_context.cpp",
            "src/sql/das/ob_das_define.cpp",
            "src/sql/das/ob_das_delete_op.cpp",
            "src/sql/das/ob_das_dml_ctx_define.cpp",
            "src/sql/das/ob_das_factory.cpp",
            "src/sql/das/ob_das_insert_op.cpp",
            "src/sql/das/ob_das_lock_op.cpp",
            "src/sql/das/ob_das_ref.cpp",
            "src/sql/das/ob_das_scan_op.cpp",
            "src/sql/das/ob_das_task.cpp",
            "src/sql/das/ob_das_update_op.cpp",
            "src/sql/das/ob_data_access_service.cpp",
            "src/sql/das/ob_das_utils.cpp",
            "src/sql/das/ob_das_ir_define.cpp",
            "src/sql/das/ob_das_vec_define.cpp",
            "src/sql/das/ob_das_retry_ctrl.cpp",
            "src/sql/das/ob_das_simple_op.cpp",
            "src/sql/das/ob_das_domain_utils.cpp",
            "src/sql/das/ob_das_attach_define.cpp",
            "src/sql/das/ob_das_dml_vec_iter.cpp",
            "src/sql/das/ob_das_parallel_handler.cpp",
            "src/sql/das/iter/ob_das_iter.cpp",
            "src/sql/das/iter/ob_das_merge_iter.cpp",
            "src/sql/das/ob_das_id_allocator.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_das_1",
        language = "c++",
        srcs = [
            "src/sql/das/iter/ob_das_lookup_iter.cpp",
            "src/sql/das/iter/ob_das_group_fold_iter.cpp",
            "src/sql/das/iter/ob_das_scan_iter.cpp",
            "src/sql/das/iter/ob_das_local_lookup_iter.cpp",
            "src/sql/das/iter/ob_das_global_lookup_iter.cpp",
            "src/sql/das/iter/ob_das_sort_iter.cpp",
            "src/sql/das/iter/ob_das_text_retrieval_iter.cpp",
            "src/sql/das/iter/ob_das_text_retrieval_merge_iter.cpp",
            "src/sql/das/iter/ob_das_text_retrieval_eval_node.cpp",
            "src/sql/das/iter/ob_das_iter_utils.cpp",
            "src/sql/das/iter/ob_das_index_merge_iter.cpp",
            "src/sql/das/iter/ob_das_func_data_iter.cpp",
            "src/sql/das/iter/ob_das_functional_lookup_iter.cpp",
            "src/sql/das/iter/ob_das_cache_lookup_iter.cpp",
            "src/sql/das/iter/ob_das_mvi_lookup_iter.cpp",
            "src/sql/das/iter/ob_das_spatial_scan_iter.cpp",
            "src/sql/das/iter/ob_das_hnsw_scan_iter.cpp",
            "src/sql/das/iter/ob_das_ivf_scan_iter.cpp",
            "src/sql/das/iter/ob_das_spiv_merge_iter.cpp",
            "src/sql/das/iter/ob_das_spiv_scan_iter.cpp",
            "src/sql/das/iter/ob_das_domain_id_merge_iter.cpp",
            "src/sql/das/iter/ob_das_vec_scan_utils.cpp",
            "src/sql/das/iter/sparse_retrieval/ob_das_tr_merge_iter.cpp",
            "src/sql/das/iter/sparse_retrieval/ob_das_match_iter.cpp",
            "src/sql/das/ob_das_tablet_mapper.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_dtl_0",
        language = "c++",
        srcs = [
            "src/sql/dtl/ob_dtl.cpp",
            "src/sql/dtl/ob_dtl_basic_channel.cpp",
            "src/sql/dtl/ob_dtl_buf_allocator.cpp",
            "src/sql/dtl/ob_dtl_channel.cpp",
            "src/sql/dtl/ob_dtl_channel_agent.cpp",
            "src/sql/dtl/ob_dtl_channel_group.cpp",
            "src/sql/dtl/ob_dtl_channel_loop.cpp",
            "src/sql/dtl/ob_dtl_channel_mem_manager.cpp",
            "src/sql/dtl/ob_dtl_fc_server.cpp",
            "src/sql/dtl/ob_dtl_flow_control.cpp",
            "src/sql/dtl/ob_dtl_interm_result_manager.cpp",
            "src/sql/dtl/ob_dtl_linked_buffer.cpp",
            "src/sql/dtl/ob_dtl_local_channel.cpp",
            "src/sql/dtl/ob_dtl_local_first_buffer_manager.cpp",
            "src/sql/dtl/ob_dtl_task.cpp",
            "src/sql/dtl/ob_dtl_utils.cpp",
            "src/sql/dtl/ob_op_metric.cpp",
            "src/sql/dtl/ob_dtl_mem_manager.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_0",
        language = "c++",
        srcs = [
            "src/sql/engine/ob_des_exec_context.cpp",
            "src/sql/engine/ob_exec_context.cpp",
            "src/sql/engine/ob_exec_feedback_info.cpp",
            "src/sql/engine/ob_operator.cpp",
            "src/sql/engine/ob_batch_rows.cpp",
            "src/sql/engine/ob_operator_factory.cpp",
            "src/sql/engine/ob_phy_operator_type.cpp",
            "src/sql/engine/ob_physical_plan.cpp",
            "src/sql/engine/ob_physical_plan_ctx.cpp",
            "src/sql/engine/ob_sql_mem_mgr_processor.cpp",
            "src/sql/engine/prepare/ob_deallocate_executor.cpp",
            "src/sql/engine/prepare/ob_execute_executor.cpp",
            "src/sql/engine/prepare/ob_prepare_executor.cpp",
            "src/sql/engine/recursive_cte/ob_fake_cte_table_op.cpp",
            "src/sql/engine/recursive_cte/ob_recursive_inner_data_op.cpp",
            "src/sql/engine/recursive_cte/ob_recursive_union_all_op.cpp",
            "src/sql/engine/recursive_cte/ob_search_method_op.cpp",
            "src/sql/engine/sort/ob_base_sort.cpp",
            "src/sql/engine/sort/ob_sort_basic_info.cpp",
            "src/sql/engine/sort/ob_sort_op.cpp",
            "src/sql/engine/sort/ob_sort_op_impl.cpp",
            "src/sql/engine/subquery/ob_subplan_filter_op.cpp",
            "src/sql/engine/subquery/ob_subplan_scan_op.cpp",
            "src/sql/engine/user_defined_function/ob_pl_user_defined_agg_function.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_1",
        language = "c++",
        srcs = [
            "src/sql/engine/graph/graph_feedback_loop_op.cpp",
            "src/sql/engine/graph/graph_expand.cpp",
            "src/sql/engine/window_function/ob_window_function_op.cpp",
            "src/sql/engine/opt_statistics/ob_optimizer_stats_gathering_op.cpp",
            "src/sql/engine/ob_subschema_ctx.cpp",
            "src/sql/engine/sort/ob_pd_topn_sort_filter.cpp",
            "src/sql/engine/expand/ob_expand_vec_op.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_aggregate_core_0",
        language = "c++",
        srcs = [
            "src/sql/engine/aggregate/ob_pushdown_aggregate_program.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_aggregate_groupby_0",
        language = "c++",
        srcs = [
            "src/sql/engine/aggregate/ob_distinct_op.cpp",
            "src/sql/engine/aggregate/ob_exec_hash_struct.cpp",
            "src/sql/engine/aggregate/ob_groupby_op.cpp",
            "src/sql/engine/aggregate/ob_hash_distinct_op.cpp",
            "src/sql/engine/aggregate/ob_hash_groupby_op.cpp",
            "src/sql/engine/aggregate/ob_merge_distinct_op.cpp",
            "src/sql/engine/aggregate/ob_merge_groupby_op.cpp",
            "src/sql/engine/aggregate/ob_scalar_aggregate_op.cpp",
            "src/sql/engine/aggregate/ob_adaptive_bypass_ctrl.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_basic_0",
        language = "c++",
        srcs = [
            "src/sql/engine/basic/ob_batch_result_holder.cpp",
            "src/sql/engine/basic/ob_temp_block_store.cpp",
            "src/sql/engine/basic/ob_temp_column_store.cpp",
            "src/sql/engine/basic/ob_temp_column_spill_spool.cpp",
            "src/sql/engine/basic/ob_chunk_datum_store.cpp",
            "src/sql/engine/basic/ob_chunk_row_store.cpp",
            "src/sql/engine/basic/ob_expr_values_op.cpp",
            "src/sql/engine/basic/ob_function_table_op.cpp",
            "src/sql/engine/basic/ob_group_join_buffer.cpp",
            "src/sql/engine/basic/ob_hash_partitioning_infrastructure_op.cpp",
            "src/sql/engine/basic/ob_json_table_op.cpp",
            "src/sql/engine/basic/ob_limit_op.cpp",
            "src/sql/engine/basic/ob_material_op_impl.cpp",
            "src/sql/engine/basic/ob_material_op.cpp",
            "src/sql/engine/basic/ob_monitoring_dump_op.cpp",
            "src/sql/engine/basic/ob_pushdown_filter.cpp",
            "src/sql/engine/basic/ob_ra_datum_store.cpp",
            "src/sql/engine/basic/ob_ra_row_store.cpp",
            "src/sql/engine/basic/ob_select_into_op.cpp",
            "src/sql/engine/basic/ob_select_into_basic.cpp",
            "src/sql/engine/basic/ob_external_file_writer.cpp",
            "src/sql/engine/basic/ob_temp_table_access_op.cpp",
            "src/sql/engine/basic/ob_temp_table_insert_op.cpp",
            "src/sql/engine/basic/ob_temp_table_transformation_op.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_basic_1",
        language = "c++",
        srcs = [
            "src/sql/engine/basic/ob_topk_op.cpp",
            "src/sql/engine/basic/ob_values_op.cpp",
            "src/sql/engine/basic/ob_stat_collector_op.cpp",
            "src/sql/engine/basic/chunk_store/ob_chunk_block.cpp",
            "src/sql/engine/basic/chunk_store/ob_compact_store.cpp",
            "src/sql/engine/basic/chunk_store/ob_default_block_reader.cpp",
            "src/sql/engine/basic/chunk_store/ob_default_block_writer.cpp",
            "src/sql/engine/basic/chunk_store/ob_compact_block_reader.cpp",
            "src/sql/engine/basic/chunk_store/ob_compact_block_writer.cpp",
            "src/sql/engine/basic/chunk_store/ob_chunk_block_compressor.cpp",
            "src/sql/engine/basic/ob_values_table_access_op.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_cmd_0",
        language = "c++",
        srcs = [
            "src/sql/engine/cmd/ob_alter_system_executor.cpp",
            "src/sql/engine/cmd/ob_analyze_executor.cpp",
            "src/sql/engine/cmd/ob_database_executor.cpp",
            "src/sql/engine/cmd/graph_ddl_executor.cpp",
            "src/sql/engine/cmd/ob_dcl_executor.cpp",
            "src/sql/engine/cmd/ob_empty_query_executor.cpp",
            "src/sql/engine/cmd/ob_get_diagnostics_executor.cpp",
            "src/sql/engine/cmd/ob_index_executor.cpp",
            "src/sql/engine/cmd/ob_kill_executor.cpp",
            "src/sql/engine/cmd/ob_kill_session_arg.cpp",
            "src/sql/engine/cmd/ob_load_data_file_reader.cpp",
            "src/sql/engine/cmd/ob_load_data_executor.cpp",
            "src/sql/engine/cmd/ob_load_data_impl.cpp",
            "src/sql/engine/cmd/ob_load_data_parser.cpp",
            "src/sql/engine/cmd/ob_load_data_utils.cpp",
            "src/sql/engine/cmd/ob_lock_table_executor.cpp",
            "src/sql/engine/cmd/ob_outline_executor.cpp",
            "src/sql/engine/cmd/ob_package_executor.cpp",
            "src/sql/engine/cmd/ob_partition_executor_utils.cpp",
            "src/sql/engine/cmd/ob_role_cmd_executor.cpp",
            "src/sql/engine/cmd/ob_routine_executor.cpp",
            "src/sql/engine/cmd/ob_set_names_executor.cpp",
            "src/sql/engine/cmd/ob_set_password_executor.cpp",
            "src/sql/engine/cmd/ob_ddl_executor_util.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_cmd_1",
        language = "c++",
        srcs = [
            "src/sql/engine/cmd/ob_table_executor.cpp",
            "src/sql/engine/cmd/ob_tcl_executor.cpp",
            "src/sql/engine/cmd/ob_trigger_executor.cpp",
            "src/sql/engine/cmd/ob_user_cmd_executor.cpp",
            "src/sql/engine/cmd/ob_variable_set_executor.cpp",
            "src/sql/engine/cmd/ob_merge_table_executor.cpp",
            "src/sql/engine/cmd/ob_vector_index_refresh.cpp",
            "src/sql/engine/cmd/ob_vector_refresh_index_executor.cpp",
            "src/sql/engine/cmd/ob_recyclebin_executor.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_dml_0",
        language = "c++",
        srcs = [
            "src/sql/engine/dml/ob_conflict_checker.cpp",
            "src/sql/engine/dml/ob_dml_ctx_define.cpp",
            "src/sql/engine/dml/ob_dml_service.cpp",
            "src/sql/engine/dml/ob_table_delete_op.cpp",
            "src/sql/engine/dml/ob_table_insert_op.cpp",
            "src/sql/engine/dml/ob_table_insert_up_op.cpp",
            "src/sql/engine/dml/ob_table_lock_op.cpp",
            "src/sql/engine/dml/ob_table_modify_op.cpp",
            "src/sql/engine/dml/ob_table_replace_op.cpp",
            "src/sql/engine/dml/ob_table_update_op.cpp",
            "src/sql/engine/dml/ob_trigger_handler.cpp",
            "src/sql/engine/dml/ob_fk_checker.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_0",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_batch_eval_util.cpp",
            "src/sql/engine/expr/ob_expr.cpp",
            "src/sql/engine/expr/ob_expr_acos.cpp",
            "src/sql/engine/expr/ob_expr_symmetric_encrypt.cpp",
            "src/sql/engine/expr/ob_expr_agg_param_list.cpp",
            "src/sql/engine/expr/ob_expr_and.cpp",
            "src/sql/engine/expr/ob_expr_any_value.cpp",
            "src/sql/engine/expr/ob_expr_arg_case.cpp",
            "src/sql/engine/expr/ob_expr_ascii.cpp",
            "src/sql/engine/expr/ob_expr_asin.cpp",
            "src/sql/engine/expr/ob_expr_assign.cpp",
            "src/sql/engine/expr/ob_expr_atan.cpp",
            "src/sql/engine/expr/ob_expr_atan2.cpp",
            "src/sql/engine/expr/ob_expr_autoinc_nextval.cpp",
            "src/sql/engine/expr/ob_expr_benchmark.cpp",
            "src/sql/engine/expr/ob_expr_between.cpp",
            "src/sql/engine/expr/ob_expr_bit_and.cpp",
            "src/sql/engine/expr/ob_expr_bit_count.cpp",
            "src/sql/engine/expr/ob_expr_bit_left_shift.cpp",
            "src/sql/engine/expr/ob_expr_bit_length.cpp",
            "src/sql/engine/expr/ob_expr_bit_neg.cpp",
            "src/sql/engine/expr/ob_expr_bit_or.cpp",
            "src/sql/engine/expr/ob_expr_bit_right_shift.cpp",
            "src/sql/engine/expr/ob_expr_bit_xor.cpp",
            "src/sql/engine/expr/ob_expr_bm25.cpp",
            "src/sql/engine/expr/ob_expr_bool.cpp",
            "src/sql/engine/expr/ob_expr_calc_partition_id.cpp",
            "src/sql/engine/expr/ob_expr_case.cpp",
            "src/sql/engine/expr/ob_expr_char.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_1",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_cast.cpp",
            "src/sql/engine/expr/ob_expr_coalesce.cpp",
            "src/sql/engine/expr/ob_expr_collation.cpp",
            "src/sql/engine/expr/ob_expr_column_conv.cpp",
            "src/sql/engine/expr/ob_expr_compress.cpp",
            "src/sql/engine/expr/ob_expr_concat.cpp",
            "src/sql/engine/expr/ob_expr_concat_ws.cpp",
            "src/sql/engine/expr/ob_expr_connection_id.cpp",
            "src/sql/engine/expr/ob_expr_conv.cpp",
            "src/sql/engine/expr/ob_expr_convert.cpp",
            "src/sql/engine/expr/ob_expr_convert_tz.cpp",
            "src/sql/engine/expr/ob_expr_cos.cpp",
            "src/sql/engine/expr/ob_expr_cot.cpp",
            "src/sql/engine/expr/ob_expr_crc32.cpp",
            "src/sql/engine/expr/ob_expr_cur_time.cpp",
            "src/sql/engine/expr/ob_expr_current_user.cpp",
            "src/sql/engine/expr/ob_expr_current_user_priv.cpp",
            "src/sql/engine/expr/ob_expr_database.cpp",
            "src/sql/engine/expr/ob_expr_date.cpp",
            "src/sql/engine/expr/ob_expr_date_add.cpp",
            "src/sql/engine/expr/ob_expr_date_diff.cpp",
            "src/sql/engine/expr/ob_expr_date_format.cpp",
            "src/sql/engine/expr/ob_expr_day_of_func.cpp",
            "src/sql/engine/expr/ob_expr_degrees.cpp",
            "src/sql/engine/expr/ob_expr_des_hex_str.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_10",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_word_segment.cpp",
            "src/sql/engine/expr/ob_expr_wrapper_inner.cpp",
            "src/sql/engine/expr/ob_expr_xor.cpp",
            "src/sql/engine/expr/ob_infix_expression.cpp",
            "src/sql/engine/expr/ob_iter_expr_range_param.cpp",
            "src/sql/engine/expr/ob_pl_expr_subquery.cpp",
            "src/sql/engine/expr/ob_postfix_expression.cpp",
            "src/sql/engine/expr/ob_rt_datum_arith.cpp",
            "src/sql/engine/expr/ob_sql_expression.cpp",
            "src/sql/engine/expr/ob_expr_encode_sortkey.cpp",
            "src/sql/engine/expr/ob_expr_hash.cpp",
            "src/sql/engine/expr/ob_expr_timestamp_to_scn.cpp",
            "src/sql/engine/expr/ob_expr_scn_to_timestamp.cpp",
            "src/sql/engine/expr/ob_expr_unix_timestamp.cpp",
            "src/sql/engine/expr/ob_expr_upper.cpp",
            "src/sql/engine/expr/ob_expr_usec_to_time.cpp",
            "src/sql/engine/expr/ob_expr_user.cpp",
            "src/sql/engine/expr/ob_expr_util.cpp",
            "src/sql/engine/expr/ob_expr_uuid.cpp",
            "src/sql/engine/expr/ob_expr_uuid_short.cpp",
            "src/sql/engine/expr/ob_expr_validate_password_strength.cpp",
            "src/sql/engine/expr/ob_expr_version.cpp",
            "src/sql/engine/expr/ob_expr_week_of_func.cpp",
            "src/sql/engine/expr/ob_expr_weight_string.cpp",
            "src/sql/engine/expr/ob_expr_to_outfile_row.cpp",
            "src/sql/engine/expr/ob_expr_to_type.cpp",
            "src/sql/engine/expr/ob_expr_trim.cpp",
            "src/sql/engine/expr/ob_expr_truncate.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_11",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_type_to_str.cpp",
            "src/sql/engine/expr/ob_expr_udf.cpp",
            "src/sql/engine/expr/ob_expr_unhex.cpp",
            "src/sql/engine/expr/ob_expr_tablet_autoinc_nextval.cpp",
            "src/sql/engine/expr/ob_expr_tan.cpp",
            "src/sql/engine/expr/ob_expr_time.cpp",
            "src/sql/engine/expr/ob_expr_time_diff.cpp",
            "src/sql/engine/expr/ob_expr_time_format.cpp",
            "src/sql/engine/expr/ob_expr_time_to_usec.cpp",
            "src/sql/engine/expr/ob_expr_timestamp.cpp",
            "src/sql/engine/expr/ob_expr_timestamp_add.cpp",
            "src/sql/engine/expr/ob_expr_timestamp_diff.cpp",
            "src/sql/engine/expr/ob_expr_timestamp_nvl.cpp",
            "src/sql/engine/expr/ob_expr_to_base64.cpp",
            "src/sql/engine/expr/ob_expr_to_days.cpp",
            "src/sql/engine/expr/ob_expr_subquery_not_equal.cpp",
            "src/sql/engine/expr/ob_expr_subquery_ns_equal.cpp",
            "src/sql/engine/expr/ob_expr_subquery_ref.cpp",
            "src/sql/engine/expr/ob_expr_substr.cpp",
            "src/sql/engine/expr/ob_expr_generator_func.cpp",
            "src/sql/engine/expr/ob_expr_zipf.cpp",
            "src/sql/engine/expr/ob_expr_uniform.cpp",
            "src/sql/engine/expr/ob_expr_normal.cpp",
            "src/sql/engine/expr/ob_expr_substrb.cpp",
            "src/sql/engine/expr/ob_expr_substring_index.cpp",
            "src/sql/engine/expr/ob_expr_sys_op_opnsize.cpp",
            "src/sql/engine/expr/ob_expr_sys_privilege_check.cpp",
            "src/sql/engine/expr/ob_expr_sys_view_bigint_param.cpp",
            "src/sql/engine/expr/ob_expr_shadow_uk_project.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_12",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_sin.cpp",
            "src/sql/engine/expr/ob_expr_soundex.cpp",
            "src/sql/engine/expr/ob_expr_space.cpp",
            "src/sql/engine/expr/ob_expr_sqrt.cpp",
            "src/sql/engine/expr/ob_expr_statement_digest.cpp",
            "src/sql/engine/expr/ob_expr_stmt_id.cpp",
            "src/sql/engine/expr/ob_expr_str_to_date.cpp",
            "src/sql/engine/expr/ob_expr_strcmp.cpp",
            "src/sql/engine/expr/ob_expr_subquery_equal.cpp",
            "src/sql/engine/expr/ob_expr_subquery_greater_equal.cpp",
            "src/sql/engine/expr/ob_expr_subquery_greater_than.cpp",
            "src/sql/engine/expr/ob_expr_subquery_less_equal.cpp",
            "src/sql/engine/expr/ob_expr_subquery_less_than.cpp",
            "src/sql/engine/expr/ob_expr_remove_const.cpp",
            "src/sql/engine/expr/ob_expr_repeat.cpp",
            "src/sql/engine/expr/ob_expr_replace.cpp",
            "src/sql/engine/expr/ob_expr_res_type_map.cpp",
            "src/sql/engine/expr/ob_expr_result_type_util.cpp",
            "src/sql/engine/expr/ob_expr_reverse.cpp",
            "src/sql/engine/expr/ob_expr_right.cpp",
            "src/sql/engine/expr/ob_expr_row_count.cpp",
            "src/sql/engine/expr/ob_expr_rpc_port.cpp",
            "src/sql/engine/expr/ob_expr_sha.cpp",
            "src/sql/engine/expr/ob_expr_quarter.cpp",
            "src/sql/engine/expr/ob_expr_quote.cpp",
            "src/sql/engine/expr/ob_expr_radians.cpp",
            "src/sql/engine/expr/ob_expr_rand.cpp",
            "src/sql/engine/expr/ob_expr_random.cpp",
            "src/sql/engine/expr/ob_expr_randstr.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_13",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_random_bytes.cpp",
            "src/sql/engine/expr/ob_expr_regexp.cpp",
            "src/sql/engine/expr/ob_expr_regexp_context.cpp",
            "src/sql/engine/expr/ob_expr_regexp_instr.cpp",
            "src/sql/engine/expr/ob_expr_regexp_like.cpp",
            "src/sql/engine/expr/ob_expr_regexp_replace.cpp",
            "src/sql/engine/expr/ob_expr_regexp_substr.cpp",
            "src/sql/engine/expr/ob_expr_part_id_pseudo_column.cpp",
            "src/sql/engine/expr/ob_expr_password.cpp",
            "src/sql/engine/expr/ob_expr_period_diff.cpp",
            "src/sql/engine/expr/ob_expr_pi.cpp",
            "src/sql/engine/expr/ob_expr_pl_associative_index.cpp",
            "src/sql/engine/expr/ob_expr_pl_get_cursor_attr.cpp",
            "src/sql/engine/expr/ob_expr_pl_integer_checker.cpp",
            "src/sql/engine/expr/ob_expr_pl_sqlcode_sqlerrm.cpp",
            "src/sql/engine/expr/ob_expr_plsql_variable.cpp",
            "src/sql/engine/expr/ob_expr_position.cpp",
            "src/sql/engine/expr/ob_expr_pow.cpp",
            "src/sql/engine/expr/ob_expr_promotion_util.cpp",
            "src/sql/engine/expr/ob_expr_nvl.cpp",
            "src/sql/engine/expr/ob_expr_obj_access.cpp",
            "src/sql/engine/expr/ob_expr_object_construct.cpp",
            "src/sql/engine/expr/ob_expr_obversion.cpp",
            "src/sql/engine/expr/ob_expr_operator.cpp",
            "src/sql/engine/expr/ob_expr_operator_factory.cpp",
            "src/sql/engine/expr/ob_expr_or.cpp",
            "src/sql/engine/expr/ob_expr_output_pack.cpp",
            "src/sql/engine/expr/ob_lob_result_materializer.cpp",
            "src/sql/engine/expr/ob_expr_pad.cpp",
            "src/sql/engine/expr/ob_expr_mysql_port.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_14",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_func_ceil.cpp",
            "src/sql/engine/expr/ob_expr_name_const.cpp",
            "src/sql/engine/expr/ob_expr_neg.cpp",
            "src/sql/engine/expr/ob_expr_align_date4cmp.cpp",
            "src/sql/engine/expr/ob_expr_not.cpp",
            "src/sql/engine/expr/ob_expr_not_between.cpp",
            "src/sql/engine/expr/ob_expr_not_equal.cpp",
            "src/sql/engine/expr/ob_expr_not_exists.cpp",
            "src/sql/engine/expr/ob_expr_not_in.cpp",
            "src/sql/engine/expr/ob_expr_null_safe_equal.cpp",
            "src/sql/engine/expr/ob_expr_nullif.cpp",
            "src/sql/engine/expr/ob_expr_div.cpp",
            "src/sql/engine/expr/ob_expr_abs.cpp",
            "src/sql/engine/expr/ob_expr_minus.cpp",
            "src/sql/engine/expr/ob_expr_to_pinyin_tab.cpp",
            "src/sql/engine/expr/ob_expr_to_pinyin.cpp",
            "src/sql/engine/expr/ob_expr_url_codec.cpp",
            "src/sql/engine/expr/ob_expr_keyvalue.cpp",
            "src/sql/engine/expr/ob_expr_demote_cast.cpp",
            "src/sql/engine/expr/ob_expr_array_max.cpp",
            "src/sql/engine/expr/ob_expr_array_avg.cpp",
            "src/sql/engine/expr/ob_expr_array_first.cpp",
            "src/sql/engine/expr/ob_expr_array_concat.cpp",
            "src/sql/engine/expr/ob_expr_array_difference.cpp",
            "src/sql/engine/expr/ob_expr_array_compact.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_15",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_array_sortby.cpp",
            "src/sql/engine/expr/ob_expr_array_filter.cpp",
            "src/sql/engine/expr/ob_expr_array_range.cpp",
            "src/sql/engine/expr/ob_expr_array_length.cpp",
            "src/sql/engine/expr/ob_expr_array_position.cpp",
            "src/sql/engine/expr/ob_expr_array_slice.cpp",
            "src/sql/engine/expr/ob_expr_inner_info_cols_printer.cpp",
            "src/sql/engine/expr/ob_expr_array_except.cpp",
            "src/sql/engine/expr/ob_expr_array_union.cpp",
            "src/sql/engine/expr/ob_expr_array_intersect.cpp",
            "src/sql/engine/expr/ob_expr_map.cpp",
            "src/sql/engine/expr/ob_expr_map_keys.cpp",
            "src/sql/engine/expr/ob_expr_spiv_dim.cpp",
            "src/sql/engine/expr/ob_expr_spiv_value.cpp",
            "src/sql/engine/expr/ob_expr_semantic_distance.cpp",
            "src/sql/engine/expr/ob_expr_ai/ob_ai_func.cpp",
            "src/sql/engine/expr/ob_expr_ai/ob_ai_func_client.cpp",
            "src/sql/engine/expr/ob_expr_ai/ob_ai_func_utils.cpp",
            "src/sql/engine/expr/ob_expr_ai/ob_expr_ai_complete.cpp",
            "src/sql/engine/expr/ob_expr_ai/ob_expr_ai_embed.cpp",
            "src/sql/engine/expr/ob_expr_ai/ob_expr_ai_rerank.cpp",
            "src/sql/engine/expr/ob_expr_ai/ob_expr_ai_prompt.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_2",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_doc_id.cpp",
            "src/sql/engine/expr/ob_expr_doc_length.cpp",
            "src/sql/engine/expr/ob_expr_elt.cpp",
            "src/sql/engine/expr/ob_expr_encrypt.cpp",
            "src/sql/engine/expr/ob_expr_equal.cpp",
            "src/sql/engine/expr/ob_expr_estimate_ndv.cpp",
            "src/sql/engine/expr/ob_expr_exists.cpp",
            "src/sql/engine/expr/ob_expr_exp.cpp",
            "src/sql/engine/expr/ob_expr_export_set.cpp",
            "src/sql/engine/expr/ob_expr_extra_info_factory.cpp",
            "src/sql/engine/expr/ob_expr_extract.cpp",
            "src/sql/engine/expr/ob_expr_field.cpp",
            "src/sql/engine/expr/ob_expr_find_in_set.cpp",
            "src/sql/engine/expr/ob_expr_format.cpp",
            "src/sql/engine/expr/ob_expr_found_rows.cpp",
            "src/sql/engine/expr/ob_expr_frame_info.cpp",
            "src/sql/engine/expr/ob_expr_from_base64.cpp",
            "src/sql/engine/expr/ob_expr_from_days.cpp",
            "src/sql/engine/expr/ob_expr_from_unix_time.cpp",
            "src/sql/engine/expr/ob_expr_fun_default.cpp",
            "src/sql/engine/expr/ob_expr_fun_values.cpp",
            "src/sql/engine/expr/ob_expr_func_dump.cpp",
            "src/sql/engine/expr/ob_expr_func_part_hash.cpp",
            "src/sql/engine/expr/ob_expr_func_partition_key.cpp",
            "src/sql/engine/expr/ob_expr_func_round.cpp",
            "src/sql/engine/expr/ob_expr_func_sleep.cpp",
            "src/sql/engine/expr/ob_expr_get_package_var.cpp",
            "src/sql/engine/expr/ob_expr_get_path.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_3",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_get_subprogram_var.cpp",
            "src/sql/engine/expr/ob_expr_get_sys_var.cpp",
            "src/sql/engine/expr/ob_expr_get_user_var.cpp",
            "src/sql/engine/expr/ob_expr_greater_equal.cpp",
            "src/sql/engine/expr/ob_expr_greater_than.cpp",
            "src/sql/engine/expr/ob_expr_greatest.cpp",
            "src/sql/engine/expr/ob_expr_hex.cpp",
            "src/sql/engine/expr/ob_expr_host_ip.cpp",
            "src/sql/engine/expr/ob_expr_icu_version.cpp",
            "src/sql/engine/expr/ob_expr_ifnull.cpp",
            "src/sql/engine/expr/ob_expr_inet.cpp",
            "src/sql/engine/expr/ob_expr_inner_decode_like.cpp",
            "src/sql/engine/expr/ob_expr_inner_double_to_int.cpp",
            "src/sql/engine/expr/ob_expr_inner_decimal_to_year.cpp",
            "src/sql/engine/expr/ob_expr_inner_trim.cpp",
            "src/sql/engine/expr/ob_expr_insert.cpp",
            "src/sql/engine/expr/ob_expr_instr.cpp",
            "src/sql/engine/expr/ob_expr_int2ip.cpp",
            "src/sql/engine/expr/ob_expr_int_div.cpp",
            "src/sql/engine/expr/ob_expr_interval.cpp",
            "src/sql/engine/expr/ob_expr_ip2int.cpp",
            "src/sql/engine/expr/ob_expr_is.cpp",
            "src/sql/engine/expr/ob_expr_json_func_helper.cpp",
            "src/sql/engine/expr/ob_expr_json_extract.cpp",
            "src/sql/engine/expr/ob_expr_json_schema_valid.cpp",
            "src/sql/engine/expr/ob_expr_json_schema_validation_report.cpp",
            "src/sql/engine/expr/ob_expr_json_contains.cpp",
            "src/sql/engine/expr/ob_expr_json_contains_path.cpp",
            "src/sql/engine/expr/ob_expr_json_depth.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_4",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_json_keys.cpp",
            "src/sql/engine/expr/ob_expr_current_scn.cpp",
            "src/sql/engine/expr/ob_expr_json_overlaps.cpp",
            "src/sql/engine/expr/ob_expr_json_remove.cpp",
            "src/sql/engine/expr/ob_expr_json_replace.cpp",
            "src/sql/engine/expr/ob_expr_json_insert.cpp",
            "src/sql/engine/expr/ob_expr_json_member_of.cpp",
            "src/sql/engine/expr/ob_expr_json_merge_preserve.cpp",
            "src/sql/engine/expr/ob_expr_json_merge_patch.cpp",
            "src/sql/engine/expr/ob_expr_json_merge.cpp",
            "src/sql/engine/expr/ob_expr_json_pretty.cpp",
            "src/sql/engine/expr/ob_expr_json_object.cpp",
            "src/sql/engine/expr/ob_expr_json_search.cpp",
            "src/sql/engine/expr/ob_expr_json_array.cpp",
            "src/sql/engine/expr/ob_expr_json_array_append.cpp",
            "src/sql/engine/expr/ob_expr_json_append.cpp",
            "src/sql/engine/expr/ob_expr_json_array_insert.cpp",
            "src/sql/engine/expr/ob_expr_json_quote.cpp",
            "src/sql/engine/expr/ob_expr_json_unquote.cpp",
            "src/sql/engine/expr/ob_expr_json_valid.cpp",
            "src/sql/engine/expr/ob_expr_json_value.cpp",
            "src/sql/engine/expr/ob_expr_json_query.cpp",
            "src/sql/engine/expr/ob_expr_json_type.cpp",
            "src/sql/engine/expr/ob_expr_json_length.cpp",
            "src/sql/engine/expr/ob_expr_json_storage_size.cpp",
            "src/sql/engine/expr/ob_expr_json_storage_free.cpp",
            "src/sql/engine/expr/ob_expr_json_set.cpp",
            "src/sql/engine/expr/ob_expr_join_filter.cpp",
            "src/sql/engine/expr/ob_expr_last_exec_id.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_5",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_last_insert_id.cpp",
            "src/sql/engine/expr/ob_expr_last_trace_id.cpp",
            "src/sql/engine/expr/ob_expr_least.cpp",
            "src/sql/engine/expr/ob_expr_left.cpp",
            "src/sql/engine/expr/ob_expr_length.cpp",
            "src/sql/engine/expr/ob_expr_less_equal.cpp",
            "src/sql/engine/expr/ob_expr_less_than.cpp",
            "src/sql/engine/expr/ob_expr_like.cpp",
            "src/sql/engine/expr/ob_expr_lnnvl.cpp",
            "src/sql/engine/expr/ob_expr_locate.cpp",
            "src/sql/engine/expr/ob_expr_log.cpp",
            "src/sql/engine/expr/ob_expr_log10.cpp",
            "src/sql/engine/expr/ob_expr_log2.cpp",
            "src/sql/engine/expr/ob_expr_lower.cpp",
            "src/sql/engine/expr/ob_expr_lrpad.cpp",
            "src/sql/engine/expr/ob_expr_make_set.cpp",
            "src/sql/engine/expr/ob_expr_makedate.cpp",
            "src/sql/engine/expr/ob_expr_maketime.cpp",
            "src/sql/engine/expr/ob_expr_md5.cpp",
            "src/sql/engine/expr/ob_expr_mid.cpp",
            "src/sql/engine/expr/ob_expr_mod.cpp",
            "src/sql/engine/expr/ob_expr_tokenize.cpp",
            "src/sql/engine/expr/ob_expr_gtid.cpp",
            "src/sql/engine/expr/ob_expr_inner_table_option_printer.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_6",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_json_utils.cpp",
            "src/sql/engine/expr/ob_expr_array_contains.cpp",
            "src/sql/engine/expr/ob_expr_array_to_string.cpp",
            "src/sql/engine/expr/ob_expr_string_to_array.cpp",
            "src/sql/engine/expr/ob_expr_array_append.cpp",
            "src/sql/engine/expr/ob_expr_element_at.cpp",
            "src/sql/engine/expr/ob_expr_array_cardinality.cpp",
            "src/sql/engine/expr/ob_expr_decode_trace_id.cpp",
            "src/sql/engine/expr/ob_expr_split_part.cpp",
            "src/sql/engine/expr/ob_expr_array_overlaps.cpp",
            "src/sql/engine/expr/ob_expr_array_contains_all.cpp",
            "src/sql/engine/expr/ob_expr_array_distinct.cpp",
            "src/sql/engine/expr/ob_expr_array_map.cpp",
            "src/sql/engine/expr/ob_expr_array_sum.cpp",
            "src/sql/engine/expr/ob_expr_array_remove.cpp",
            "src/sql/engine/expr/ob_expr_extract_cert_expired_time.cpp",
            "src/sql/engine/expr/ob_expr_transaction_id.cpp",
            "src/sql/engine/expr/ob_expr_inner_row_cmp_val.cpp",
            "src/sql/engine/expr/ob_expr_array.cpp",
            "src/sql/engine/expr/ob_expr_vector.cpp",
            "src/sql/engine/expr/ob_expr_vector_similarity.cpp",
            "src/sql/engine/expr/ob_distribution.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_7",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_array_expr_utils.cpp",
            "src/sql/engine/expr/ob_expr_vec_ivf_center_id.cpp",
            "src/sql/engine/expr/ob_expr_vec_ivf_center_vector.cpp",
            "src/sql/engine/expr/ob_expr_vec_ivf_flat_data_vector.cpp",
            "src/sql/engine/expr/ob_expr_vec_ivf_sq8_data_vector.cpp",
            "src/sql/engine/expr/ob_expr_vec_ivf_meta_id.cpp",
            "src/sql/engine/expr/ob_expr_vec_ivf_meta_vector.cpp",
            "src/sql/engine/expr/ob_expr_vec_ivf_pq_center_id.cpp",
            "src/sql/engine/expr/ob_expr_vec_ivf_pq_center_ids.cpp",
            "src/sql/engine/expr/ob_expr_vec_ivf_pq_center_vector.cpp",
            "src/sql/engine/expr/ob_expr_vec_vid.cpp",
            "src/sql/engine/expr/ob_expr_vec_type.cpp",
            "src/sql/engine/expr/ob_expr_vec_vector.cpp",
            "src/sql/engine/expr/ob_expr_vec_scn.cpp",
            "src/sql/engine/expr/ob_expr_vec_key.cpp",
            "src/sql/engine/expr/ob_expr_vec_data.cpp",
            "src/sql/engine/expr/ob_expr_vec_chunk.cpp",
            "src/sql/engine/expr/ob_expr_embedded_vec.cpp",
            "src/sql/engine/expr/ob_expr_topn_filter.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_makeenvelope.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_clipbybox2d.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_pointonsurface.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_geometrytype.cpp",
            "src/sql/engine/expr/ob_expr_st_crosses.cpp",
            "src/sql/engine/expr/ob_expr_st_overlaps.cpp",
            "src/sql/engine/expr/ob_expr_st_union.cpp",
            "src/sql/engine/expr/ob_expr_st_length.cpp",
            "src/sql/engine/expr/ob_expr_st_difference.cpp",
            "src/sql/engine/expr/ob_expr_st_asgeojson.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_8",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_collection_construct.cpp",
            "src/sql/engine/expr/ob_expr_st_symdifference.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_asmvtgeom.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_makevalid.cpp",
            "src/sql/engine/expr/ob_expr_lock_func.cpp",
            "src/sql/engine/expr/ob_expr_extract_value.cpp",
            "src/sql/engine/expr/ob_expr_update_xml.cpp",
            "src/sql/engine/expr/ob_expr_sql_udt_utils.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_numinteriorrings.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_iscollection.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_equals.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_touches.cpp",
            "src/sql/engine/expr/ob_expr_st_dwithin.cpp",
            "src/sql/engine/expr/ob_expr_st_aswkb.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_asewkb.cpp",
            "src/sql/engine/expr/ob_expr_st_distance_sphere.cpp",
            "src/sql/engine/expr/ob_expr_st_contains.cpp",
            "src/sql/engine/expr/ob_expr_st_within.cpp",
            "src/sql/engine/expr/ob_expr_sql_mode_convert.cpp",
            "src/sql/engine/expr/ob_expr_can_access_trigger.cpp",
            "src/sql/engine/expr/ob_expr_mysql_proc_info.cpp",
            "src/sql/engine/expr/ob_expr_get_mysql_routine_parameter_type_str.cpp",
            "src/sql/engine/expr/ob_expr_prefix_pattern.cpp",
            "src/sql/engine/expr/ob_expr_xml_func_helper.cpp",
            "src/sql/engine/expr/ob_expr_multi_mode_func_helper.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_transform.cpp",
            "src/sql/engine/expr/ob_expr_st_covers.cpp",
            "src/sql/engine/expr/ob_expr_st_bestsrid.cpp",
            "src/sql/engine/expr/ob_expr_st_astext.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_expr_9",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_priv_st_setsrid.cpp",
            "src/sql/engine/expr/ob_expr_st_geometryfromtext.cpp",
            "src/sql/engine/expr/ob_expr_st_buffer.cpp",
            "src/sql/engine/expr/ob_expr_st_geomfromewkb.cpp",
            "src/sql/engine/expr/ob_expr_st_geomfromwkb.cpp",
            "src/sql/engine/expr/ob_expr_st_geomfromewkt.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_geogfromtext.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_geographyfromtext.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_geohash.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_makepoint.cpp",
            "src/sql/engine/expr/ob_expr_st_asewkt.cpp",
            "src/sql/engine/expr/ob_expr_st_srid.cpp",
            "src/sql/engine/expr/ob_expr_st_distance.cpp",
            "src/sql/engine/expr/ob_expr_st_isvalid.cpp",
            "src/sql/engine/expr/ob_expr_errno.cpp",
            "src/sql/engine/expr/ob_expr_lob_utils.cpp",
            "src/sql/engine/expr/ob_expr_format_bytes.cpp",
            "src/sql/engine/expr/ob_expr_format_pico_time.cpp",
            "src/sql/engine/expr/ob_geo_expr_utils.cpp",
            "src/sql/engine/expr/ob_expr_spatial_cellid.cpp",
            "src/sql/engine/expr/ob_expr_spatial_mbr.cpp",
            "src/sql/engine/expr/ob_expr_point.cpp",
            "src/sql/engine/expr/ob_expr_priv_st_point.cpp",
            "src/sql/engine/expr/ob_expr_spatial_collection.cpp",
            "src/sql/engine/expr/ob_expr_st_geomfromtext.cpp",
            "src/sql/engine/expr/ob_expr_st_intersects.cpp",
            "src/sql/engine/expr/ob_expr_st_area.cpp",
            "src/sql/engine/expr/ob_expr_st_x.cpp",
            "src/sql/engine/expr/ob_expr_st_transform.cpp",
            "src/sql/engine/expr/ob_expr_word_count.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_join_0",
        language = "c++",
        srcs = [
            "src/sql/engine/join/ob_basic_nested_loop_join_op.cpp",
            "src/sql/engine/join/ob_hash_join_basic.cpp",
            "src/sql/engine/join/ob_hash_join_op.cpp",
            "src/sql/engine/join/ob_join_filter_op.cpp",
            "src/sql/engine/join/ob_join_op.cpp",
            "src/sql/engine/join/ob_merge_join_op.cpp",
            "src/sql/engine/join/ob_nested_loop_join_op.cpp",
            "src/sql/engine/join/ob_join_filter_material_control_info.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_pdml_0",
        language = "c++",
        srcs = [
            "src/sql/engine/pdml/static/ob_pdml_op_batch_row_cache.cpp",
            "src/sql/engine/pdml/static/ob_pdml_op_data_driver.cpp",
            "src/sql/engine/pdml/static/ob_px_multi_part_delete_op.cpp",
            "src/sql/engine/pdml/static/ob_px_multi_part_insert_op.cpp",
            "src/sql/engine/pdml/static/ob_px_multi_part_modify_op.cpp",
            "src/sql/engine/pdml/static/ob_px_multi_part_update_op.cpp",
            "src/sql/engine/pdml/static/ob_px_sstable_insert_op.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_px_0",
        language = "c++",
        srcs = [
            "src/sql/engine/px/ob_dfo.cpp",
            "src/sql/engine/px/ob_dfo_mgr.cpp",
            "src/sql/engine/px/ob_dfo_scheduler.cpp",
            "src/sql/engine/px/ob_granule_iterator_op.cpp",
            "src/sql/engine/px/ob_granule_pump.cpp",
            "src/sql/engine/px/ob_granule_task_info.cpp",
            "src/sql/engine/px/ob_granule_util.cpp",
            "src/sql/engine/px/ob_px_admission.cpp",
            "src/sql/engine/px/ob_px_bloom_filter.cpp",
            "src/sql/engine/px/ob_px_coord_msg_proc.cpp",
            "src/sql/engine/px/ob_px_coord_op.cpp",
            "src/sql/engine/px/ob_px_data_ch_provider.cpp",
            "src/sql/engine/px/ob_px_dtl_msg.cpp",
            "src/sql/engine/px/ob_px_dtl_proc.cpp",
            "src/sql/engine/px/ob_px_interruption.cpp",
            "src/sql/engine/px/ob_px_op_size_factor.cpp",
            "src/sql/engine/px/ob_px_row_store.cpp",
            "src/sql/engine/px/ob_px_scheduler.cpp",
            "src/sql/engine/px/ob_px_sqc_handler.cpp",
            "src/sql/engine/px/ob_px_sqc_proxy.cpp",
            "src/sql/engine/px/ob_px_sub_coord.cpp",
            "src/sql/engine/px/ob_px_task_process.cpp",
            "src/sql/engine/px/ob_px_target_monitor.cpp",
            "src/sql/engine/px/ob_px_util.cpp",
            "src/sql/engine/px/ob_px_worker.cpp",
            "src/sql/engine/px/ob_px_worker_stat.cpp",
            "src/sql/engine/px/ob_sqc_ctx.cpp",
            "src/sql/engine/px/ob_sub_trans_ctrl.cpp",
            "src/sql/engine/px/ob_slice_calc.cpp",
            "src/sql/engine/px/datahub/ob_dh_msg.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_px_1",
        language = "c++",
        srcs = [
            "src/sql/engine/px/exchange/ob_px_dist_transmit_op.cpp",
            "src/sql/engine/px/exchange/ob_px_fifo_coord_op.cpp",
            "src/sql/engine/px/exchange/ob_px_ms_coord_op.cpp",
            "src/sql/engine/px/exchange/ob_px_ms_receive_op.cpp",
            "src/sql/engine/px/exchange/ob_px_ordered_coord_op.cpp",
            "src/sql/engine/px/exchange/ob_px_receive_op.cpp",
            "src/sql/engine/px/exchange/ob_px_reduce_transmit_op.cpp",
            "src/sql/engine/px/exchange/ob_px_repart_transmit_op.cpp",
            "src/sql/engine/px/exchange/ob_px_transmit_op.cpp",
            "src/sql/engine/px/exchange/ob_receive_op.cpp",
            "src/sql/engine/px/exchange/ob_row_heap.cpp",
            "src/sql/engine/px/exchange/ob_transmit_op.cpp",
            "src/sql/engine/px/datahub/components/ob_dh_barrier.cpp",
            "src/sql/engine/px/datahub/components/ob_dh_sample.cpp",
            "src/sql/engine/px/datahub/components/ob_dh_winbuf.cpp",
            "src/sql/engine/px/datahub/components/ob_dh_range_dist_wf.cpp",
            "src/sql/engine/px/datahub/components/ob_dh_init_channel.cpp",
            "src/sql/engine/px/datahub/components/ob_dh_second_stage_reporting_wf.cpp",
            "src/sql/engine/px/datahub/components/ob_dh_opt_stats_gather.cpp",
            "src/sql/engine/px/datahub/components/ob_dh_join_filter_count_row.cpp",
            "src/sql/engine/px/p2p_datahub/ob_p2p_dh_mgr.cpp",
            "src/sql/engine/px/p2p_datahub/ob_p2p_dh_msg.cpp",
            "src/sql/engine/px/p2p_datahub/ob_runtime_filter_query_range.cpp",
            "src/sql/engine/px/p2p_datahub/ob_runtime_filter_msg.cpp",
            "src/sql/engine/px/p2p_datahub/ob_pushdown_topn_filter_msg.cpp",
            "src/sql/engine/px/ob_px_local_sqc_launcher.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_set_0",
        language = "c++",
        srcs = [
            "src/sql/engine/set/ob_hash_except_op.cpp",
            "src/sql/engine/set/ob_hash_intersect_op.cpp",
            "src/sql/engine/set/ob_hash_set_op.cpp",
            "src/sql/engine/set/ob_hash_union_op.cpp",
            "src/sql/engine/set/ob_merge_except_op.cpp",
            "src/sql/engine/set/ob_merge_intersect_op.cpp",
            "src/sql/engine/set/ob_merge_set_op.cpp",
            "src/sql/engine/set/ob_merge_union_op.cpp",
            "src/sql/engine/set/ob_set_op.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_table_0",
        language = "c++",
        srcs = [
            "src/sql/engine/table/ob_block_sample_scan_op.cpp",
            "src/sql/engine/table/ob_row_sample_scan_op.cpp",
            "src/sql/engine/table/ob_table_partition_ranges.cpp",
            "src/sql/engine/table/ob_table_row_store_op.cpp",
            "src/sql/engine/table/ob_table_scan_op.cpp",
            "src/sql/engine/table/ob_index_lookup_op_impl.cpp",
            "src/sql/engine/table/ob_table_scan_with_index_back_op.cpp",
            "src/sql/engine/table/ob_ddl_block_sample_scan_op.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_vector_base_0",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_char_length.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_vector_cmp_0",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_sign.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_vector_continuous_0",
        language = "c++",
        srcs = [
            "src/sql/engine/expr/ob_expr_st_centroid.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_vector_discrete_0",
        language = "c++",
        srcs = [
            "src/sql/engine/vector/ob_discrete_base.cpp",
            "src/sql/engine/ob_sql_memory_manager.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_vector_fixed_0",
        language = "c++",
        srcs = [
            "src/sql/engine/vector/ob_fixed_length_base.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_engine_vector_uniform_0",
        language = "c++",
        srcs = [
            "src/sql/engine/vector/ob_uniform_base.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_executor_0",
        language = "c++",
        srcs = [
            "src/sql/executor/ob_cmd_executor.cpp",
            "src/sql/executor/ob_execute_result.cpp",
            "src/sql/executor/ob_executor.cpp",
            "src/sql/executor/ob_maintain_dependency_info_task.cpp",
            "src/sql/executor/ob_sql_executor_ctx.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_executor_1",
        language = "c++",
        srcs = [
            "src/sql/executor/ob_memory_tracker.cpp",
            "src/sql/executor/ob_memory_tracker_wrapper.cpp",
            "src/sql/executor/ob_worker_session_guard.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_hybrid_search_0",
        language = "c++",
        srcs = [
            "src/sql/hybrid_search/ob_query_parse.cpp",
            "src/sql/hybrid_search/ob_request_base.cpp",
            "src/sql/hybrid_search/ob_query_request.cpp",
            "src/sql/hybrid_search/ob_query_translator.cpp",
            "src/sql/hybrid_search/ob_hybrid_search_executor.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_monitor_0",
        language = "c++",
        srcs = [
            "src/sql/monitor/ob_exec_stat_collector.cpp",
            "src/sql/monitor/ob_monitor_node.cpp",
            "src/sql/monitor/ob_phy_operator_stats.cpp",
            "src/sql/monitor/show_trace/ob_show_trace.cpp",
            "src/sql/monitor/ob_sql_plan.cpp",
            "src/sql/monitor/ob_plan_info_manager.cpp",
            "src/sql/monitor/ob_sql_stat_record.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_optimizer_0",
        language = "c++",
        srcs = [
            "src/sql/optimizer/ob_access_path_estimation.cpp",
            "src/sql/optimizer/ob_conflict_detector.cpp",
            "src/sql/optimizer/ob_del_upd_log_plan.cpp",
            "src/sql/optimizer/ob_delete_log_plan.cpp",
            "src/sql/optimizer/ob_explain_log_plan.cpp",
            "src/sql/optimizer/ob_fd_item.cpp",
            "src/sql/optimizer/ob_index_info_cache.cpp",
            "src/sql/optimizer/ob_insert_log_plan.cpp",
            "src/sql/optimizer/ob_join_order.cpp",
            "src/sql/optimizer/ob_log_del_upd.cpp",
            "src/sql/optimizer/ob_log_delete.cpp",
            "src/sql/optimizer/ob_log_distinct.cpp",
            "src/sql/optimizer/ob_log_exchange.cpp",
            "src/sql/optimizer/ob_log_expr_values.cpp",
            "src/sql/optimizer/ob_log_for_update.cpp",
            "src/sql/optimizer/ob_log_function_table.cpp",
            "src/sql/optimizer/ob_log_granule_iterator.cpp",
            "src/sql/optimizer/ob_log_group_by.cpp",
            "src/sql/optimizer/ob_log_insert.cpp",
            "src/sql/optimizer/ob_log_join.cpp",
            "src/sql/optimizer/ob_log_join_filter.cpp",
            "src/sql/optimizer/ob_log_json_table.cpp",
            "src/sql/optimizer/ob_log_limit.cpp",
            "src/sql/optimizer/ob_log_material.cpp",
            "src/sql/optimizer/ob_log_monitoring_dump.cpp",
            "src/sql/optimizer/ob_log_operator_factory.cpp",
            "src/sql/optimizer/ob_log_plan.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_optimizer_1",
        language = "c++",
        srcs = [
            "src/sql/optimizer/graph_feedback_loop_log_op.cpp",
            "src/sql/optimizer/ob_log_plan_factory.cpp",
            "src/sql/optimizer/ob_log_select_into.cpp",
            "src/sql/optimizer/ob_log_set.cpp",
            "src/sql/optimizer/ob_log_sort.cpp",
            "src/sql/optimizer/ob_log_subplan_filter.cpp",
            "src/sql/optimizer/ob_log_subplan_scan.cpp",
            "src/sql/optimizer/ob_log_table_scan.cpp",
            "src/sql/optimizer/ob_log_temp_table_access.cpp",
            "src/sql/optimizer/ob_log_temp_table_insert.cpp",
            "src/sql/optimizer/ob_log_temp_table_transformation.cpp",
            "src/sql/optimizer/ob_log_topk.cpp",
            "src/sql/optimizer/ob_log_update.cpp",
            "src/sql/optimizer/ob_log_window_function.cpp",
            "src/sql/optimizer/ob_logical_operator.cpp",
            "src/sql/optimizer/ob_opt_est_cost.cpp",
            "src/sql/optimizer/ob_opt_est_cost_model.cpp",
            "src/sql/optimizer/ob_opt_est_cost_model_vector.cpp",
            "src/sql/optimizer/ob_opt_cost_model_parameter.cpp",
            "src/sql/optimizer/ob_opt_est_utils.cpp",
            "src/sql/optimizer/ob_opt_selectivity.cpp",
            "src/sql/optimizer/ob_optimizer.cpp",
            "src/sql/optimizer/ob_optimizer_util.cpp",
            "src/sql/optimizer/ob_phy_table_location_info.cpp",
            "src/sql/optimizer/ob_pwj_comparer.cpp",
            "src/sql/optimizer/ob_px_resource_analyzer.cpp",
            "src/sql/optimizer/ob_raw_expr_add_to_context.cpp",
            "src/sql/optimizer/ob_raw_expr_check_dep.cpp",
            "src/sql/optimizer/ob_raw_expr_get_hash_value.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_optimizer_2",
        language = "c++",
        srcs = [
            "src/sql/optimizer/ob_sel_estimator.cpp",
            "src/sql/optimizer/ob_select_log_plan.cpp",
            "src/sql/optimizer/ob_sharding_info.cpp",
            "src/sql/optimizer/ob_skyline_prunning.cpp",
            "src/sql/optimizer/ob_storage_estimator.cpp",
            "src/sql/optimizer/ob_table_location.cpp",
            "src/sql/optimizer/ob_table_partition_info.cpp",
            "src/sql/optimizer/ob_update_log_plan.cpp",
            "src/sql/optimizer/ob_log_stat_collector.cpp",
            "src/sql/optimizer/ob_log_optimizer_stats_gathering.cpp",
            "src/sql/optimizer/ob_dynamic_sampling.cpp",
            "src/sql/optimizer/ob_log_values_table_access.cpp",
            "src/sql/optimizer/ob_log_expand.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_optimizer_stat_0",
        language = "c++",
        srcs = [
            "src/sql/optimizer/stat/ob_basic_stats_estimator.cpp",
            "src/sql/optimizer/stat/ob_dbms_stats_copy_table_stats.cpp",
            "src/sql/optimizer/stat/ob_dbms_stats_executor.cpp",
            "src/sql/optimizer/stat/ob_dbms_stats_export_import.cpp",
            "src/sql/optimizer/stat/ob_dbms_stats_gather.cpp",
            "src/sql/optimizer/stat/ob_dbms_stats_history_manager.cpp",
            "src/sql/optimizer/stat/ob_dbms_stats_lock_unlock.cpp",
            "src/sql/optimizer/stat/ob_dbms_stats_maintenance_window.cpp",
            "src/sql/optimizer/stat/ob_dbms_stats_preferences.cpp",
            "src/sql/optimizer/stat/ob_dbms_stats_utils.cpp",
            "src/sql/optimizer/stat/ob_hybrid_hist_estimator.cpp",
            "src/sql/optimizer/stat/ob_incremental_stat_estimator.cpp",
            "src/sql/optimizer/stat/ob_index_stats_estimator.cpp",
            "src/sql/optimizer/stat/ob_min_max_estimator.cpp",
            "src/sql/optimizer/stat/ob_opt_column_stat.cpp",
            "src/sql/optimizer/stat/ob_opt_column_stat_cache.cpp",
            "src/sql/optimizer/stat/ob_opt_ds_stat.cpp",
            "src/sql/optimizer/stat/ob_opt_ds_stat_cache.cpp",
            "src/sql/optimizer/stat/ob_opt_osg_column_stat.cpp",
            "src/sql/optimizer/stat/ob_opt_stat_gather_stat.cpp",
            "src/sql/optimizer/stat/ob_opt_stat_manager.cpp",
            "src/sql/optimizer/stat/ob_opt_stat_monitor_manager.cpp",
            "src/sql/optimizer/stat/ob_opt_stat_service.cpp",
            "src/sql/optimizer/stat/ob_opt_stat_sql_service.cpp",
            "src/sql/optimizer/stat/ob_opt_system_stat.cpp",
            "src/sql/optimizer/stat/ob_opt_system_stat_cache.cpp",
            "src/sql/optimizer/stat/ob_opt_table_stat.cpp",
            "src/sql/optimizer/stat/ob_opt_table_stat_cache.cpp",
            "src/sql/optimizer/stat/ob_stat_define.cpp",
            "src/sql/optimizer/stat/ob_stat_item.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_optimizer_stat_1",
        language = "c++",
        srcs = [
            "src/sql/optimizer/stat/ob_stats_estimator.cpp",
            "src/sql/optimizer/stat/ob_topk_hist_estimator.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_plan_cache_0",
        language = "c++",
        srcs = [
            "src/sql/plan_cache/ob_cache_object.cpp",
            "src/sql/plan_cache/ob_cache_object_factory.cpp",
            "src/sql/plan_cache/ob_dist_plans.cpp",
            "src/sql/plan_cache/ob_id_manager_allocator.cpp",
            "src/sql/plan_cache/ob_pcv_set.cpp",
            "src/sql/plan_cache/ob_plan_cache.cpp",
            "src/sql/plan_cache/ob_plan_cache_callback.cpp",
            "src/sql/plan_cache/ob_plan_cache_util.cpp",
            "src/sql/plan_cache/ob_plan_cache_value.cpp",
            "src/sql/plan_cache/ob_plan_set.cpp",
            "src/sql/plan_cache/ob_param_value_formatter.cpp",
            "src/sql/plan_cache/ob_prepare_stmt_struct.cpp",
            "src/sql/plan_cache/ob_ps_cache.cpp",
            "src/sql/plan_cache/ob_ps_cache_callback.cpp",
            "src/sql/plan_cache/ob_ps_sql_utils.cpp",
            "src/sql/plan_cache/ob_sql_parameterization.cpp",
            "src/sql/plan_cache/ob_i_lib_cache_node.cpp",
            "src/sql/plan_cache/ob_i_lib_cache_object.cpp",
            "src/sql/plan_cache/ob_lib_cache_key_creator.cpp",
            "src/sql/plan_cache/ob_lib_cache_register.cpp",
            "src/sql/plan_cache/ob_lib_cache_object_manager.cpp",
            "src/sql/plan_cache/ob_lib_cache_node_factory.cpp",
            "src/sql/plan_cache/ob_plan_match_helper.cpp",
            "src/sql/plan_cache/ob_values_table_compression.cpp",
            "src/sql/plan_cache/ob_adaptive_auto_dop.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_printer_0",
        language = "c++",
        srcs = [
            "src/sql/printer/ob_delete_stmt_printer.cpp",
            "src/sql/printer/ob_dml_stmt_printer.cpp",
            "src/sql/printer/ob_insert_stmt_printer.cpp",
            "src/sql/printer/ob_raw_expr_printer.cpp",
            "src/sql/printer/ob_select_stmt_printer.cpp",
            "src/sql/printer/ob_update_stmt_printer.cpp",
            "src/sql/printer/ob_schema_printer.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_resolver_0",
        language = "c++",
        srcs = [
            "src/sql/resolver/ob_resolver.cpp",
            "src/sql/resolver/ob_resolver_utils.cpp",
            "src/sql/resolver/ob_schema_checker.cpp",
            "src/sql/resolver/ob_stmt.cpp",
            "src/sql/resolver/ob_stmt_resolver.cpp",
            "src/sql/resolver/tcl/ob_end_trans_resolver.cpp",
            "src/sql/resolver/tcl/ob_savepoint_resolver.cpp",
            "src/sql/resolver/tcl/ob_savepoint_stmt.cpp",
            "src/sql/resolver/tcl/ob_start_trans_resolver.cpp",
            "src/sql/resolver/tcl/ob_tcl_resolver.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_resolver_cmd_0",
        language = "c++",
        srcs = [
            "src/sql/resolver/cmd/ob_alter_system_resolver.cpp",
            "src/sql/resolver/cmd/ob_anonymous_block_resolver.cpp",
            "src/sql/resolver/cmd/ob_anonymous_block_stmt.cpp",
            "src/sql/resolver/cmd/ob_call_procedure_resolver.cpp",
            "src/sql/resolver/cmd/ob_call_procedure_stmt.cpp",
            "src/sql/resolver/cmd/ob_empty_query_resolver.cpp",
            "src/sql/resolver/cmd/ob_get_diagnostics_resolver.cpp",
            "src/sql/resolver/cmd/ob_get_diagnostics_stmt.cpp",
            "src/sql/resolver/cmd/ob_kill_resolver.cpp",
            "src/sql/resolver/cmd/ob_load_data_resolver.cpp",
            "src/sql/resolver/cmd/ob_load_data_stmt.cpp",
            "src/sql/resolver/cmd/ob_set_names_resolver.cpp",
            "src/sql/resolver/cmd/ob_set_transaction_resolver.cpp",
            "src/sql/resolver/cmd/ob_show_resolver.cpp",
            "src/sql/resolver/cmd/ob_diff_table_resolver.cpp",
            "src/sql/resolver/cmd/ob_merge_table_resolver.cpp",
            "src/sql/resolver/cmd/ob_variable_set_resolver.cpp",
            "src/sql/resolver/cmd/ob_variable_set_stmt.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_resolver_dcl_0",
        language = "c++",
        srcs = [
            "src/sql/resolver/dcl/ob_alter_role_resolver.cpp",
            "src/sql/resolver/dcl/ob_alter_role_stmt.cpp",
            "src/sql/resolver/dcl/ob_create_role_resolver.cpp",
            "src/sql/resolver/dcl/ob_create_role_stmt.cpp",
            "src/sql/resolver/dcl/ob_create_user_resolver.cpp",
            "src/sql/resolver/dcl/ob_create_user_stmt.cpp",
            "src/sql/resolver/dcl/ob_dcl_resolver.cpp",
            "src/sql/resolver/dcl/ob_drop_role_resolver.cpp",
            "src/sql/resolver/dcl/ob_drop_role_stmt.cpp",
            "src/sql/resolver/dcl/ob_drop_user_resolver.cpp",
            "src/sql/resolver/dcl/ob_drop_user_stmt.cpp",
            "src/sql/resolver/dcl/ob_grant_resolver.cpp",
            "src/sql/resolver/dcl/ob_grant_stmt.cpp",
            "src/sql/resolver/dcl/ob_lock_user_resolver.cpp",
            "src/sql/resolver/dcl/ob_lock_user_stmt.cpp",
            "src/sql/resolver/dcl/ob_rename_user_resolver.cpp",
            "src/sql/resolver/dcl/ob_rename_user_stmt.cpp",
            "src/sql/resolver/dcl/ob_revoke_resolver.cpp",
            "src/sql/resolver/dcl/ob_revoke_stmt.cpp",
            "src/sql/resolver/dcl/ob_set_password_resolver.cpp",
            "src/sql/resolver/dcl/ob_set_password_stmt.cpp",
            "src/sql/resolver/dcl/ob_alter_user_role_resolver.cpp",
            "src/sql/resolver/dcl/ob_alter_user_role_stmt.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_resolver_ddl_0",
        language = "c++",
        srcs = [
            "src/sql/resolver/ddl/ob_fts_index_builder_util.cpp",
            "src/sql/resolver/ddl/ob_vec_index_builder_util.cpp",
            "src/sql/resolver/ddl/ob_index_builder_util.cpp",
            "src/sql/resolver/ddl/ob_alter_database_resolver.cpp",
            "src/sql/resolver/ddl/ob_alter_database_stmt.cpp",
            "src/sql/resolver/ddl/ob_alter_outline_resolver.cpp",
            "src/sql/resolver/ddl/ob_alter_routine_resolver.cpp",
            "src/sql/resolver/ddl/ob_alter_table_resolver.cpp",
            "src/sql/resolver/ddl/ob_alter_table_stmt.cpp",
            "src/sql/resolver/ddl/ob_analyze_stmt.cpp",
            "src/sql/resolver/ddl/ob_analyze_stmt_resolver.cpp",
            "src/sql/resolver/ddl/ob_create_database_resolver.cpp",
            "src/sql/resolver/ddl/ob_create_database_stmt.cpp",
            "src/sql/resolver/ddl/ob_create_index_resolver.cpp",
            "src/sql/resolver/ddl/ob_create_index_stmt.cpp",
            "src/sql/resolver/ddl/ob_create_outline_resolver.cpp",
            "src/sql/resolver/ddl/ob_create_package_resolver.cpp",
            "src/sql/resolver/ddl/ob_create_routine_resolver.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_resolver_ddl_1",
        language = "c++",
        srcs = [
            "src/sql/resolver/ddl/ob_create_table_like_resolver.cpp",
            "src/sql/resolver/ddl/ob_create_table_like_stmt.cpp",
            "src/sql/resolver/ddl/ob_create_table_resolver.cpp",
            "src/sql/resolver/ddl/ob_create_table_resolver_base.cpp",
            "src/sql/resolver/ddl/ob_create_table_stmt.cpp",
            "src/sql/resolver/ddl/ob_create_view_resolver.cpp",
            "src/sql/resolver/ddl/ob_ddl_resolver.cpp",
            "src/sql/resolver/ddl/ob_ddl_stmt.cpp",
            "src/sql/resolver/ddl/ob_drop_database_resolver.cpp",
            "src/sql/resolver/ddl/ob_drop_index_resolver.cpp",
            "src/sql/resolver/ddl/ob_drop_index_stmt.cpp",
            "src/sql/resolver/ddl/ob_drop_outline_resolver.cpp",
            "src/sql/resolver/ddl/ob_drop_package_resolver.cpp",
            "src/sql/resolver/ddl/ob_drop_routine_resolver.cpp",
            "src/sql/resolver/ddl/ob_drop_table_resolver.cpp",
            "src/sql/resolver/ddl/ob_drop_table_stmt.cpp",
            "src/sql/resolver/ddl/ob_explain_resolver.cpp",
            "src/sql/resolver/ddl/ob_explain_stmt.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_resolver_ddl_2",
        language = "c++",
        srcs = [
            "src/sql/resolver/ddl/ob_recyclebin_restore_resolver.cpp",
            "src/sql/resolver/ddl/ob_fork_table_resolver.cpp",
            "src/sql/resolver/ddl/ob_fork_table_stmt.cpp",
            "src/sql/resolver/ddl/ob_fork_database_resolver.cpp",
            "src/sql/resolver/ddl/graph_ddl_resolver.cpp",
            "src/sql/resolver/ddl/ob_fork_database_stmt.cpp",
            "src/sql/resolver/ddl/ob_lock_table_resolver.cpp",
            "src/sql/resolver/ddl/ob_lock_table_stmt.cpp",
            "src/sql/resolver/ddl/ob_optimize_resolver.cpp",
            "src/sql/resolver/ddl/ob_optimize_stmt.cpp",
            "src/sql/resolver/ddl/ob_outline_resolver.cpp",
            "src/sql/resolver/ddl/ob_purge_resolver.cpp",
            "src/sql/resolver/ddl/ob_rename_table_resolver.cpp",
            "src/sql/resolver/ddl/ob_rename_table_stmt.cpp",
            "src/sql/resolver/ddl/ob_set_comment_resolver.cpp",
            "src/sql/resolver/ddl/ob_trigger_resolver.cpp",
            "src/sql/resolver/ddl/ob_trigger_stmt.cpp",
            "src/sql/resolver/ddl/ob_truncate_table_resolver.cpp",
            "src/sql/resolver/ddl/ob_truncate_table_stmt.cpp",
            "src/sql/resolver/ddl/ob_use_database_resolver.cpp",
            "src/sql/resolver/ddl/ob_fts_parser_resolver.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_resolver_dml_0",
        language = "c++",
        srcs = [
            "src/sql/resolver/dml/ob_aggr_expr_push_up_analyzer.cpp",
            "src/sql/resolver/dml/ob_column_namespace_checker.cpp",
            "src/sql/resolver/dml/ob_default_value_utils.cpp",
            "src/sql/resolver/dml/ob_del_upd_resolver.cpp",
            "src/sql/resolver/dml/ob_del_upd_stmt.cpp",
            "src/sql/resolver/dml/ob_delete_resolver.cpp",
            "src/sql/resolver/dml/ob_delete_stmt.cpp",
            "src/sql/resolver/dml/ob_dml_resolver.cpp",
            "src/sql/resolver/dml/graph_table_resolver.cpp",
            "src/sql/resolver/dml/graph_show_resolver.cpp",
            "src/sql/resolver/dml/ob_dml_stmt.cpp",
            "src/sql/resolver/dml/ob_group_by_checker.cpp",
            "src/sql/resolver/dml/ob_insert_resolver.cpp",
            "src/sql/resolver/dml/ob_insert_stmt.cpp",
            "src/sql/resolver/dml/ob_raw_expr_sets.cpp",
            "src/sql/resolver/dml/ob_select_resolver.cpp",
            "src/sql/resolver/dml/ob_select_stmt.cpp",
            "src/sql/resolver/dml/ob_sql_hint.cpp",
            "src/sql/resolver/dml/ob_stmt_expr_visitor.cpp",
            "src/sql/resolver/dml/ob_hint.cpp",
            "src/sql/resolver/dml/ob_standard_group_checker.cpp",
            "src/sql/resolver/dml/ob_update_resolver.cpp",
            "src/sql/resolver/dml/ob_update_stmt.cpp",
            "src/sql/resolver/dml/ob_view_table_resolver.cpp",
            "src/sql/resolver/dml/ob_inlist_resolver.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_resolver_expr_0",
        language = "c++",
        srcs = [
            "src/sql/resolver/expr/ob_expr_relation_analyzer.cpp",
            "src/sql/resolver/expr/ob_raw_expr.cpp",
            "src/sql/resolver/expr/ob_raw_expr_copier.cpp",
            "src/sql/resolver/expr/ob_raw_expr_deduce_type.cpp",
            "src/sql/resolver/expr/ob_raw_expr_info_extractor.cpp",
            "src/sql/resolver/expr/ob_raw_expr_modify_column_name.cpp",
            "src/sql/resolver/expr/ob_raw_expr_part_expr_checker.cpp",
            "src/sql/resolver/expr/ob_raw_expr_part_func_checker.cpp",
            "src/sql/resolver/expr/ob_raw_expr_print_visitor.cpp",
            "src/sql/resolver/expr/ob_raw_expr_replacer.cpp",
            "src/sql/resolver/expr/ob_raw_expr_resolver_impl.cpp",
            "src/sql/resolver/expr/ob_raw_expr_util.cpp",
            "src/sql/resolver/expr/ob_raw_expr_wrap_enum_set.cpp",
            "src/sql/resolver/expr/ob_shared_expr_resolver.cpp",
            "src/sql/resolver/expr/ob_raw_expr_type_demotion.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_resolver_prepare_0",
        language = "c++",
        srcs = [
            "src/sql/resolver/prepare/ob_deallocate_resolver.cpp",
            "src/sql/resolver/prepare/ob_deallocate_stmt.cpp",
            "src/sql/resolver/prepare/ob_execute_resolver.cpp",
            "src/sql/resolver/prepare/ob_execute_stmt.cpp",
            "src/sql/resolver/prepare/ob_prepare_resolver.cpp",
            "src/sql/resolver/prepare/ob_prepare_stmt.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_rewrite_0",
        language = "c++",
        srcs = [
            "src/sql/rewrite/ob_equal_analysis.cpp",
            "src/sql/rewrite/ob_expand_aggregate_utils.cpp",
            "src/sql/rewrite/ob_key_part.cpp",
            "src/sql/rewrite/ob_predicate_deduce.cpp",
            "src/sql/rewrite/ob_expr_range_converter.cpp",
            "src/sql/rewrite/ob_query_range_define.cpp",
            "src/sql/rewrite/ob_range_generator.cpp",
            "src/sql/rewrite/ob_range_graph_generator.cpp",
            "src/sql/rewrite/ob_stmt_comparer.cpp",
            "src/sql/rewrite/ob_transform_count_to_exists.cpp",
            "src/sql/rewrite/ob_transform_aggr_subquery.cpp",
            "src/sql/rewrite/ob_transform_min_max.cpp",
            "src/sql/rewrite/ob_transform_const_propagate.cpp",
            "src/sql/rewrite/ob_transform_eliminate_outer_join.cpp",
            "src/sql/rewrite/ob_transform_groupby_pullup.cpp",
            "src/sql/rewrite/ob_transform_groupby_pushdown.cpp",
            "src/sql/rewrite/ob_transform_join_elimination.cpp",
            "src/sql/rewrite/ob_transform_left_join_to_anti.cpp",
            "src/sql/rewrite/ob_transform_or_expansion.cpp",
            "src/sql/rewrite/ob_transform_join_limit_pushdown.cpp",
            "src/sql/rewrite/ob_transform_pre_process.cpp",
            "src/sql/rewrite/ob_transform_predicate_move_around.cpp",
            "src/sql/rewrite/ob_transform_project_pruning.cpp",
            "src/sql/rewrite/ob_transform_query_push_down.cpp",
            "src/sql/rewrite/ob_transform_rule.cpp",
            "src/sql/rewrite/ob_transform_semi_to_inner.cpp",
            "src/sql/rewrite/ob_transform_simplify_distinct.cpp",
            "src/sql/rewrite/ob_transform_simplify_expr.cpp",
            "src/sql/rewrite/ob_transform_simplify_groupby.cpp",
            "src/sql/rewrite/ob_transform_simplify_limit.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_rewrite_1",
        language = "c++",
        srcs = [
            "src/sql/rewrite/ob_transform_simplify_orderby.cpp",
            "src/sql/rewrite/ob_transform_simplify_set.cpp",
            "src/sql/rewrite/ob_transform_simplify_subquery.cpp",
            "src/sql/rewrite/ob_transform_simplify_winfunc.cpp",
            "src/sql/rewrite/ob_transform_subquery_coalesce.cpp",
            "src/sql/rewrite/ob_transform_temp_table.cpp",
            "src/sql/rewrite/ob_transform_utils.cpp",
            "src/sql/rewrite/ob_transform_view_merge.cpp",
            "src/sql/rewrite/ob_transform_where_subquery_pullup.cpp",
            "src/sql/rewrite/ob_transform_win_magic.cpp",
            "src/sql/rewrite/ob_transform_expr_pullup.cpp",
            "src/sql/rewrite/ob_transformer_impl.cpp",
            "src/sql/rewrite/ob_transform_conditional_aggr_coalesce.cpp",
            "src/sql/rewrite/ob_union_find.cpp",
            "src/sql/rewrite/ob_transform_decorrelate.cpp",
            "src/sql/rewrite/ob_transform_late_materialization.cpp",
            "src/sql/rewrite/ob_transform_distinct_aggregate.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_session_0",
        language = "c++",
        srcs = [
            "src/sql/session/ob_basic_session_info.cpp",
            "src/sql/session/ob_piece_cache.cpp",
            "src/sql/session/ob_session_val_map.cpp",
            "src/sql/session/ob_sql_session_info.cpp",
            "src/sql/session/ob_sql_session_mgr.cpp",
            "src/sql/session/ob_sys_params_mgr.cpp",
            "src/sql/session/ob_user_resource_mgr.cpp",
            "src/sql/session/ob_local_session_var.cpp",
            "src/sql/session/ob_system_variable.cpp",
            "src/sql/session/ob_system_variable_factory.cpp",
            "src/sql/session/ob_session_inner_sql.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_sql_tablelock_0",
        language = "c++",
        srcs = [
            "src/sql/tablelock/ob_lock_executor.cpp",
            "src/sql/tablelock/ob_lock_func_executor.cpp",
            "src/sql/tablelock/ob_mysql_lock_table_executor.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
]

SQL_SIMD_UNITY_GROUPS = [
    struct(
        name = "ob_sql_simd_common_0",
        language = "c++",
        srcs = [
            "src/sql/engine/basic/ob_pushdown_filter_simd.cpp",
            "src/sql/engine/basic/ob_byte_compare_simd.cpp",
            "src/sql/engine/px/ob_px_bloom_filter_simd.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
]

SQL_STANDALONE_SOURCES = [
    struct(path = "src/sql/engine/aggregate/ob_aggregate_processor.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_add.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_array_sort.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_in.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_mul.cpp", language = "c++", kind = "source"),
]

SQL_EXTRA_SOURCES = [
    struct(path = "src/sql/engine/expr/ob_datum_cast.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_obj_cast_runtime.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_cmp_func.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_cmp_func_compile/ob_expr_cmp_func_compile_init.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_cmp_func_compile/ob_expr_cmp_func_part0.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_cmp_func_compile/ob_expr_cmp_func_part1.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_cmp_func_compile/ob_expr_cmp_func_part2.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_cmp_func_compile/ob_expr_cmp_func_part3.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_cmp_func_compile/ob_expr_cmp_func_part4.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_cmp_func_compile/ob_expr_cmp_func_part5.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_cmp_func_compile/ob_expr_cmp_func_part6.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_cmp_func_compile/ob_expr_cmp_func_part7.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_str_cmp_func_compile/ob_expr_str_cmp_func_all.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_str_cmp_func_compile/ob_expr_str_cmp_func_part_0.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_str_cmp_func_compile/ob_expr_str_cmp_func_part_1.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_str_cmp_func_compile/ob_expr_str_cmp_func_part_2.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_str_cmp_func_compile/ob_expr_str_cmp_func_part_3.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_str_cmp_func_compile/ob_expr_str_cmp_func_part_4.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_str_cmp_func_compile/ob_expr_str_cmp_func_part_5.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_str_cmp_func_compile/ob_expr_str_cmp_func_part_6.cpp", language = "c++", kind = "source"),
    struct(path = "src/sql/engine/expr/ob_expr_str_cmp_func_compile/ob_expr_str_cmp_func_part_7.cpp", language = "c++", kind = "source"),
]

SQL_PARSER_SOURCES = [
    "src/sql/parser/fts_base.c",
    "src/sql/parser/fts_parse.c",
    "src/sql/parser/non_reserved_keywords_mysql_mode.c",
    "src/sql/parser/ob_fast_parser.cpp",
    "src/sql/parser/ob_memory_tracker_wrapper.cpp",
    "src/sql/parser/ob_non_reserved_keywords.c",
    "src/sql/parser/ob_parse_simd.cpp",
    "src/sql/parser/ob_parser.cpp",
    "src/sql/parser/ob_parser_charset_utils.cpp",
    "src/sql/parser/ob_sql_parser.cpp",
    "src/sql/parser/parse_malloc.cpp",
    "src/sql/parser/parse_node.c",
    "src/sql/parser/parse_node_hash.cpp",
    "src/sql/parser/parser_utility.cpp",
    "src/sql/parser/sql_parser_base.c",
]
