"""Generated source inventory for Storage."""

STORAGE_TABLET_AUTOINCREMENT_STATE_SOURCES = [
    "tablet/ob_tablet_autoincrement_state.cpp",
]

STORAGE_UNITY_GROUPS = [
    struct(
        name = "ob_storage_access_0",
        language = "c++",
        srcs = [
            "src/storage/access/ob_data_access_retry.cpp",
            "src/storage/access/ob_datum_reshape.cpp",
            "src/storage/access/ob_table_estimator.cpp",
            "src/storage/access/ob_index_sstable_estimator.cpp",
            "src/storage/access/ob_sstable_multi_version_row_iterator.cpp",
            "src/storage/access/ob_sstable_row_getter.cpp",
            "src/storage/access/ob_sstable_row_lock_checker.cpp",
            "src/storage/access/ob_sstable_row_multi_getter.cpp",
            "src/storage/access/ob_sstable_row_multi_scanner.cpp",
            "src/storage/access/ob_sstable_row_whole_scanner.cpp",
            "src/storage/access/ob_block_batched_row_store.cpp",
            "src/storage/access/ob_block_row_store.cpp",
            "src/storage/access/ob_vector_store.cpp",
            "src/storage/access/ob_aggregated_store.cpp",
            "src/storage/access/ob_scan_merge_loser_tree.cpp",
            "src/storage/access/ob_single_merge.cpp",
            "src/storage/access/ob_sstable_index_filter.cpp",
            "src/storage/access/ob_multiple_get_merge.cpp",
            "src/storage/access/ob_multiple_merge.cpp",
            "src/storage/access/ob_multiple_multi_scan_merge.cpp",
            "src/storage/access/ob_multiple_scan_merge.cpp",
            "src/storage/access/ob_table_scan_iterator.cpp",
            "src/storage/access/ob_store_row_iterator.cpp",
            "src/storage/access/ob_i_sample_iterator.cpp",
            "src/storage/access/ob_block_sample_iterator.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_access_1",
        language = "c++",
        srcs = [
            "src/storage/access/ob_ddl_block_sample_iterator.cpp",
            "src/storage/access/ob_row_sample_iterator.cpp",
            "src/storage/access/ob_rows_info.cpp",
            "src/storage/access/ob_sample_iter_helper.cpp",
            "src/storage/access/ob_table_read_info.cpp",
            "src/storage/access/ob_table_param.cpp",
            "src/storage/access/ob_sample_filter.cpp",
            "src/storage/access/ob_table_scan_range.cpp",
            "src/storage/access/ob_table_access_param.cpp",
            "src/storage/access/ob_table_access_context.cpp",
            "src/storage/access/ob_fuse_row_cache_fetcher.cpp",
            "src/storage/access/ob_dml_param.cpp",
            "src/storage/access/ob_micro_block_handle_mgr.cpp",
            "src/storage/access/ob_aggregate_base.cpp",
            "src/storage/access/ob_pushdown_aggregate_input.cpp",
            "src/storage/access/ob_pushdown_aggregate.cpp",
            "src/storage/access/ob_empty_read_bucket.cpp",
            "src/storage/access/ob_global_iterator_pool.cpp",
            "src/storage/access/ob_where_optimizer.cpp",
            "src/storage/access/ob_advance_scan_helper.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_allocator_0",
        language = "c++",
        srcs = [
            "src/storage/allocator/ob_fifo_arena.cpp",
            "src/storage/allocator/ob_memstore_allocator.cpp",
            "src/storage/allocator/ob_handle_list.cpp",
            "src/storage/allocator/ob_mds_allocator.cpp",
            "src/storage/allocator/ob_shared_memory_allocator_mgr.cpp",
            "src/storage/allocator/ob_tx_data_allocator.cpp",
            "src/storage/allocator/ob_vector_allocator.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_blocksstable_0",
        language = "c++",
        srcs = [
            "src/storage/blocksstable/ob_kvcache_pointer_swizzle.cpp",
            "src/storage/blocksstable/ob_kvcache_pre_warmer.cpp",
            "src/storage/blocksstable/ob_block_manager.cpp",
            "src/storage/blocksstable/ob_macro_seq_generator.cpp",
            "src/storage/blocksstable/ob_object_manager.cpp",
            "src/storage/blocksstable/ob_block_sstable_struct.cpp",
            "src/storage/blocksstable/ob_bloom_filter_cache.cpp",
            "src/storage/blocksstable/ob_data_buffer.cpp",
            "src/storage/blocksstable/ob_fuse_row_cache.cpp",
            "src/storage/blocksstable/ob_imicro_block_reader.cpp",
            "src/storage/blocksstable/ob_imicro_block_writer.cpp",
            "src/storage/blocksstable/ob_micro_block_header.cpp",
            "src/storage/blocksstable/ob_macro_block.cpp",
            "src/storage/blocksstable/ob_macro_block_bare_iterator.cpp",
            "src/storage/blocksstable/ob_macro_block_checker.cpp",
            "src/storage/blocksstable/ob_macro_block_common_header.cpp",
            "src/storage/blocksstable/ob_macro_block_flusher.cpp",
            "src/storage/blocksstable/ob_macro_block_handle.cpp",
            "src/storage/blocksstable/ob_macro_block_id.cpp",
            "src/storage/blocksstable/ob_macro_block_meta_mgr.cpp",
            "src/storage/blocksstable/ob_macro_block_meta.cpp",
            "src/storage/blocksstable/ob_macro_block_reader.cpp",
            "src/storage/blocksstable/ob_macro_block_struct.cpp",
            "src/storage/blocksstable/ob_macro_block_writer.cpp",
            "src/storage/blocksstable/ob_block_writer_concurrent_guard.cpp",
            "src/storage/blocksstable/ob_data_macro_block_merge_writer.cpp",
            "src/storage/blocksstable/ob_micro_block_cache.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_blocksstable_1",
        language = "c++",
        srcs = [
            "src/storage/blocksstable/ob_micro_block_checksum_helper.cpp",
            "src/storage/blocksstable/ob_micro_block_hash_index.cpp",
            "src/storage/blocksstable/ob_micro_block_reader.cpp",
            "src/storage/blocksstable/ob_micro_block_row_getter.cpp",
            "src/storage/blocksstable/ob_micro_block_row_lock_checker.cpp",
            "src/storage/blocksstable/ob_micro_block_row_scanner.cpp",
            "src/storage/blocksstable/ob_micro_block_writer.cpp",
            "src/storage/blocksstable/ob_storage_object_handle.cpp",
            "src/storage/blocksstable/ob_row_cache.cpp",
            "src/storage/blocksstable/ob_row_queue.cpp",
            "src/storage/blocksstable/ob_row_reader.cpp",
            "src/storage/blocksstable/ob_row_writer.cpp",
            "src/storage/blocksstable/ob_shared_macro_block_manager.cpp",
            "src/storage/blocksstable/ob_sstable.cpp",
            "src/storage/blocksstable/ob_sstable_macro_block_header.cpp",
            "src/storage/blocksstable/ob_simplified_sstable_macro_block_header.cpp",
            "src/storage/blocksstable/ob_sstable_meta.cpp",
            "src/storage/blocksstable/ob_logic_macro_id.cpp",
            "src/storage/blocksstable/ob_sstable_printer.cpp",
            "src/storage/blocksstable/ob_storage_cache_suite.cpp",
            "src/storage/blocksstable/ob_super_block_buffer_holder.cpp",
            "src/storage/blocksstable/ob_storage_datum.cpp",
            "src/storage/blocksstable/ob_datum_row.cpp",
            "src/storage/blocksstable/ob_datum_rowkey.cpp",
            "src/storage/blocksstable/ob_datum_row_store.cpp",
            "src/storage/blocksstable/ob_datum_row_utils.cpp",
            "src/storage/blocksstable/ob_data_store_desc.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_blocksstable_2",
        language = "c++",
        srcs = [
            "src/storage/blocksstable/ob_column_checksum_struct.cpp",
            "src/storage/blocksstable/ob_datum_rowkey_vector.cpp",
            "src/storage/blocksstable/ob_batch_datum_rows.cpp",
            "src/storage/ob_tablet_stat_mgr.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_blocksstable_encoding1_0",
        language = "c++",
        srcs = [
            "src/storage/blocksstable/encoding/ob_bit_stream.cpp",
            "src/storage/blocksstable/encoding/ob_column_equal_decoder.cpp",
            "src/storage/blocksstable/encoding/ob_column_equal_encoder.cpp",
            "src/storage/blocksstable/encoding/ob_column_datum_iter.cpp",
            "src/storage/blocksstable/encoding/ob_const_decoder.cpp",
            "src/storage/blocksstable/encoding/ob_const_encoder.cpp",
            "src/storage/blocksstable/encoding/ob_dict_decoder.cpp",
            "src/storage/blocksstable/encoding/ob_dict_encoder.cpp",
            "src/storage/blocksstable/encoding/ob_encoding_allocator.cpp",
            "src/storage/blocksstable/encoding/ob_encoding_bitset.cpp",
            "src/storage/blocksstable/encoding/ob_encoding_hash_util.cpp",
            "src/storage/blocksstable/encoding/ob_encoding_util.cpp",
            "src/storage/blocksstable/encoding/ob_hex_string_decoder.cpp",
            "src/storage/blocksstable/encoding/ob_hex_string_encoder.cpp",
            "src/storage/blocksstable/encoding/ob_icolumn_decoder.cpp",
            "src/storage/blocksstable/encoding/ob_icolumn_encoder.cpp",
            "src/storage/blocksstable/encoding/ob_new_column_decoder.cpp",
            "src/storage/blocksstable/encoding/ob_integer_base_diff_decoder.cpp",
            "src/storage/blocksstable/encoding/ob_integer_base_diff_encoder.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_blocksstable_encoding2_0",
        language = "c++",
        srcs = [
            "src/storage/blocksstable/encoding/ob_inter_column_substring_decoder.cpp",
            "src/storage/blocksstable/encoding/ob_inter_column_substring_encoder.cpp",
            "src/storage/blocksstable/encoding/ob_imicro_block_decoder.cpp",
            "src/storage/blocksstable/encoding/ob_micro_block_decoder.cpp",
            "src/storage/blocksstable/encoding/ob_micro_block_encoder.cpp",
            "src/storage/blocksstable/encoding/ob_multi_prefix_tree.cpp",
            "src/storage/blocksstable/encoding/ob_raw_decoder.cpp",
            "src/storage/blocksstable/encoding/ob_raw_encoder.cpp",
            "src/storage/blocksstable/encoding/ob_rle_decoder.cpp",
            "src/storage/blocksstable/encoding/ob_rle_encoder.cpp",
            "src/storage/blocksstable/encoding/ob_string_diff_decoder.cpp",
            "src/storage/blocksstable/encoding/ob_string_diff_encoder.cpp",
            "src/storage/blocksstable/encoding/ob_string_prefix_decoder.cpp",
            "src/storage/blocksstable/encoding/ob_string_prefix_encoder.cpp",
            "src/storage/blocksstable/encoding/neon/ob_dict_decoder_neon.cpp",
            "src/storage/blocksstable/encoding/neon/ob_raw_decoder_neon.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_blocksstable_index_block_0",
        language = "c++",
        srcs = [
            "src/storage/blocksstable/index_block/ob_agg_row_struct.cpp",
            "src/storage/blocksstable/index_block/ob_macro_meta_temp_store.cpp",
            "src/storage/blocksstable/index_block/ob_index_block_aggregator.cpp",
            "src/storage/blocksstable/index_block/ob_index_block_builder.cpp",
            "src/storage/blocksstable/index_block/ob_index_block_macro_iterator.cpp",
            "src/storage/blocksstable/index_block/ob_index_block_dual_meta_iterator.cpp",
            "src/storage/blocksstable/index_block/ob_index_block_dumper.cpp",
            "src/storage/blocksstable/index_block/ob_ddl_sstable_scan_merge.cpp",
            "src/storage/blocksstable/index_block/ob_index_block_row_scanner.cpp",
            "src/storage/blocksstable/index_block/ob_ddl_index_block_row_iterator.cpp",
            "src/storage/blocksstable/index_block/ob_index_block_row_struct.cpp",
            "src/storage/blocksstable/index_block/ob_index_block_tree_cursor.cpp",
            "src/storage/blocksstable/index_block/ob_index_block_util.cpp",
            "src/storage/blocksstable/index_block/ob_skip_index_filter_executor.cpp",
            "src/storage/blocksstable/index_block/ob_sstable_index_scanner.cpp",
            "src/storage/blocksstable/index_block/ob_sstable_meta_info.cpp",
            "src/storage/blocksstable/index_block/ob_sstable_sec_meta_iterator.cpp",
            "src/storage/blocksstable/index_block/ob_clustered_index_block_writer.cpp",
            "src/storage/blocksstable/index_block/ob_index_block_bare_iterator.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_ckpt_0",
        language = "c++",
        srcs = [
            "src/storage/slog_ckpt/ob_linked_macro_block_reader.cpp",
            "src/storage/slog_ckpt/ob_linked_macro_block_struct.cpp",
            "src/storage/slog_ckpt/ob_linked_macro_block_writer.cpp",
            "src/storage/slog_ckpt/ob_server_checkpoint_reader.cpp",
            "src/storage/slog_ckpt/ob_server_checkpoint_slog_handler.cpp",
            "src/storage/slog_ckpt/ob_server_checkpoint_writer.cpp",
            "src/storage/slog_ckpt/ob_startup_accel_task_handler.cpp",
            "src/storage/slog_ckpt/ob_tablet_replay_create_handler.cpp",
            "src/storage/slog_ckpt/ob_local_storage_checkpoint_reader.cpp",
            "src/storage/slog_ckpt/ob_local_storage_checkpoint_slog_handler.cpp",
            "src/storage/slog_ckpt/ob_local_storage_checkpoint_writer.cpp",
            "src/storage/slog_ckpt/ob_server_snapshot_handler.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_common_0",
        language = "c++",
        srcs = [
            "src/storage/ob_storage_rpc_arg.cpp",
            "src/storage/ob_order_perserving_encoder.cpp",
            "src/storage/ob_table_dml_param.cpp",
            "src/storage/ob_i_pre_warmer.cpp",
            "src/storage/ob_tablet_autoincrement_service.cpp",
            "src/storage/ob_row_bitmap.cpp",
            "src/storage/ob_all_micro_block_range_iterator.cpp",
            "src/storage/ob_bloom_filter_task.cpp",
            "src/storage/ob_col_map.cpp",
            "src/storage/ob_disk_usage_reporter.cpp",
            "src/storage/ob_dml_running_ctx.cpp",
            "src/storage/ob_file_system_router.cpp",
            "src/storage/ob_i_memtable_mgr.cpp",
            "src/storage/ob_i_store.cpp",
            "src/storage/ob_i_table.cpp",
            "src/storage/ob_i_tablet_memtable.cpp",
            "src/storage/ob_iter_cache.cpp",
            "src/storage/ob_partition_range_spliter.cpp",
            "src/storage/ob_query_iterator_factory.cpp",
            "src/storage/ob_relative_table.cpp",
            "src/storage/ob_row_fuse.cpp",
            "src/storage/ob_row_reshape.cpp",
            "src/storage/ob_storage_schema.cpp",
            "src/storage/ob_storage_schema_util.cpp",
            "src/storage/ob_storage_schema_recorder.cpp",
            "src/storage/ob_storage_clog_recorder.cpp",
            "src/storage/ob_storage_struct.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_common_1",
        language = "c++",
        srcs = [
            "src/storage/ob_storage_table_guard.cpp",
            "src/storage/ob_storage_util.cpp",
            "src/storage/ob_super_block_struct.cpp",
            "src/storage/ob_sync_tablet_seq_clog.cpp",
            "src/storage/ob_table_store_stat_mgr.cpp",
            "src/storage/ob_value_row_iterator.cpp",
            "src/storage/ob_common_id_utils.cpp",
            "src/storage/ob_protected_memtable_mgr_handle.cpp",
            "src/storage/ob_gc_upper_trans_helper.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_common_mixed_0",
        language = "c++",
        srcs = [
            "src/storage/checkpoint/ob_checkpoint_executor.cpp",
            "src/storage/checkpoint/ob_data_checkpoint.cpp",
            "src/storage/checkpoint/ob_freeze_checkpoint.cpp",
            "src/storage/meta_mem/ob_external_tablet_cnt_map.cpp",
            "src/storage/meta_mem/ob_flying_tablet_pointer_map.cpp",
            "src/storage/meta_mem/ob_meta_obj_struct.cpp",
            "src/storage/meta_mem/ob_storage_meta_cache.cpp",
            "src/storage/meta_mem/ob_tablet_handle.cpp",
            "src/storage/meta_mem/ob_tablet_map_key.cpp",
            "src/storage/meta_mem/ob_tablet_pointer_map.cpp",
            "src/storage/meta_mem/ob_tablet_pointer_handle.cpp",
            "src/storage/meta_mem/ob_tablet_pointer.cpp",
            "src/storage/concurrency_control/ob_multi_version_garbage_collector.cpp",
            "src/storage/concurrency_control/ob_trans_stat_row.cpp",
            "src/storage/meta_mem/ob_storage_meta_mem_mgr.cpp",
            "src/storage/meta_mem/ob_storage_meta_obj_pool.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_compaction_0",
        language = "c++",
        srcs = [
            "src/storage/compaction/ob_table_ckm_items.cpp",
            "src/storage/compaction/ob_batch_exec_dag.cpp",
            "src/storage/compaction/ob_column_checksum_calculator.cpp",
            "src/storage/compaction/ob_index_block_micro_iterator.cpp",
            "src/storage/compaction/ob_i_compaction_filter.cpp",
            "src/storage/compaction/ob_partition_merge_fuser.cpp",
            "src/storage/compaction/ob_partition_merge_iter.cpp",
            "src/storage/compaction/ob_partition_merge_progress.cpp",
            "src/storage/compaction/ob_partition_merger.cpp",
            "src/storage/compaction/ob_partition_merge_policy.cpp",
            "src/storage/compaction/ob_partition_parallel_merge_ctx.cpp",
            "src/storage/compaction/ob_tablet_merge_ctx.cpp",
            "src/storage/compaction/ob_basic_tablet_merge_ctx.cpp",
            "src/storage/compaction/ob_tablet_merge_task.cpp",
            "src/storage/compaction/ob_tablet_merge_info.cpp",
            "src/storage/compaction/ob_compaction_schedule_iterator.cpp",
            "src/storage/compaction/ob_compaction_schedule_util.cpp",
            "src/storage/compaction/ob_schedule_dag_func.cpp",
            "src/storage/compaction/ob_extra_medium_info.cpp",
            "src/storage/compaction/ob_medium_compaction_func.cpp",
            "src/storage/compaction/ob_medium_compaction_mgr.cpp",
            "src/storage/compaction/ob_medium_compaction_info.cpp",
            "src/storage/compaction/ob_compaction_diagnose.cpp",
            "src/storage/compaction/ob_compaction_tablet_diagnose.cpp",
            "src/storage/compaction/ob_compaction_suggestion.cpp",
            "src/storage/compaction/ob_compaction_trans_cache.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_compaction_1",
        language = "c++",
        srcs = [
            "src/storage/compaction/ob_sstable_merge_info_mgr.cpp",
            "src/storage/compaction/ob_server_compaction_event_history.cpp",
            "src/storage/compaction/ob_compaction_util.cpp",
            "src/storage/compaction/ob_partition_rows_merger.cpp",
            "src/storage/compaction/ob_medium_list_checker.cpp",
            "src/storage/compaction/ob_sstable_builder.cpp",
            "src/storage/compaction/ob_compaction_memory_pool.cpp",
            "src/storage/compaction/ob_compaction_memory_context.cpp",
            "src/storage/compaction/ob_sstable_merge_history.cpp",
            "src/storage/compaction/ob_batch_freeze_tablets_dag.cpp",
            "src/storage/compaction/ob_progressive_merge_helper.cpp",
            "src/storage/compaction/ob_medium_loop.cpp",
            "src/storage/compaction/ob_basic_schedule_tablet_func.cpp",
            "src/storage/compaction/ob_schedule_tablet_func.cpp",
            "src/storage/compaction/ob_schedule_status_cache.cpp",
            "src/storage/compaction/ob_mds_filter_info.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_scheduler_0",
        language = "c++",
        srcs = [
            "src/storage/scheduler/ob_dag_scheduler.cpp",
            "src/storage/scheduler/ob_dag_warning_history_mgr.cpp",
            "src/storage/scheduler/ob_independent_dag.cpp",
            "src/storage/scheduler/ob_sys_task_stat.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_compaction_filter_0",
        language = "c++",
        srcs = [
            "src/storage/compaction/filter/ob_tx_data_minor_filter.cpp",
            "src/storage/compaction/filter/ob_mds_info_compaction_filter.cpp",
            "src/storage/compaction/ob_compaction_progress.cpp",
            "src/storage/compaction/ob_freeze_info_mgr.cpp",
            "src/storage/compaction/ob_medium_checker.cpp",
            "src/storage/compaction/ob_runtime_status_cache.cpp",
            "src/storage/compaction/ob_tablet_scheduler.cpp",
            "src/storage/compaction/ob_tablet_scheduler_task_mgr.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_ddl_0",
        language = "c++",
        srcs = [
            "src/storage/ddl/ob_ddl_common_storage_impl.cpp",
            "src/storage/ddl/ob_build_index_task.cpp",
            "src/storage/ddl/ob_complement_data_task.cpp",
            "src/storage/ddl/ob_delete_lob_meta_row_task.cpp",
            "src/storage/ddl/ob_ddl_clog.cpp",
            "src/storage/ddl/ob_ddl_merge_task.cpp",
            "src/storage/ddl/ob_table_fork_info.cpp",
            "src/storage/ddl/ob_tablet_fork_task.cpp",
            "src/storage/ddl/ob_ddl_redo_log_replayer.cpp",
            "src/storage/ddl/ob_ddl_redo_log_writer.cpp",
            "src/storage/ddl/ob_ddl_struct.cpp",
            "src/storage/ddl/ob_ddl_redo_log_row_iterator.cpp",
            "src/storage/ddl/ob_tablet_barrier_log.cpp",
            "src/storage/ddl/ob_tablet_ddl_kv.cpp",
            "src/storage/ddl/ob_tablet_ddl_kv_mgr.cpp",
            "src/storage/ddl/ob_ddl_replay_executor.cpp",
            "src/storage/ddl/ob_ddl_insert_dag.cpp",
            "src/storage/ddl/ob_pipeline.cpp",
            "src/storage/ddl/ob_ddl_heart_beat_task.cpp",
            "src/storage/ddl/ob_ddl_seq_generator.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_ddl_1",
        language = "c++",
        srcs = [
            "src/storage/ddl/ob_direct_load_struct.cpp",
            "src/storage/ddl/ob_ddl_lock.cpp",
            "src/storage/ddl/ob_direct_insert.cpp",
            "src/storage/ddl/ob_ddl_direct_load_utils.cpp",
            "src/storage/ddl/ob_tablet_slice_row_iterator.cpp",
            "src/storage/ddl/ob_ddl_independent_dag.cpp",
            "src/storage/ddl/ob_ddl_macro_block_writer.cpp",
            "src/storage/ddl/ob_ddl_macro_block_write_task.cpp",
            "src/storage/ddl/ob_lob_macro_block_writer.cpp",
            "src/storage/ddl/ob_ddl_dag_thread_pool.cpp",
            "src/storage/ddl/ob_tablet_slice_writer.cpp",
            "src/storage/ddl/ob_ddl_tablet_context.cpp",
            "src/storage/ddl/ob_ddl_pipeline.cpp",
            "src/storage/ddl/ob_ddl_row_tmp_file.cpp",
            "src/storage/ddl/ob_ddl_merge_task_utils.cpp",
            "src/storage/ddl/ob_ddl_merge_task_v2.cpp",
            "src/storage/ddl/ob_ddl_merge_helper.cpp",
            "src/storage/ddl/ob_ddl_merge_schedule.cpp",
            "src/storage/ddl/ob_hnsw_embedmgr.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_deadlock_0",
        language = "c++",
        srcs = [
            "src/storage/deadlock/ob_deadlock_detector_common_define.cpp",
            "src/storage/deadlock/ob_deadlock_detector_mgr.cpp",
            "src/storage/deadlock/ob_deadlock_inner_table_service.cpp",
            "src/storage/deadlock/ob_deadlock_key_wrapper.cpp",
            "src/storage/deadlock/ob_lcl_scheme/ob_lcl_node.cpp",
            "src/storage/deadlock/ob_lcl_scheme/ob_lcl_utils.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_fts_0",
        language = "c++",
        srcs = [
            "src/storage/fts/ob_ik_ft_parser.cpp",
            "src/storage/fts/ob_ngram2_ft_parser.cpp",
            "src/storage/fts/ob_beng_ft_parser.cpp",
            "src/storage/fts/ob_fts_doc_word_iterator.cpp",
            "src/storage/fts/ob_fts_parser_property.cpp",
            "src/storage/fts/ob_fts_stop_word.cpp",
            "src/storage/fts/ob_fts_struct.cpp",
            "src/storage/fts/ob_ngram_ft_parser.cpp",
            "src/storage/fts/ob_whitespace_ft_parser.cpp",
            "src/storage/fts/dict/ob_dic_loader.cpp",
            "src/storage/fts/dict/ob_gen_dic_loader.cpp",
            "src/storage/fts/dict/ob_dic_lock.cpp",
            "src/storage/fts/dict/ob_ik_utf8_dic_loader.cpp",
            "src/storage/fts/utils/unicode_utils.cpp",
            "src/storage/fts/utils/ob_ft_ngram_impl.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_ik_0",
        language = "c++",
        srcs = [
            "src/storage/fts/ik/ob_ik_processor.cpp",
            "src/storage/fts/ik/ob_ik_letter_processor.cpp",
            "src/storage/fts/ik/ob_ik_cjk_processor.cpp",
            "src/storage/fts/ik/ob_ik_quantifier_processor.cpp",
            "src/storage/fts/ik/ob_ik_surrogate_processor.cpp",
            "src/storage/fts/ik/ob_ik_arbitrator.cpp",
            "src/storage/fts/ik/ob_ik_token.cpp",
            "src/storage/fts/dict/ob_ik_dic.cpp",
            "src/storage/fts/dict/ob_ft_dat_dict.cpp",
            "src/storage/fts/dict/ob_ft_dict_def.cpp",
            "src/storage/fts/dict/ob_ft_trie.cpp",
            "src/storage/fts/dict/ob_ft_cache_dict.cpp",
            "src/storage/fts/dict/ob_ft_dict_hub.cpp",
            "src/storage/fts/dict/ob_ft_range_dict.cpp",
            "src/storage/fts/dict/ob_ft_dict_table_iter.cpp",
            "src/storage/fts/dict/ob_ft_cache.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_lob_0",
        language = "c++",
        srcs = [
            "src/storage/lob/ob_lob_meta.cpp",
            "src/storage/lob/ob_lob_manager.cpp",
            "src/storage/lob/ob_lob_seq.cpp",
            "src/storage/lob/ob_lob_piece.cpp",
            "src/storage/lob/ob_lob_persistent_adaptor.cpp",
            "src/storage/lob/ob_lob_data_reader.cpp",
            "src/storage/lob/ob_lob_locator.cpp",
            "src/storage/lob/ob_lob_util.cpp",
            "src/storage/lob/ob_ext_info_callback.cpp",
            "src/storage/lob/ob_lob_access_param.cpp",
            "src/storage/lob/ob_lob_persistent_reader.cpp",
            "src/storage/lob/ob_lob_persistent_iterator.cpp",
            "src/storage/lob/ob_lob_write_buffer.cpp",
            "src/storage/lob/ob_lob_cursor.cpp",
            "src/storage/lob/ob_lob_location.cpp",
            "src/storage/lob/ob_lob_iterator.cpp",
            "src/storage/lob/ob_lob_handler.cpp",
            "src/storage/lob/ob_lob_meta_manager.cpp",
            "src/storage/lob/ob_lob_retry.cpp",
            "src/storage/lob/ob_lob_tablet_dml.cpp",
            "src/storage/lob/ob_lob_locator_struct.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_ls_0",
        language = "c++",
        srcs = [
            "src/storage/ls/ob_freezer.cpp",
            "src/storage/ls/ob_ls_wrs_handler.cpp",
            "src/storage/ls/ob_ls.cpp",
            "src/storage/ls/ob_ls_ddl_log_handler.cpp",
            "src/storage/ls/ob_ls_lock.cpp",
            "src/storage/ls/ob_ls_meta.cpp",
            "src/storage/ls/ob_ls_state.cpp",
            "src/storage/ls/ob_ls_sync_tablet_seq_handler.cpp",
            "src/storage/ls/ob_ls_switch_checker.cpp",
            "src/storage/ls/ob_ls_tablet_service.cpp",
            "src/storage/ls/ob_ls_tx_service.cpp",
            "src/storage/ls/ob_ls_saved_info.cpp",
            "src/storage/ls/ob_ls_reserved_snapshot_mgr.cpp",
            "src/storage/ls/ob_ls_storage_clog_handler.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_memtable_0",
        language = "c++",
        srcs = [
            "src/storage/memtable/ob_lock_wait_mgr.cpp",
            "src/storage/memtable/ob_memtable.cpp",
            "src/storage/memtable/ob_memtable_key.cpp",
            "src/storage/memtable/ob_memtable_compact_writer.cpp",
            "src/storage/memtable/ob_memtable_context.cpp",
            "src/storage/memtable/ob_memtable_iterator.cpp",
            "src/storage/memtable/ob_memtable_mutator.cpp",
            "src/storage/memtable/ob_memtable_read_row_util.cpp",
            "src/storage/memtable/ob_memtable_single_row_reader.cpp",
            "src/storage/memtable/ob_redo_log_generator.cpp",
            "src/storage/memtable/ob_row_compactor.cpp",
            "src/storage/memtable/ob_row_conflict_handler.cpp",
            "src/storage/memtable/ob_concurrent_control.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_memtable_mvcc_0",
        language = "c++",
        srcs = [
            "src/storage/memtable/mvcc/ob_multi_version_iterator.cpp",
            "src/storage/memtable/mvcc/ob_mvcc_acc_ctx.cpp",
            "src/storage/memtable/mvcc/ob_mvcc_ctx.cpp",
            "src/storage/memtable/mvcc/ob_mvcc_engine.cpp",
            "src/storage/memtable/mvcc/ob_mvcc_iterator.cpp",
            "src/storage/memtable/mvcc/ob_mvcc_row.cpp",
            "src/storage/memtable/mvcc/ob_mvcc_trans_ctx.cpp",
            "src/storage/memtable/mvcc/ob_tx_callback_list.cpp",
            "src/storage/memtable/mvcc/ob_query_engine.cpp",
            "src/storage/memtable/mvcc/ob_row_data.cpp",
            "src/storage/memtable/mvcc/ob_mvcc_define.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_meta_store_0",
        language = "c++",
        srcs = [
            "src/storage/meta_store/ob_server_storage_meta_service.cpp",
            "src/storage/meta_store/ob_server_storage_meta_persister.cpp",
            "src/storage/meta_store/ob_server_storage_meta_replayer.cpp",
            "src/storage/meta_store/ob_storage_meta_io_util.cpp",
            "src/storage/meta_store/ob_local_storage_meta_persister.cpp",
            "src/storage/meta_store/ob_local_storage_meta_replayer.cpp",
            "src/storage/meta_store/ob_local_storage_meta_service.cpp",
            "src/storage/meta_store/ob_server_runtime_meta.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_multi_data_source_0",
        language = "c++",
        srcs = [
            "src/storage/multi_data_source/buffer_ctx.cpp",
            "src/storage/multi_data_source/mds_ctx.cpp",
            "src/storage/multi_data_source/mds_for_each_map_flush_operation.cpp",
            "src/storage/multi_data_source/mds_node.cpp",
            "src/storage/multi_data_source/mds_table_mgr.cpp",
            "src/storage/multi_data_source/mds_table_order_flusher.cpp",
            "src/storage/multi_data_source/mds_table_base.cpp",
            "src/storage/multi_data_source/mds_writer.cpp",
            "src/storage/multi_data_source/mds_table_handler.cpp",
            "src/storage/multi_data_source/adapter_define/mds_dump_kv_wrapper.cpp",
            "src/storage/multi_data_source/adapter_define/mds_dump_node.cpp",
            "src/storage/multi_data_source/runtime_utility/common_define.cpp",
            "src/storage/multi_data_source/runtime_utility/mds_factory.cpp",
            "src/storage/multi_data_source/runtime_utility/mds_retry_control.cpp",
            "src/storage/multi_data_source/ob_mds_table_merge_dag.cpp",
            "src/storage/multi_data_source/ob_mds_table_merge_dag_param.cpp",
            "src/storage/multi_data_source/ob_mds_table_merge_task.cpp",
            "src/storage/multi_data_source/ob_mds_minor_compaction_filter.cpp",
            "src/storage/multi_data_source/ob_tablet_create_mds_ctx.cpp",
            "src/storage/multi_data_source/ob_tablet_mds_merge_ctx.cpp",
            "src/storage/multi_data_source/mds_key_serialize_util.cpp",
            "src/storage/multi_data_source/runtime_utility/mds_service.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_retrieval_0",
        language = "c++",
        srcs = [
            "src/storage/retrieval/ob_block_max_iter.cpp",
            "src/storage/retrieval/ob_block_stat_collector.cpp",
            "src/storage/retrieval/ob_block_stat_iter.cpp",
            "src/storage/retrieval/ob_inv_idx_param_estimator.cpp",
            "src/storage/retrieval/ob_sparse_bmw_iter.cpp",
            "src/storage/retrieval/ob_sparse_daat_iter.cpp",
            "src/storage/retrieval/ob_sparse_taat_iter.cpp",
            "src/storage/retrieval/ob_sparse_utils.cpp",
            "src/storage/retrieval/ob_sparse_lookup_iter.cpp",
            "src/storage/retrieval/ob_sparse_retrieval_factory.cpp",
            "src/storage/retrieval/ob_retrieval_program.cpp",
            "src/storage/retrieval/ob_sparse_vector_block_source.cpp",
            "src/storage/retrieval/ob_text_retrieval_token_iter.cpp",
            "src/storage/retrieval/ob_text_daat_iter.cpp",
            "src/storage/retrieval/ob_text_taat_iter.cpp",
            "src/storage/retrieval/ob_spiv_daat_iter.cpp",
            "src/storage/retrieval/ob_spiv_dim_iter.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_slog_0",
        language = "c++",
        srcs = [
            "src/storage/slog/ob_server_slog_writer.cpp",
            "src/storage/slog/ob_storage_log_batch_header.cpp",
            "src/storage/slog/ob_storage_log_entry.cpp",
            "src/storage/slog/ob_storage_log_item.cpp",
            "src/storage/slog/ob_storage_log_nop_log.cpp",
            "src/storage/slog/ob_storage_log_reader.cpp",
            "src/storage/slog/ob_storage_log_replayer.cpp",
            "src/storage/slog/ob_storage_log_struct.cpp",
            "src/storage/slog/ob_storage_log.cpp",
            "src/storage/slog/ob_storage_log_write_buffer.cpp",
            "src/storage/slog/ob_storage_log_writer.cpp",
            "src/storage/slog/ob_storage_logger.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_tablelock_0",
        language = "c++",
        srcs = [
            "src/storage/tablelock/ob_lock_memtable.cpp",
            "src/storage/tablelock/ob_lock_memtable_mgr.cpp",
            "src/storage/tablelock/ob_lock_inner_connection_util.cpp",
            "src/storage/tablelock/ob_lock_table.cpp",
            "src/storage/tablelock/ob_lock_utils.cpp",
            "src/storage/tablelock/ob_mem_ctx_table_lock.cpp",
            "src/storage/tablelock/ob_obj_lock.cpp",
            "src/storage/tablelock/ob_table_lock_callback.cpp",
            "src/storage/tablelock/ob_table_lock_common.cpp",
            "src/storage/tablelock/ob_table_lock_deadlock.cpp",
            "src/storage/tablelock/ob_table_lock_iterator.cpp",
            "src/storage/tablelock/ob_table_lock_rpc_struct.cpp",
            "src/storage/tablelock/ob_table_lock_service.cpp",
            "src/storage/tablelock/ob_table_lock_local_executor.cpp",
            "src/storage/tablelock/ob_table_lock_live_detector.cpp",
            "src/storage/tablelock/ob_session_table_lock.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_tablet_0",
        language = "c++",
        srcs = [
            "src/storage/tablet/ob_batch_create_tablet_arg.cpp",
            "src/storage/tablet/ob_batch_create_tablet_pretty_arg.cpp",
            "src/storage/tablet/ob_full_tablet_creator.cpp",
            "src/storage/tablet/ob_i_tablet_mds_interface.cpp",
            "src/storage/tablet/ob_i_tablet_mds_customized_interface.cpp",
            "src/storage/tablet/ob_mds_range_query_iterator.cpp",
            "src/storage/tablet/ob_mds_row_iterator.cpp",
            "src/storage/tablet/ob_mds_scan_param_helper.cpp",
            "src/storage/tablet/ob_mds_schema_helper.cpp",
            "src/storage/tablet/ob_tablet_binding_helper.cpp",
            "src/storage/tablet/ob_tablet_binding_replay_executor.cpp",
            "src/storage/tablet/ob_tablet_complex_addr.cpp",
            "src/storage/tablet/ob_tablet_create_delete_helper.cpp",
            "src/storage/tablet/ob_tablet_create_replay_executor.cpp",
            "src/storage/tablet/ob_tablet_create_sstable_param.cpp",
            "src/storage/tablet/ob_tablet_ddl_info.cpp",
            "src/storage/tablet/ob_tablet_id_set.cpp",
            "src/storage/tablet/ob_tablet_iterator.cpp",
            "src/storage/tablet/ob_tablet_memtable_mgr.cpp",
            "src/storage/tablet/ob_tablet_meta.cpp",
            "src/storage/tablet/ob_tablet_multi_source_data.cpp",
            "src/storage/tablet/ob_tablet_replay_executor.cpp",
            "src/storage/tablet/ob_tablet_service_clog_replay_executor.cpp",
            "src/storage/tablet/ob_tablet_status.cpp",
            "src/storage/tablet/ob_tablet_table_store.cpp",
            "src/storage/tablet/ob_tablet_table_store_iterator.cpp",
            "src/storage/tablet/ob_table_store_util.cpp",
            "src/storage/tablet/ob_tablet_table_store_flag.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_tablet_1",
        language = "c++",
        srcs = [
            "src/storage/tablet/ob_tablet_create_delete_mds_user_data.cpp",
            "src/storage/tablet/ob_tablet_create_mds_helper.cpp",
            "src/storage/tablet/ob_tablet_delete_mds_helper.cpp",
            "src/storage/tablet/ob_tablet_delete_replay_executor.cpp",
            "src/storage/tablet/ob_tablet_ddl_complete_replay_executor.cpp",
            "src/storage/tablet/ob_tablet_full_medium_info.cpp",
            "src/storage/tablet/ob_tablet_full_memory_mds_data.cpp",
            "src/storage/tablet/ob_tablet_mds_data.cpp",
            "src/storage/tablet/ob_tablet_mds_data_cache.cpp",
            "src/storage/tablet/ob_tablet_dumped_medium_info.cpp",
            "src/storage/tablet/ob_tablet_binding_info.cpp",
            "src/storage/tablet/ob_tablet_binding_mds_user_data.cpp",
            "src/storage/tablet/ob_tablet_mds_node_dump_operator.cpp",
            "src/storage/tablet/ob_tablet_mds_table_mini_merger.cpp",
            "src/storage/tablet/ob_tablet_fork_mds_helper.cpp",
            "src/storage/tablet/ob_tablet_persister.cpp",
            "src/storage/tablet/ob_tablet_obj_load_helper.cpp",
            "src/storage/tablet/ob_tablet.cpp",
            "src/storage/tablet/ob_tablet_block_header.cpp",
            "src/storage/tablet/ob_tablet_medium_info_reader.cpp",
            "src/storage/tablet/ob_tablet_space_usage.cpp",
            "src/storage/tablet/ob_tablet_block_aggregated_info.cpp",
            "src/storage/tablet/ob_tablet_macro_info_iterator.cpp",
            "src/storage/tablet/ob_tablet_ddl_complete_mds_helper.cpp",
            "src/storage/tablet/ob_tablet_ddl_complete_mds_data.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_throttle_0",
        language = "c++",
        srcs = [
            "src/storage/throttle/ob_share_throttle_define.cpp",
            "src/storage/throttle/ob_throttle_common.cpp",
            "src/storage/ob_tablet_autoinc_seq_service.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_tmp_file_0",
        language = "c++",
        srcs = [
            "src/storage/tmp_file/ob_i_tmp_file.cpp",
            "src/storage/tmp_file/ob_i_tmp_file_manager.cpp",
            "src/storage/tmp_file/ob_shared_nothing_tmp_file.cpp",
            "src/storage/tmp_file/ob_sn_tmp_file_manager.cpp",
            "src/storage/tmp_file/ob_tmp_file_block_manager.cpp",
            "src/storage/tmp_file/ob_tmp_file_cache.cpp",
            "src/storage/tmp_file/ob_tmp_file_eviction_manager.cpp",
            "src/storage/tmp_file/ob_tmp_file_flush_ctx.cpp",
            "src/storage/tmp_file/ob_tmp_file_flush_list_iterator.cpp",
            "src/storage/tmp_file/ob_tmp_file_flush_manager.cpp",
            "src/storage/tmp_file/ob_tmp_file_flush_priority_manager.cpp",
            "src/storage/tmp_file/ob_tmp_file_global.cpp",
            "src/storage/tmp_file/ob_tmp_file_io_ctx.cpp",
            "src/storage/tmp_file/ob_tmp_file_io_handle.cpp",
            "src/storage/tmp_file/ob_tmp_file_io_info.cpp",
            "src/storage/tmp_file/ob_tmp_file_meta_tree.cpp",
            "src/storage/tmp_file/ob_tmp_file_manager.cpp",
            "src/storage/tmp_file/ob_tmp_file_page_cache_controller.cpp",
            "src/storage/tmp_file/ob_tmp_file_thread_wrapper.cpp",
            "src/storage/tmp_file/ob_tmp_file_thread_job.cpp",
            "src/storage/tmp_file/ob_tmp_file_write_buffer_pool.cpp",
            "src/storage/tmp_file/ob_tmp_file_write_buffer_index_cache.cpp",
            "src/storage/tmp_file/ob_tmp_file_write_buffer_pool_entry_array.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_truncate_info_0",
        language = "c++",
        srcs = [
            "src/storage/truncate_info/ob_truncate_info_array.cpp",
            "src/storage/truncate_info/ob_truncate_info.cpp",
            "src/storage/truncate_info/ob_truncate_info_mds_helper.cpp",
            "src/storage/truncate_info/ob_truncate_tablet_arg.cpp",
            "src/storage/truncate_info/ob_tablet_truncate_info_reader.cpp",
            "src/storage/truncate_info/ob_truncate_filter_evaluator.cpp",
            "src/storage/truncate_info/ob_truncate_partition_filter.cpp",
            "src/storage/truncate_info/ob_mds_info_distinct_mgr.cpp",
            "src/storage/truncate_info/ob_truncate_info_kv_cache.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_tx_0",
        language = "c++",
        srcs = [
            "src/storage/tx/ob_ctx_tx_data.cpp",
            "src/storage/tx/ob_id_service.cpp",
            "src/storage/tx/ob_keep_alive_ls_handler.cpp",
            "src/storage/tx/ob_tx_loop_worker.cpp",
            "src/storage/tx/ob_tx_ctx_log_cb_helper.cpp",
            "src/storage/tx/ob_timestamp_access.cpp",
            "src/storage/tx/ob_timestamp_service.cpp",
            "src/storage/tx/ob_weak_read_util.cpp",
            "src/storage/tx/ob_trans_ctx.cpp",
            "src/storage/tx/ob_trans_ctx_lock.cpp",
            "src/storage/tx/ob_trans_ctx_mgr.cpp",
            "src/storage/tx/ob_trans_deadlock_adapter.cpp",
            "src/storage/tx/ob_trans_ctx_mgr_v4.cpp",
            "src/storage/tx/ob_trans_define.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_tx_1",
        language = "c++",
        srcs = [
            "src/storage/tx/ob_trans_define_v4.cpp",
            "src/storage/tx/ob_trans_end_trans_callback.cpp",
            "src/storage/tx/ob_trans_factory.cpp",
            "src/storage/tx/tx_ctx_cache.cpp",
            "src/storage/tx/ob_trans_id_service.cpp",
            "src/storage/tx/ob_trans_memory_stat.cpp",
            "src/storage/tx/ob_defensive_check_mgr.cpp",
            "src/storage/tx/ob_trans_result.cpp",
            "src/storage/tx/ob_tx_result_struct.cpp",
            "src/storage/tx/ob_trans_service.cpp",
            "src/storage/tx/ob_trans_service_v4.cpp",
            "src/storage/tx/ob_tx_api.cpp",
            "src/storage/tx/ob_tx_elr_util.cpp",
            "src/storage/tx/ob_tx_elr_handler.cpp",
            "src/storage/tx/ob_tx_stat.cpp",
            "src/storage/tx/ob_ls_tx_ctx_mgr_stat.cpp",
            "src/storage/tx/ob_trans_submit_log_cb.cpp",
            "src/storage/tx/ob_trans_timer.cpp",
            "src/storage/tx/ob_trans_version_mgr.cpp",
            "src/storage/tx/ob_ts_mgr.cpp",
            "src/storage/tx/ob_tx_data_define.cpp",
            "src/storage/tx/ob_tx_data_op.cpp",
            "src/storage/tx/ob_tx_data_functor.cpp",
            "src/storage/tx/ob_tx_log.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_tx_2",
        language = "c++",
        srcs = [
            "src/storage/tx/ob_tx_log_adapter.cpp",
            "src/storage/tx/ob_tx_big_segment_buf.cpp",
            "src/storage/tx/ob_tx_on_demand_print.cpp",
            "src/storage/tx/ob_tx_replay_executor.cpp",
            "src/storage/tx/ob_tx_ctx_mds.cpp",
            "src/storage/tx/ob_multi_data_source.cpp",
            "src/storage/tx/ob_multi_data_source_printer.cpp",
            "src/storage/tx/ob_multi_data_source_tx_buffer_node.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_tx_storage_0",
        language = "c++",
        srcs = [
            "src/storage/tx_storage/ob_access_service.cpp",
            "src/storage/tx_storage/ob_checkpoint_service.cpp",
            "src/storage/tx_storage/ob_ls_freeze_thread.cpp",
            "src/storage/tx_storage/ob_ls_service.cpp",
            "src/storage/tx_storage/ob_log_storage_adapter.cpp",
            "src/storage/tx_storage/ob_tablet_gc_service.cpp",
            "src/storage/tx_storage/ob_empty_shell_task.cpp",
            "src/storage/tx_storage/ob_memory_printer.cpp",
            "src/storage/tx_storage/ob_memstore_freezer.cpp",
            "src/storage/tx_storage/ob_memstore_freezer_common.cpp",
            "src/storage/tx_storage/ob_memstore_freezer_local_dispatch.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_tx_table_0",
        language = "c++",
        srcs = [
            "src/storage/tx_table/ob_tx_ctx_memtable.cpp",
            "src/storage/tx_table/ob_tx_ctx_memtable_mgr.cpp",
            "src/storage/tx_table/ob_tx_ctx_table.cpp",
            "src/storage/tx_table/ob_tx_data_cache.cpp",
            "src/storage/tx_table/ob_tx_data_hash_map.cpp",
            "src/storage/tx_table/ob_tx_data_memtable.cpp",
            "src/storage/tx_table/ob_tx_data_memtable_mgr.cpp",
            "src/storage/tx_table/ob_tx_data_table.cpp",
            "src/storage/tx_table/ob_tx_table.cpp",
            "src/storage/tx_table/ob_tx_table_define.cpp",
            "src/storage/tx_table/ob_tx_table_guards.cpp",
            "src/storage/tx_table/ob_tx_table_interface.cpp",
            "src/storage/tx_table/ob_tx_table_iterator.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_vector_index_0",
        language = "c++",
        srcs = [
            "src/storage/vector_index/ob_vector_kmeans_ctx.cpp",
            "src/storage/blockstore/ob_object_reader_writer.cpp",
            "src/storage/ob_tablet_local_status.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_vector_type_0",
        language = "c++",
        srcs = [
            "src/storage/vector_type/ob_vector_add.cpp",
            "src/storage/vector_type/ob_vector_div.cpp",
            "src/storage/vector_type/ob_vector_l2_distance.cpp",
            "src/storage/vector_type/ob_vector_ip_distance.cpp",
            "src/storage/vector_type/ob_vector_cosine_distance.cpp",
            "src/storage/vector_type/ob_vector_l1_distance.cpp",
            "src/storage/vector_type/ob_vector_norm.cpp",
            "src/storage/vector_type/ob_vector_common_util.cpp",
            "src/storage/vector_type/ob_sparse_vector_ip_distance.cpp",
            "src/storage/vector_type/ob_vector_l2_similarity.cpp",
            "src/storage/vector_type/ob_vector_cosine_similarity.cpp",
            "src/storage/vector_type/ob_vector_ip_similarity.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_storage_rebase_0",
        language = "c++",
        srcs = [
            "src/storage/ddl/ob_ddl_batch_rows.cpp",
            "src/storage/ddl/ob_ddl_continuous_vector.cpp",
            "src/storage/ddl/ob_ddl_discrete_vector.cpp",
            "src/storage/ddl/ob_ddl_fixed_length_vector.cpp",
            "src/storage/ddl/ob_ddl_vector.cpp",
            "src/storage/ddl/ob_ddl_vector_continuous.cpp",
            "src/storage/ddl/ob_ddl_vector_discrete.cpp",
            "src/storage/ddl/ob_ddl_vector_fixed.cpp",
            "src/storage/ddl/ob_ddl_vector_uniform.cpp",
            "src/storage/ddl/ob_ddl_vector_uniform_const.cpp",
            "src/storage/ddl/ob_ddl_vector_utils.cpp",
            "src/storage/fts/ob_fts_parser_helper.cpp",
            "src/storage/fts/ob_fts_parser_name.cpp",
            "src/storage/tx/ob_tx_ctx.cpp",
            "src/storage/tx/ob_tx_print_time_guard.cpp",
            "src/storage/tx/ob_tx_timestamp_waiter.cpp",
            "src/storage/ddl/ob_tablet_copy_util.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
]

STORAGE_SIMD_UNITY_GROUPS = [
    struct(
        name = "ob_storage_simd_common_0",
        language = "c++",
        srcs = [
            "src/storage/blocksstable/encoding/ob_raw_decoder_simd.cpp",
            "src/storage/blocksstable/encoding/ob_dict_decoder_simd.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
]

STORAGE_STANDALONE_SOURCES = [
]

STORAGE_EXTRA_SOURCES = [
]
