"""Generated source inventory for the native Rootserver module."""

ROOTSERVER_IGNORED_SOURCES = []

ROOTSERVER_UNITY_GROUPS = [
    struct(
        name = "ob_rootserver_base_common_0",
        language = "c++",
        srcs = [
            "src/rootserver/ob_ddl_sql_generator.cpp",
            "src/rootserver/ob_rs_reentrant_thread.cpp",
            "src/rootserver/ob_schema2ddl_sql.cpp",
            "src/rootserver/ob_snapshot_info_manager.cpp",
            "src/rootserver/ob_thread_idling.cpp",
            "src/rootserver/ob_load_inner_table_schema_executor.cpp",
            "src/rootserver/ob_ai_model_ddl_operator.cpp",
            "src/rootserver/fork_table/ob_fork_table_info_builder.cpp",
            "src/rootserver/dbms_job/ob_dbms_job_executor.cpp",
            "src/rootserver/dbms_job/ob_dbms_job_utils.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_rootserver_base_maintenance_0",
        language = "c++",
        srcs = [
            "src/rootserver/freeze/ob_daily_major_freeze_launcher.cpp",
            "src/rootserver/freeze/ob_major_merge_progress_util.cpp",
            "src/rootserver/freeze/ob_fts_checksum_validate_util.cpp",
            "src/rootserver/freeze/ob_global_merge_manager.cpp",
            "src/rootserver/freeze/ob_local_major_freeze.cpp",
            "src/rootserver/freeze/ob_snapshot_gc_scn_renewer.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_rootserver_query_0",
        language = "c++",
        srcs = [
            "src/rootserver/ob_dependency_ddl_helper.cpp",
            "src/rootserver/ob_objpriv_mysql_ddl_operator.cpp",
            "src/rootserver/ob_admin_job_table_operator.cpp",
            "src/rootserver/ob_local_management_service.cpp",
            "src/rootserver/ob_runtime_ddl_service.cpp",
            "src/rootserver/ob_server_thread_helper.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_rootserver_storage_common_0",
        language = "c++",
        srcs = [
            "src/rootserver/ob_root_minor_freeze.cpp",
            "src/rootserver/ob_root_utils.cpp",
            "src/rootserver/ob_table_creator.cpp",
            "src/rootserver/ob_tablet_creator.cpp",
            "src/rootserver/ob_tablet_drop.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_rootserver_storage_freeze_0",
        language = "c++",
        srcs = [
            "src/rootserver/freeze/ob_major_merge_scheduler.cpp",
            "src/rootserver/freeze/ob_major_merge_progress_checker.cpp",
            "src/rootserver/freeze/ob_freeze_reentrant_thread.cpp",
            "src/rootserver/freeze/ob_checksum_validator.cpp",
            "src/rootserver/freeze/ob_major_freeze_service.cpp",
            "src/rootserver/freeze/ob_major_freeze_helper.cpp",
            "src/rootserver/freeze/ob_major_freeze_coordinator_adapter.cpp",
            "src/rootserver/freeze/ob_major_freeze_util.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_rootserver_sql_mixed_0",
        language = "c++",
        srcs = [
            "src/rootserver/ddl_task/ob_ddl_longops.cpp",
            "src/rootserver/ddl_task/ob_drop_primary_key_task.cpp",
            "src/rootserver/pl_ddl/ob_pl_ddl_operator.cpp",
            "src/rootserver/ddl_task/ob_ddl_local_build_executor.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_rootserver_runtime_common_0",
        language = "c++",
        srcs = [
            "src/rootserver/ddl_task/ob_ddl_common_rs_impl.cpp",
            "src/rootserver/ob_bootstrap.cpp",
            "src/rootserver/ob_ddl_operator.cpp",
            "src/rootserver/ob_index_builder.cpp",
            "src/rootserver/ob_max_id_cache_adapter.cpp",
            "src/rootserver/ob_partition_creator.cpp",
            "src/rootserver/ob_root_inspection.cpp",
            "src/rootserver/ob_system_admin_util.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_rootserver_runtime_common_1",
        language = "c++",
        srcs = [
            "src/rootserver/ob_lob_piece_builder.cpp",
            "src/rootserver/ob_lob_meta_builder.cpp",
            "src/rootserver/ob_partition_exchange.cpp",
            "src/rootserver/ob_alter_table_constraint_checker.cpp",
            "src/rootserver/ob_ai_model_ddl_service.cpp",
            "src/rootserver/graph_ddl_service.cpp",
            "src/rootserver/ob_objpriv_mysql_ddl_service.cpp",
            "src/rootserver/ob_create_index_on_empty_table_helper.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_rootserver_runtime_ddl_0",
        language = "c++",
        srcs = [
            "src/rootserver/ddl_task/ob_column_redefinition_task.cpp",
            "src/rootserver/ddl_task/ob_constraint_task.cpp",
            "src/rootserver/ddl_task/ob_ddl_retry_task.cpp",
            "src/rootserver/ddl_task/ob_ddl_scheduler.cpp",
            "src/rootserver/ddl_task/ob_ddl_task.cpp",
            "src/rootserver/ddl_task/ob_drop_index_task.cpp",
            "src/rootserver/ddl_task/ob_drop_fts_index_task.cpp",
            "src/rootserver/ddl_task/ob_drop_vec_index_task.cpp",
            "src/rootserver/ddl_task/ob_index_build_task.cpp",
            "src/rootserver/ddl_task/ob_fts_index_build_task.cpp",
            "src/rootserver/ddl_task/ob_modify_autoinc_task.cpp",
            "src/rootserver/ddl_task/ob_table_redefinition_task.cpp",
            "src/rootserver/ddl_task/ob_ddl_tablet_scheduler.cpp",
            "src/rootserver/ddl_task/ob_drop_vec_ivf_index_task.cpp",
            "src/rootserver/ddl_task/ob_rebuild_index_task.cpp",
            "src/rootserver/ddl_task/ob_vec_index_build_task.cpp",
            "src/rootserver/fork_table/ob_fork_database_service.cpp",
            "src/rootserver/ddl_task/ob_sys_ddl_util.cpp",
            "src/rootserver/ddl_task/ob_vec_ivf_index_build_task.cpp",
            "src/rootserver/ddl_task/ob_drop_lob_task.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_rootserver_runtime_fork_freeze_0",
        language = "c++",
        srcs = [
            "src/rootserver/fork_table/ob_fork_table_helper.cpp",
            "src/rootserver/fork_table/ob_fork_table_util.cpp",
            "src/rootserver/ob_domain_index_builder_util.cpp",
            "src/rootserver/fork_table/ob_fork_table_service.cpp",
            "src/rootserver/fork_table/ob_fork_table_task.cpp",
            "src/rootserver/freeze/ob_freeze_info_detector.cpp",
            "src/rootserver/freeze/ob_major_merge_info_manager.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
    struct(
        name = "ob_rootserver_runtime_services_0",
        language = "c++",
        srcs = [
            "src/rootserver/parallel_ddl/ob_ddl_helper.cpp",
            "src/rootserver/parallel_ddl/ob_create_table_helper.cpp",
            "src/rootserver/parallel_ddl/ob_create_view_helper.cpp",
            "src/rootserver/parallel_ddl/ob_set_comment_helper.cpp",
            "src/rootserver/parallel_ddl/ob_create_index_helper.cpp",
            "src/rootserver/parallel_ddl/ob_update_index_status_helper.cpp",
            "src/rootserver/parallel_ddl/ob_drop_table_helper.cpp",
            "src/rootserver/parallel_ddl/ob_table_helper.cpp",
            "src/rootserver/parallel_ddl/ob_create_table_like_helper.cpp",
            "src/rootserver/pl_ddl/ob_pl_ddl_service.cpp",
            "src/rootserver/truncate_info/ob_truncate_info_service.cpp",
            "src/rootserver/dbms_job/ob_dbms_job_master.cpp",
        ],
        generated_srcs = [],
        external_srcs = [],
    ),
]

ROOTSERVER_STANDALONE_SOURCES = [
    struct(path = "src/rootserver/ddl_task/ob_ddl_redefinition_task.cpp", language = "c++", kind = "source"),
    struct(path = "src/rootserver/ob_ddl_service.cpp", language = "c++", kind = "source"),
    struct(path = "src/rootserver/ob_ddl_service_launcher.cpp", language = "c++", kind = "source"),
    struct(path = "src/rootserver/ob_debug_sync_broadcaster_adapter.cpp", language = "c++", kind = "source"),
    struct(path = "src/rootserver/ob_lonely_table_cleaner.cpp", language = "c++", kind = "source"),
]
