"""Native public and private header ownership for Rootserver."""

ROOTSERVER_PUBLIC_HEADERS = [
    "dbms_job/ob_dbms_job_master.h",
    "dbms_job/ob_dbms_job_utils.h",
    "ddl_task/ob_column_redefinition_task.h",
    "ddl_task/ob_constraint_task.h",
    "ddl_task/ob_ddl_longops.h",
    "ddl_task/ob_ddl_local_build_executor.h",
    "ddl_task/ob_ddl_redefinition_task.h",
    "ddl_task/ob_ddl_retry_task.h",
    "ddl_task/ob_ddl_scheduler.h",
    "ddl_task/ob_ddl_tablet_scheduler.h",
    "ddl_task/ob_ddl_task.h",
    "ddl_task/ob_drop_index_task.h",
    "ddl_task/ob_drop_primary_key_task.h",
    "ddl_task/ob_index_build_task.h",
    "ddl_task/ob_modify_autoinc_task.h",
    "ddl_task/ob_table_redefinition_task.h",
    "fork_table/ob_fork_table_util.h",
    "freeze/ob_checksum_validator.h",
    "freeze/ob_daily_major_freeze_launcher.h",
    "freeze/ob_freeze_info_detector.h",
    "freeze/ob_freeze_reentrant_thread.h",
    "freeze/ob_fts_checksum_validate_util.h",
    "freeze/ob_major_freeze_helper.h",
    "freeze/ob_major_freeze_coordinator_adapter.h",
    "freeze/ob_major_freeze_service.h",
    "freeze/ob_major_freeze_util.h",
    "freeze/ob_major_merge_info_manager.h",
    "freeze/ob_major_merge_progress_checker.h",
    "freeze/ob_major_merge_progress_util.h",
    "freeze/ob_major_merge_scheduler.h",
    "ob_bootstrap.h",
    "ob_ddl_operator.h",
    "ob_ddl_service.h",
    "ob_ddl_service_launcher.h",
    "ob_debug_sync_broadcaster_adapter.h",
    "ob_i_debug_sync_local_runtime.h",
    "ob_max_id_cache_adapter.h",
    "ob_objpriv_mysql_ddl_service.h",
    "ob_partition_exchange.h",
    "ob_root_inspection.h",
    "ob_root_minor_freeze.h",
    "ob_root_utils.h",
    "ob_rootserver_local_runtime.h",
    "ob_runtime_ddl_service.h",
    "ob_rs_reentrant_thread.h",
    "ob_snapshot_info_manager.h",
    "ob_system_admin_util.h",
    "ob_tablet_creator.h",
    "ob_thread_idling.h",
    "pl_ddl/ob_pl_ddl_operator.h",
    "pl_ddl/ob_pl_ddl_service.h",
    "ob_admin_job_table_operator.h",
    "ob_admin_job_type.h",
    "ob_local_ddl_serial_call.h",
    "ob_local_management_service.h",
    "ob_server_thread_helper.h",
]


ROOTSERVER_PRIVATE_HEADERS = [
    "dbms_job/ob_dbms_job_executor.h",
    "ddl_task/ob_drop_fts_index_task.h",
    "ddl_task/ob_drop_lob_task.h",
    "ddl_task/ob_drop_vec_index_task.h",
    "ddl_task/ob_drop_vec_ivf_index_task.h",
    "ddl_task/ob_fts_index_build_task.h",
    "ddl_task/ob_rebuild_index_task.h",
    "ddl_task/ob_sys_ddl_util.h",
    "ddl_task/ob_ddl_task_util.h",
    "ddl_task/ob_vec_index_build_task.h",
    "ddl_task/ob_vec_ivf_index_build_task.h",
    "fork_table/ob_fork_table_helper.h",
    "fork_table/ob_fork_table_info_builder.h",
    "fork_table/ob_fork_table_task.h",
    "ob_ai_model_ddl_operator.h",
    "ob_ai_model_ddl_service.h",
    "graph_ddl_service.h",
    "ob_alter_table_constraint_checker.h",
    "ob_create_index_on_empty_table_helper.h",
    "ob_ddl_sql_generator.h",
    "ob_dependency_ddl_helper.h",
    "ob_domain_index_builder_util.h",
    "ob_index_builder.h",
    "ob_load_inner_table_schema_executor.h",
    "ob_lob_meta_builder.h",
    "ob_lob_piece_builder.h",
    "ob_objpriv_mysql_ddl_operator.h",
    "ob_partition_creator.h",
    "ob_schema2ddl_sql.h",
    "ob_table_creator.h",
    "ob_tablet_drop.h",
    "parallel_ddl/ob_create_index_helper.h",
    "parallel_ddl/ob_create_table_helper.h",
    "parallel_ddl/ob_create_table_like_helper.h",
    "parallel_ddl/ob_create_view_helper.h",
    "parallel_ddl/ob_ddl_helper.h",
    "parallel_ddl/ob_drop_table_helper.h",
    "parallel_ddl/ob_set_comment_helper.h",
    "parallel_ddl/ob_table_helper.h",
    "parallel_ddl/ob_update_index_status_helper.h",
    "truncate_info/ob_truncate_info_service.h",
    "freeze/ob_global_merge_manager.h",
    "freeze/ob_local_major_freeze.h",
    "freeze/ob_snapshot_gc_scn_renewer.h",
    "ob_control_event.h",
    "ob_runtime_event_def.h",
    "ob_system_bootstrap_service.h",
]


def rootserver_validate_header_inventory(checked_in_headers):
    owner = {}
    for category, headers in [("public", ROOTSERVER_PUBLIC_HEADERS), ("private", ROOTSERVER_PRIVATE_HEADERS)]:
        for path in headers:
            if path in owner:
                fail("Rootserver header %s is owned by both %s and %s" % (path, owner[path], category))
            owner[path] = category
    checked_in = {path: True for path in checked_in_headers}
    missing = sorted([path for path in checked_in if path not in owner])
    stale = sorted([path for path in owner if path not in checked_in])
    if missing or stale:
        fail("Rootserver header ownership differs from the tree: missing=%s stale=%s" % (missing, stale))
